---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 'what"s new' 
summary: En este tema, se incluyen los cambios en las versiones más recientes de System Manager de SANtricity en cuanto a comandos de la CLI y comandos de script. 
---
= Lo nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En este tema, se incluyen los cambios en las versiones más recientes de System Manager de SANtricity en cuanto a comandos de la CLI y comandos de script.

[NOTE]
====
Al emitir un comando SMcli en el símbolo del sistema, es necesario introducir una barra diagonal inversa adicional (`\`) Carácter como carácter de escape en el nombre de la ruta de acceso de un archivo de entrada o de salida cuando se utiliza el sistema operativo Windows. La barra invertida adicional (`\`) Se debe incluir cuando se usa SMcli en el modo seguro, https, proporcionando la opción -u para especificar un usuario de gestión de acceso basado en roles. Ejemplo: `C:\\dir\\subdir\\filename`

====
[NOTE]
====
Si actualmente utiliza SANtricity 11.52 o una versión anterior, no podrá actualizar a la versión más reciente de SANtricity a través de la CLI heredada. Las actualizaciones de SANtricity 11.52 a versiones posteriores solo se pueden realizar a través de SMcli.

====


== SANtricity 11,90

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11,90.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html["Definir límite de tamaño de envío de AutoSupport"]
 a| 
Se añadió el comando



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html["Guarde la CSR de cabina de controladora"]
 a| 
Se ha añadido `KeySize` el parámetro.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-email-smtp-delivery-method.html["Establezca el método de entrega de correo electrónico (SMTP)"]
 a| 
Se ha añadido `destinationAddress` el parámetro.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples["Mostrar configuración de AutoSupport"]
 a| 
Se han agregado límites de tamaño de mensaje y direcciones de correo electrónico de destino en el resultado de ejemplo para el comando.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html["Descargue storageArray keyManagementCertificate"]
 a| 
Se ha añadido `privateKeyFile` el parámetro.

|===


== SANtricity 11,81

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11,81.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices["Identifique los dispositivos"]
 a| 
Añadido `identifyDevices` parámetro.

|===


== SANtricity 11,80

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11,80.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[Guarde los errores de paridad del trabajo de paridad de un volumen]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/start-check-vol-parity-job.adoc[Inicie el trabajo de comprobación de paridad del volumen]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[Muestra los trabajos de comprobación de paridad de volúmenes]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/show-check-vol-parity-job.adoc[Muestra el trabajo de comprobación de paridad del volumen]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/stop-check-vol-parity-job.adoc[Detenga la comprobación del trabajo de paridad del volumen]
 a| 
Se añadió el comando



 a| 
xref:./get-started/command-line-parameters.adoc[Parámetros de la línea de comandos heredados]
 a| 
Añadido `-useLegacyTransferPort` parámetro.



 a| 
xref:./commands-a-z/autoconfigure-storagearray.adoc[Configurar automáticamente la cabina de almacenamiento]
 a| 
Añadido `blockSize` parámetro.



 a| 
xref:./commands-a-z/check-volume-parity.adoc[Comprobar la paridad de un volumen]
 a| 
Comando obsoleto.

|===


== SANtricity 11.70.5

No hay cambios de comandos de script ni de la CLI para la versión 11.70.5.



== SANtricity 11.70.4

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11.70.4.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./get-started/downloadable-smcli-parameters.adoc[Descarga de parámetros de línea de comandos de SMcli]
 a| 
Añadido `-t` y.. `-T` descripciones de parámetros de token de acceso para la autenticación multifactor.

|===


== SANtricity 11.70.3

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11.70.3.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[Iniciar el aprovisionamiento de recursos de pool de discos]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[Inicie el aprovisionamiento de recursos del grupo de volúmenes]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[Inicie el aprovisionamiento completo del pool de discos]
 a| 
Actualizado `disableResourceProvisioning` descripción del parámetro.



 a| 
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[Inicie el aprovisionamiento completo del grupo de volúmenes]
 a| 
Actualizado `disableResourceProvisioning` descripción del parámetro.



 a| 
xref:./commands-a-z/recreate-storagearray-securitykey.html[Vuelva a crear una clave de seguridad externa]
 a| 
Añadido `deleteOldKey` parámetro.



 a| 
xref:./commands-a-z/create-diskpool.html[Crear pool de discos]
 a| 
Actualizado `driveCount` descripción del parámetro.

|===


== SANtricity 11.70.2

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11.70.2.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./commands-a-z/create-snmpuser-username.adoc[Registre el usuario USM de SNMPv3]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/set-snmpuser-username.adoc[Actualice el usuario USM de SNMPv3]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/show-allsnmpusers.adoc[Muestra el usuario USM de SNMPv3]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/delete-snmpuser-username.adoc[Cancele el registro del usuario USM de SNMPv3]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/create-snmptrapdestination.adoc[Registre el destino de captura SNMP]
 a| 
Añadido `userName` y.. `engineid` parámetros.



 a| 
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[Actualice el destino de captura SNMP]
 a| 
Añadido `userName` y.. `engineid` parámetros.



 a| 
xref:./commands-a-z/start-snmptrapdestination.adoc[Probar destino de captura SNMP]
 a| 
Añadido `userName` y.. `engineid` parámetros.

|===


== SANtricity 11.70.1

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11.70.1.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./commands-a-z/start-drive-erase.adoc[Iniciar borrado de unidad]
 a| 
Se añadió el comando



 a| 
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[Importe la clave de seguridad de la cabina de almacenamiento]
 a| 
Añadido `forceOverwrite` parámetro.



 a| 
xref:./commands-a-z/set-controller-hostport.adoc[Configure las propiedades de los puertos de host de la controladora]
 a| 
Añadido `fecMode` parámetro.



 a| 
xref:./commands-a-z/show-syslog-summary.adoc[Mostrar configuración de syslog]
 a| 
Añadido `syslogFormat` parámetro.



 a| 
xref:./commands-a-z/set-syslog.adoc[Configure los ajustes de syslog]
 a| 
Añadido `syslogFormat` parámetro.



 a| 
xref:./commands-a-z/set-emailalert.adoc[Configure los ajustes de alerta de correo electrónico]
 a| 
Añadido `serverEncryption`, `serverPort`, `serverUsername`, y. `serverPassword` parámetros.



 a| 
xref:./commands-a-z/show-emailalert-summary.adoc[Muestra la configuración de alertas de correo electrónico]
 a| 
Añadido `SMTP` datos de parámetros de cifrado, puerto y credencial.



 a| 
xref:./commands-a-z/recover-volume.adoc[Recuperar volumen RAID]
 a| 
Añadido `blockSize` parámetro.

|===


== SANtricity 11.70

En la siguiente tabla, se enumeran los cambios de comandos de la CLI y de script para la versión 11.70.

[cols="2*"]
|===
| Comando | Descripción del cambio 


 a| 
xref:./commands-a-z/download-storagearray-firmware.adoc[Descargue el firmware/NVSRAM de la cabina de almacenamiento]
 a| 
Añadido `healthCheckNeedsAttnOverride` parámetro.



 a| 
xref:./commands-a-z/create-volume-diskpool.adoc[Crear volumen en pool de discos]
 a| 
Añadido `raidLevel` parámetro.



 a| 
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[Habilite la gestión de claves de seguridad externas]
 a| 
Añadido `saveFile` parámetro.



 a| 
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[Deshabilite la gestión de claves de seguridad externas]
 a| 
Añadido `saveFile` parámetro.



 a| 
xref:./commands-a-z/recover-volume.adoc[Recuperar volumen RAID]
 a| 
Añadido `hostUnmapEnabled` parámetro.

|===