---
permalink: get-started/interactive-mode.html 
sidebar: sidebar 
keywords: interactive mode 
summary: 'El modo interactivo le permite ejecutar comandos individuales sin colocar el prefijo de los comandos con `SMcli`.' 
---
= Modo interactivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El modo interactivo le permite ejecutar comandos individuales sin colocar el prefijo de los comandos con `SMcli`.

Si introduce `SMcli` Y el nombre de una cabina de almacenamiento, pero no especifica parámetros de interfaz de línea de comandos, comandos de script ni un archivo de script, la interfaz de línea de comandos se ejecuta en modo interactivo.

En el modo interactivo, se puede introducir un solo comando, ver los resultados e introducir el siguiente comando sin escribir el completo `SMcli` cadena. El modo interactivo es útil para determinar errores de configuración y probar cambios de configuración rápidamente.

Para finalizar una sesión en modo interactivo, se debe escribir el comando específico del sistema operativo. Para Linux, esta combinación de teclas es *Control-D*. Para Windows, esta combinación de teclas es *Control-Z + ENTRAR*.
