---
permalink: get-started/recurring-syntax-elements.html 
sidebar: sidebar 
keywords: recur, syntax, elements 
summary: Los elementos de sintaxis recurrente son una categoría general de parámetros y opciones que se pueden utilizar en los comandos de script. 
---
= Obtenga información sobre los elementos recurrentes de la sintaxis CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los elementos de sintaxis recurrente son una categoría general de parámetros y opciones que se pueden utilizar en los comandos de script. En la siguiente tabla, se enumeran las convenciones utilizadas en los elementos de sintaxis recurrente.

[cols="2*"]
|===
| Convención | Definición 


 a| 
`*a | b*`
 a| 
Alternativa ("a" o "b")



 a| 
`italicized-words`
 a| 
Se necesita una entrada de usuario para completar un parámetro (una respuesta a una variable)



 a| 
`+[ ... ]+` (corchetes)
 a| 
Cero o una aparición (los corchetes también se utilizan como delimitadores para algunos parámetros de comando)



 a| 
`+{ ... }+` (llaves)
 a| 
Cero o más ocurrencias



 a| 
`(*a | b | c*)`
 a| 
Se debe elegir solo una de las alternativas

|===
En la siguiente tabla, se enumeran los parámetros de sintaxis recurrente y los valores que se pueden utilizar con los parámetros de sintaxis recurrente.

[cols="2*"]
|===
| Sintaxis recurrente | Valor de sintaxis 


 a| 
`_autoconfigure-vols-attr- value-list_`
 a| 
{`_autoconfigure-vols-attr-value-pair_` {`_autoconfigure-vols-attr-value-pair_`}



 a| 
`_autoconfigure-vols-attr- value-pair_`
 a| 
[listing]
----
driveType=drive-type | driveMediaType=drive-media-type |
raidLevel=raid-level | volumeGroupWidth=integer-literal |
volumeGroupCount=integer-literal | volumesPerGroupCount=integer-literal6|
hotSpareCount=integer-literal | segmentSize=segment-size-spec | cacheReadPrefetch=(TRUE | FALSE)
securityType=(none | capable | enabled)7| dataAssurance=(none | enabled)5
----


 a| 
`_boolean_`
 a| 
[listing]
----
(TRUE | FALSE)
----


 a| 
`_cache-flush-modifier- setting_`
 a| 
[listing]
----
immediate, 0, .25, .5, .75, 1, 1.5, 2, 5, 10, 20, 60, 120, 300, 1200, 3600, infinite
----


 a| 
`_capacity-spec_`
 a| 
`_integer-literal_` `[KB | MB | GB | TB | Bytes]`



 a| 
`_count-based-repository- spec_`
 a| 
[listing]
----
repositoryRAIDLevel =repository-raid-level repositoryDriveCount=integer-literal
[repositoryVolumeGroupUserLabel =user-label] [driveType=drive-type4
] [trayLossProtect=(TRUE | FALSE)1] | [drawerLossProtect=(TRUE | FALSE)2] |
[dataAssurance=(none | enabled)5] |
----


 a| 
`_create-raid-vol-attr- value-list_`
 a| 
{`_create-raid-volume-attribute-value-pair_` {`_create-raid-volume-attribute-value-pair_`}



 a| 
`_create-raid-volume- attribute-value-pair_`
 a| 
[listing]
----
capacity=capacity-spec | owner=(a | b) |
cacheReadPrefetch=(TRUE | FALSE) | segmentSize=integer-literal |
usageHint=usage-hint-spec
----


 a| 
`_create-volume-copy-attr- value-list_`
 a| 
{`_create-volume-copy-attr-value-pair_` {`_create-volume-copy-attr-value-pair_`}



 a| 
`_create-volume-copy-attr- value-pair_`
 a| 
[listing]
----
copyPriority=(highest | high | medium | low | lowest) |
targetReadOnlyEnabled=(TRUE | FALSE) | copyType=(offline | online) |
repositoryPercentOfBase=(20 | 40 | 60 | 120 | default) |
repositoryGroupPreference=(sameAsSource | otherThanSource | default)
----


 a| 
`_drive-media-type_`
 a| 
`(HDD | SSD | unknown | allMedia)` _HDD_ significa unidad de disco duro. _SSD_ significa disco de estado sólido.



 a| 
`_drive-spec_`
 a| 
`_trayID,slotID` o. `trayID,drawerID,slotID_` Una unidad se define con dos o tres valores literales de números enteros separados por coma. Los soportes de densidad baja requieren dos valores. Los soportes de densidad alta, los que tienen cajones, requieren tres valores.



 a| 
`_drive-spec-list_`
 a| 
 `_drive-spec_` `_drive-spec_`



 a| 
`drive-type`
 a| 
`(fibre | SATA | SAS)`

[NOTE]
====
Solo se admiten unidades SAS para las versiones de firmware 7.86 y posteriores.

====


 a| 
`_error-action_`
 a| 
`(stop | continue)`



 a| 
`_ethernet-port-options_`
 a| 
[listing]
----
enableIPv4=(TRUE | FALSE) | enableIPv6=(TRUE | FALSE) |
IPv6LocalAddress=ipv6-address | IPv6RoutableAddress=ipv6-address |
IPv6RouterAddress=ipv6-address | IPv4Address=ip-address |
IPv4ConfigurationMethod= (static | dhcp) | IPv4GatewayIP=ip-address |
IPv4SubnetMask=ip-address | duplexMode=(TRUE | FALSE) | portSpeed=(autoNegotiate | 10 | 100 |
1000)
----


 a| 
`_feature-identifier_`
 a| 
[NOTE]
====
De manera predeterminada, todas las funciones de SANtricity 11.40 se encuentran habilitadas.

====


 a| 
`_filename_`
 a| 
`_string-literal_`



 a| 
`_gid_`
 a| 
`_string-literal_`



 a| 
`_hex-literal_`
 a| 
Un valor literal comprendido entre 0x00 y 0xFF.



 a| 
`_host-card-identifier_`
 a| 
`(1 | 2 | 3 | 4)`



 a| 
`_host-type_`
 a| 
`string-literal`| `integer-literal`



 a| 
`_instance-based- repository-spec_`
 a| 
[listing]
----
(repositoryRAIDLevel =repository-raid-level repositoryDrives= (drive-spec-list)
[repositoryVolumeGroupUserLabel =user-label] [trayLossProtect=(TRUE | FALSE)1]) |
[drawerLossProtect=(TRUE | FALSE)2]) | (repositoryVolumeGroup=user-label
[freeCapacityArea=integer-literal3])
----
Especifique el `*repositoryRAIDLevel*` con el `*repositoryDrives*` parámetro. No se debe especificar el nivel de RAID ni las unidades con el grupo de volúmenes. No configure un valor para `*trayLossProtect*` parámetro al especificar un grupo de volúmenes.



 a| 
`_ip-address_`
 a| 
`*(0-255).(0-255).(0-255).(0-255)*`



 a| 
`_ipv6-address_`
 a| 
`*(0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF): (0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF)*`

Se deben introducir los 32 caracteres hexadecimales.



 a| 
`_iscsi-host-port_`
 a| 
[listing]
----
(1 | 2 | 3 | 4)
----
El número de puerto de host puede ser 2, 3 o 4, según el tipo de controladora que se esté usando.



 a| 
`_iscsi-host-port-options_`
 a| 
[listing]
----
IPv4Address=ip-address | IPv6LocalAddress=ipv6-address |
IPv6RoutableAddress=ipv6-address | IPv6RouterAddress=ipv6-address |
enableIPv4=(TRUE | FALSE) | enableIPv6=(TRUE | FALSE) | enableIPv4Priority=(TRUE | FALSE) |
enableIPv6Priority=(TRUE | FALSE) | IPv4ConfigurationMethod=(static | dhcp) |
IPv6ConfigurationMethod= (static | auto) | IPv4GatewayIP=ip-address |
IPv6HopLimit=integer | IPv6NdDetectDuplicateAddress=integer |
IPv6NdReachableTime=time-interval | IPv6NdRetransmitTime=time-interval |
IPv6NdTimeOut=time-interval | IPv4Priority=integer |
IPv6Priority=integer | IPv4SubnetMask=ip-address |
IPv4VlanId=integer | IPv6VlanId=integer |
maxFramePayload=integer | tcpListeningPort=tcp-port-id |
portSpeed=(autoNegotiate | 1 | 10)
----


 a| 
`_iscsiSession_`
 a| 
[listing]
----
[session-identifier]
----


 a| 
`_nvsram-offset_`
 a| 
`_hex-literal_`



 a| 
`_nvsramBitSetting_`
 a| 
`_nvsram-mask, nvsram-value_` = `_0xhexadecimal, 0xhexadecimal_` | `_integer-literal_`

La `_0xhexadecimal_` El valor suele ser un valor entre 0x00 y 0xFF.



 a| 
`_nvsramByteSetting_`
 a| 
`_nvsram-value_` = `_0xhexadecimal_` | `_integer-literal_`

La `0xhexadecimal` El valor suele ser un valor entre 0x00 y 0xFF.



 a| 
`_portID_`
 a| 
[listing]
----
(0-127)
----


 a| 
`_raid-level_`
 a| 
[listing]
----
(0 | 1 | 3 | 5 | 6)
----


 a| 
`_recover-raid-volume-attr- value-list_`
 a| 
{`_recover-raid-volume-attr-value-pair_` {`_recover-raid-volume-attr-value-pair_`}



 a| 
`_recover-raid-volume-attr- value-pair_`
 a| 
[listing]
----
owner=(a|b) |cacheReadPrefetch=(TRUE | FALSE) | dataAssurance=(none | enabled)
----


 a| 
`_repository-raid-level_`
 a| 
[listing]
----
(1 | 3 | 5 | 6)
----


 a| 
`_repository-spec_`
 a| 
`instance-based-repository-spec` | `count-based-repository-spec`



 a| 
`_segment-size-spec_`
 a| 
`_integer-literal_` - todas las capacidades se encuentran en la base 2.



 a| 
`_serial-number_`
 a| 
[listing]
----
string-literal
----


 a| 
`_slotID_`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

[listing]
----
(drive=\(trayID,[drawerID,]slotID\)|
drives=\(trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\) )
----


 a| 
`_test-devices_`
 a| 
[listing]
----
controller=(a|b)
esms=(esm-spec-list)drives=(drive-spec-list)
----


 a| 
`_test-devices-list_`
 a| 
{`_test-devices_` {`_test-devices_`}



 a| 
`_time-zone-spec_`
 a| 
[listing]
----
(GMT+HH:MM | GMT-HH:MM) [dayLightSaving=HH:MM]
----


 a| 
`_trayID-list_`
 a| 
{`_trayID_` {`_trayID_`}



 a| 
`_usage-hint-spec_`
 a| 
[listing]
----
usageHint=(multiMedia | database | fileSystem)
----
La controladora utiliza el Consejo de uso o las características de I/o esperadas del volumen para indicar un tamaño de segmento de volumen predeterminado adecuado y la captura previa de lectura de caché dinámica. En el caso de los sistemas de archivos y las bases de datos, se utiliza un tamaño de segmento de 128 KB. En el caso de los archivos multimedia, se utiliza un tamaño de segmento de 256 KB. Los tres consejos de uso habilitan la captura previa de lectura de caché dinámica.



 a| 
`_user-label_`
 a| 
`_string-literal_`

Los caracteres válidos son los alfanuméricos, el guion y el guion bajo.



 a| 
`_user-label-list_`
 a| 
{`_user-label_` {`_user-label_`}



 a| 
`_volumeGroup-number_`
 a| 
`_integer-literal_`



 a| 
`_wwID_`
 a| 
`_string-literal_`

|===
1para que la protección contra pérdida de soporte funcione, la configuración debe respetar las siguientes directrices:

[cols="3*"]
|===
| Nivel | Criterios para la protección contra pérdida de soporte | Cantidad mínima requerida de bandejas 


 a| 
Pool de discos
 a| 
El pool de discos consta de dos unidades como máximo en un solo soporte
 a| 
6



 a| 
RAID 6
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo soporte
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Cada unidad del grupo de volúmenes se encuentra en un soporte aparte
 a| 
3



 a| 
RAID 1
 a| 
Cada unidad de una pareja RAID 1 se debe ubicar en un soporte aparte
 a| 
2



 a| 
RAID 0
 a| 
No puede contar con protección contra pérdida de soporte.
 a| 
No aplicable

|===
2para que la protección contra pérdida de cajón funcione, la configuración debe respetar las siguientes directrices:

[cols="3*"]
|===
| Nivel | Criterios para la protección contra pérdida de cajón | Cantidad mínima requerida de cajones 


 a| 
Pool de discos
 a| 
El pool incluye las unidades de los cinco cajones y existe la misma cantidad de unidades por cajón. Un soporte de 60 unidades puede brindar protección contra pérdida de cajón cuando el pool de discos consta de 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 unidades.
 a| 
5



 a| 
RAID 6
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo cajón.
 a| 
3



 a| 
RAID 3 o RAID 5
 a| 
Cada unidad del grupo de volúmenes se encuentra en un cajón aparte.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidad de una pareja reflejada se debe ubicar en un cajón aparte.
 a| 
2



 a| 
RAID 0
 a| 
No puede contar con protección contra pérdida de cajón.
 a| 
No aplicable

|===
Si un grupo de volúmenes se extiende por varios soportes en la configuración de la cabina de almacenamiento, se debe comprobar que la configuración para la protección contra pérdida de cajón funcione con la configuración para la protección contra pérdida de soporte. Es posible contar con protección contra pérdida de cajón sin protección contra pérdida de soporte. No es posible contar con protección contra pérdida de soporte sin protección contra pérdida de cajón. Si la `*trayLossProtect*` y la `*drawerLossProtect*` no están configurados en el mismo valor, la cabina de almacenamiento muestra un mensaje de error y no se creará la configuración de la cabina de almacenamiento.

3 para determinar si existe un área de capacidad libre, ejecute el `show volumeGroup` comando.

4 la unidad predeterminada (tipo de unidad) es `SAS`.

La `*driveType*` no es necesario parámetro si la cabina de almacenamiento contiene un solo tipo de unidad. Si utiliza la `*driveType*` parámetro, también debe usar el `*hotSpareCount*` y la `*volumeGroupWidth*` parámetro.

5 la `*dataAssurance*` El parámetro se relaciona con la función de garantía de datos (DA).

La función Data Assurance (DA) mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite a la cabina de almacenamiento comprobar si se producen errores cuando se transfieren datos entre hosts y unidades. Si esta función está habilitada, la cabina de almacenamiento añade códigos de comprobación de errores (también conocidos como comprobaciones de redundancia cíclicas o CRC) a cada bloque de datos del volumen. Una vez movido un bloque de datos, la cabina de almacenamiento utiliza estos códigos de CRC para determinar si se produjeron errores durante la transmisión. Los datos posiblemente dañados no se escriben en el disco ni se vuelven a transferir al host.

Si desea usar la función DA, comience con un pool o grupo de volúmenes que solo incluya unidades que sean compatibles con DA. A continuación, cree volúmenes compatibles con DA. Por último, asigne estos volúmenes compatibles con DA al host por medio de una interfaz de I/o compatible con DA. Las interfaces de I/o compatibles con DA son Fibre Channel, SAS e Iser over InfiniBand (extensiones iSCSI para RDMA/IB). ISCSI sobre Ethernet o SRP over InfiniBand no admiten LA función DA.

[NOTE]
====
Cuando todo el hardware necesario y la interfaz de I/o son compatibles CON DA, puede configurar la `*dataAssurance*` parámetro a. `enabled` Y luego usar DA con ciertas operaciones. Por ejemplo, es posible crear un grupo de volúmenes que incluya unidades compatibles con DA y, luego, crear un volumen dentro de ese grupo que tenga la función DA habilitada. Otras operaciones que usan volúmenes con la función DA habilitada tienen opciones para admitir la función DA.

====
6 la `*volumesPerGroupCount*` parámetro es la cantidad de volúmenes de capacidad equivalente por grupo de volúmenes.

7 la `*securityType*` el parámetro permite especificar la configuración de seguridad para el grupo de volúmenes que se va a crear. Todos los volúmenes se establecen en la configuración de seguridad seleccionada. Algunas de las opciones disponibles para establecer la configuración de seguridad son:

* `none` -- el grupo de volúmenes no es seguro.
* `capable` -- el grupo de volúmenes es compatible con la función de seguridad, pero no tiene la seguridad habilitada.
* `enabled` -- el grupo de volúmenes tiene la función de seguridad habilitada.


[NOTE]
====
Se debe crear una clave de seguridad para la cabina de almacenamiento si desea establecer `*securityType=enabled*`. (Para crear una clave de seguridad de la cabina de almacenamiento, utilice `create storageArray securityKey` ).

====