---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: El comando activate storageArray feature activa la función Asynchronous Mirroring. 
---
= Activar la duplicación asincrónica - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `activate storageArray feature` El comando activa la función Asynchronous Mirroring.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento, incluidas las matrices E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.

[NOTE]
====
Este comando solo se aplica para mirroring asíncrono a través de Fibre Channel.

====


[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600 o EF300, debes tener el rol de Storage Admin.



[[context]]
== Contexto

Después de activar la función de mirroring asíncrono, debe configurar un grupo de reflejos asíncrono y una pareja reflejada asíncrona.



[[syntax]]
== Sintaxis

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


[[parameters]]
== Parámetros

Ninguno.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
