---
permalink: commands-a-z/activate-storagearray-firmware.html 
sidebar: sidebar 
keywords: activate, storage array, firmware, syntax, parameter, minimum, level 
summary: El comando activate storageArray firmware activa el firmware que se descargó previamente en el área de configuración pendiente de las controladoras de la cabina de almacenamiento. 
---
= Activar el firmware de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `activate storageArray firmware` el comando activa el firmware que se descargó previamente en el área de configuración pendiente de las controladoras de la cabina de almacenamiento.



== Sintaxis

[source, cli]
----
activate storageArray firmware
[healthCheckMelOverride=(TRUE | FALSE)]
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`healthCheckMelOverride`
 a| 
El ajuste para anular los resultados de la comprobación de estado del registro de eventos serios (MEL). La validación DE MEL se ejecuta de todos modos; no se omite. Si se produce un error en la comprobación de MEL, es posible omitir el error mediante el uso de este parámetro cuando se ejecuta el comando.

Antes de cualquier activación, la controladora comprueba el registro de eventos para determinar si se produjo algún evento que pudiera impedir la correcta activación del nuevo firmware de la controladora. Si se produjo algún evento de este tipo, la controladora normalmente no activa el nuevo firmware.

El parámetro fuerza a la controladora a activar el nuevo firmware. El valor predeterminado es `FALSE`. Establezca este valor en `TRUE` si desea forzar la controladora a activar el nuevo firmware de la controladora.

|===


== Nivel de firmware mínimo

8.10 añade el `healthCheckMelOverride` parámetro.
