---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: El comando activate storageArray feature activa la función Asynchronous Mirroring. 
---
= Activar la duplicación asincrónica - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `activate storageArray feature` El comando activa la función Asynchronous Mirroring.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.

[NOTE]
====
Este comando solo se aplica para mirroring asíncrono a través de Fibre Channel.

====


== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Después de activar la función de mirroring asíncrono, debe configurar un grupo de reflejos asíncrono y una pareja reflejada asíncrona.



== Sintaxis

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
