---
permalink: commands-a-z/activate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, synchronous mirroring, supported arrays, roles, context, syntax, parameters, data assurance management, minimum firmware level 
summary: El comando activate storageArray feature activa la función Synchronous Mirroring y crea el volumen de repositorios de reflejos. 
---
= Activar el mirroring síncrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `activate storageArray feature` El comando activa la función Synchronous Mirroring y crea el volumen de repositorios de reflejos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800 y E5700, Siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800 o E5700, se deben poseer los roles Storage Admin.



== Contexto

Cuando se utiliza este comando, se puede definir el volumen de repositorios de reflejos mediante una de tres maneras:

* Unidades definidas por el usuario
* Grupo de volúmenes definido por el usuario
* Cantidad de unidades definida por el usuario


Si se opta por definir una cantidad de unidades, el firmware de la controladora elige las unidades que se utilizarán para el volumen de repositorios de reflejos.

[NOTE]
====
En las versiones anteriores de este comando, el identificador de función era `remoteMirror`. Este identificador de función ya no es válido y lo reemplaza `syncMirror`.

====


== Sintaxis (unidades definidas por el usuario)

[listing, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_,pass:quotes[[_drawerIDn_,]pass:quotes[_slotIDn_
[driveType=(fibre | SATA | SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[listing, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 5 | 6)
repositoryDrives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn)_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Sintaxis (grupo de volúmenes definido por el usuario)

[listing, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryVolumeGroup=pass:quotes[_volumeGroupName_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== Sintaxis (cantidad de unidades definida por el usuario)

[listing, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[listing, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`repositoryRAIDLevel`
 a| 
Nivel de RAID para el volumen de repositorios de reflejos. Los valores válidos son `0`, `1`, `3`, `5`, o. `6`.



 a| 
`repositoryDrives`
 a| 
Las unidades para el volumen de repositorios de reflejos. En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
El nombre que se desea otorgar al nuevo grupo de volúmenes donde se ubicará el volumen de repositorios de reflejos. El nombre del grupo de volúmenes debe escribirse entre comillas dobles (" ").



 a| 
`repositoryVolumeGroup`
 a| 
El nombre del grupo de volúmenes de repositorios de reflejos donde se encuentra el volumen de repositorios de reflejos. (Para determinar los nombres de los grupos de volúmenes en la cabina de almacenamiento, ejecute el `show storageArray profile` ).



 a| 
`freeCapacityArea`
 a| 
El número de índice del espacio libre en un grupo de volúmenes existentes que se desea usar para crear el volumen de repositorios de reflejos. La capacidad libre es la capacidad libre en los volúmenes existentes de un grupo de volúmenes. Por ejemplo, un grupo de volúmenes puede incluir las siguientes áreas: Volumen 1, capacidad libre, volumen 2, capacidad libre, volumen 3, capacidad libre. Para usar la capacidad libre seguida del volumen 2, se debe especificar lo siguiente:

[listing]
----
freeCapacityArea=2
----
Ejecute el `show volumeGroup` comando para determinar si existe un área de capacidad libre.



 a| 
`repositoryDriveCount`
 a| 
Cantidad de unidades sin asignar que se desean usar para el volumen de repositorios de reflejos.



 a| 
`driveType`
 a| 
El tipo de unidad acerca del cual se desea recuperar información. No es posible mezclar tipos de unidad.

Los tipos de unidades válidos son los siguientes:

* `fibre`
* `SATA`
* `SAS`
* NVMe4K


Si no se especifica un tipo de unidad, los valores predeterminados del comando son all type.



 a| 
`trayLossProtect`
 a| 
Configuración para aplicar la protección contra pérdida de soporte cuando se crea el volumen de repositorios de reflejos. Para aplicar la protección contra pérdida de soporte, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`drawerLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de cajón cuando se crea el volumen de repositorios de reflejos. Para aplicar la protección contra pérdida de cajón, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.

|===


== Notas

La `repositoryDrives` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.

Si las unidades que se seleccionan para el `repositoryDrives` los parámetros no son compatibles con otros parámetros (como la `repositoryRAIDLevel` Parámetro), el comando de script devuelve un error y la función de mirroring síncrono no está activada. El error devuelve la cantidad de espacio necesaria para el volumen de repositorios de reflejos. Luego, es posible volver a introducir el comando y especificar la cantidad de espacio adecuada.

Si se introduce un valor de espacio de almacenamiento del repositorio demasiado pequeño para los volúmenes de repositorios de reflejos, el firmware de la controladora devuelve un mensaje de error que indica la cantidad de espacio necesario para los volúmenes de repositorios de reflejos. El comando no intenta activar mirroring síncrono. Para volver a introducir el comando, se puede utilizar el valor del mensaje de error para el valor del espacio de almacenamiento del repositorio.

Cuando se asignan las unidades, si se configuran las `trayLossProtect` parámetro a. `TRUE` y seleccionó más de una unidad de cualquier soporte, la cabina de almacenamiento muestra un error. Si establece la `trayLossProtect` parámetro a. `FALSE`, la cabina de almacenamiento realiza operaciones, pero es posible que el grupo de volúmenes creado no tenga protección contra pérdida de soporte.

Cuando el firmware de la controladora asigna las unidades, si se configuran las `trayLossProtect` parámetro a. `TRUE`, la cabina de almacenamiento devuelve un error si el firmware de la controladora no puede proporcionar unidades que den como resultado que el nuevo grupo de volúmenes tenga protección contra pérdida de soporte. Si establece la `trayLossProtect` parámetro a. `FALSE`, la cabina de almacenamiento realiza la operación aunque esto implique que el grupo de volúmenes no tenga protección contra pérdida de soporte.

La `drawerLossProtect` el parámetro determina si se puede acceder a los datos de un volumen si el cajón presenta errores. Cuando se asignan las unidades, si se configuran las `drawerLossProtect` parámetro a. `TRUE` y seleccione más de una unidad de cualquier cajón, la cabina de almacenamiento devuelve un error. Si establece la `drawerLossProtect` parámetro a. `FALSE`, la cabina de almacenamiento realiza operaciones, pero es posible que el grupo de volúmenes creado no tenga protección contra pérdida de cajón.



== Gestión de garantía de datos

La función Data Assurance (DA) mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite a la cabina de almacenamiento comprobar si se producen errores cuando se transfieren datos entre hosts y unidades. Si esta función está habilitada, la cabina de almacenamiento añade códigos de comprobación de errores (también conocidos como comprobaciones de redundancia cíclicas o CRC) a cada bloque de datos del volumen. Una vez movido un bloque de datos, la cabina de almacenamiento utiliza estos códigos de CRC para determinar si se produjeron errores durante la transmisión. Los datos posiblemente dañados no se escriben en el disco ni se vuelven a transferir al host.

Si desea usar la función DA, comience con un pool o grupo de volúmenes que solo incluya unidades que sean compatibles con DA. A continuación, cree volúmenes compatibles con DA. Por último, asigne estos volúmenes compatibles con DA al host por medio de una interfaz de I/o compatible con DA. Las interfaces de I/o compatibles con DA son Fibre Channel, SAS e Iser over InfiniBand (extensiones iSCSI para RDMA/IB). ISCSI sobre Ethernet o SRP over InfiniBand no admiten LA función DA.

[NOTE]
====
Si todas las unidades son compatibles con DA, es posible configurar la `dataAssurance` parámetro a. `enabled` Y luego usar DA con ciertas operaciones. Por ejemplo, es posible crear un grupo de volúmenes que incluya unidades compatibles con DA y, luego, crear un volumen dentro de ese grupo que tenga la función DA habilitada. Otras operaciones que usan volúmenes con la función DA habilitada tienen opciones para admitir la función DA.

====
Si la `dataAssurance` el parámetro se establece en `enabled`, sólo se considerarán unidades compatibles con garantía de datos para candidatos de volumen; de lo contrario, se considerarán unidades compatibles con garantía de datos o no compatibles con esta función. Si solamente existen unidades con garantía de datos disponibles, se crea el nuevo grupo de volúmenes mediante las unidades compatibles con esa función.



== Nivel de firmware mínimo

7.10 añade la funcionalidad para el nivel de RAID 6.

7.60 añade el `drawerID` entrada del usuario, la `driveMediaType` y la `drawerLossProtect` parámetro.

7.75 añade el `dataAssurance` parámetro.

8.10 elimina la `driveMediaType` parámetro.

8.60 añade el `driveType` parámetro.
