---
permalink: commands-a-z/add-drives-to-ssd-cache.html 
sidebar: sidebar 
keywords: add drives ssd cache, supported arrays, syntax, parameters, minimum firmware level 
summary: 'El comando set ssdCache permite agregar discos de estado sólido (SSD) para aumenta la capacidad de la caché SSD existente.' 
---
= Agregar unidades a la caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set ssdCache` El comando aumenta la capacidad de una caché SSD existente agregando más discos de estado sólido (SSD).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.

[NOTE]
====
Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de soporte.

====


== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[set ssdCache [_ssdCacheName_]]
pass:quotes[addDrives=(_trayID1_,[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_,]pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
El nombre de la caché SSD a la cual se desea añadir SSD. El nombre debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`addDrives`
 a| 
Las unidades que se desean añadir a la caché SSD.para los soportes de unidades de gran capacidad, se deben especificar el valor de ID de soporte, el valor de ID de cajón y el valor de ID de ranura para la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

|===


== Notas

La caché SSD puede contener cualquier número de SSD. El tamaño máximo de la caché SSD es 5 TB, pero puede ser menor según el tamaño de la caché primaria de la controladora.



== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
