---
permalink: commands-a-z/change-ssd-cache-application-type.html 
sidebar: sidebar 
keywords: ssd cache application type 
summary: El comando set ssdCache cambia el tipo de aplicación asociado con la caché SSD. El tipo de aplicación puede ser servidor web, base de datos o multimedia. Cuando se modifica el tipo de aplicación, se modifica el tamaño del bloque, el tamaño del bloque secundario, el umbral de relleno en lectura y el umbral de relleno en escritura para los volúmenes subyacentes de la caché SSD. 
---
= Cambiar el tipo de aplicación de caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set ssdCache` El comando cambia el tipo de aplicación asociado con la caché SSD. El tipo de aplicación puede ser servidor web, base de datos o multimedia. Cuando se modifica el tipo de aplicación, se modifica el tamaño del bloque, el tamaño del bloque secundario, el umbral de relleno en lectura y el umbral de relleno en escritura para los volúmenes subyacentes de la caché SSD.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Support Admin.



== Sintaxis

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]usageHint=(webServer|dataBase|fileSystem)
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
Nombre de la caché SSD para la que se desea cambiar el tipo de aplicación. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD incluye caracteres especiales o está compuesto solo de números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`usageHint`
 a| 
Los valores se basan en el patrón de uso de I/o típico de la aplicación que utiliza la caché SSD. Los valores válidos son `webServer`, `dataBase`, o. `fileSystem`.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
