---
permalink: commands-a-z/check-repositoryconsistency.html 
sidebar: sidebar 
keywords: check, repository, consistency 
summary: El comando check repositoryConsistency produce un informe basado en el análisis de los datos en un volumen de repositorios subyacente del objeto especificado. 
---
= Comprobar la coherencia de un repositorio
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `check repositoryConsistency` el comando genera un informe basado en el análisis de los datos del volumen de repositorios subyacente de un objeto especificado.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[listing, subs="+macros"]
----
check (snapGroup pass:quotes[[_snapGroupName_]] repositoryConsistency |
snapVolume pass:quotes[[_snapVolumeName_]] repositoryConsistency |
volume pass:quotes[[_volumeName_]] repositoryConsistency |
volumeCopy target pass:quotes[[_targetName_]] repositoryConsistency |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[_"localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`repositoryConsistency`
 a| 
Especifica que se comprobó la coherencia del grupo Snapshot, del volumen Snapshot, del volumen o del grupo de reflejos asíncronos (según lo que especifique el parámetro correspondiente).



 a| 
`snapGroup`
 a| 
Nombre del grupo Snapshot en el que se realizará una comprobación de coherencia. El nombre del grupo Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo Snapshot contiene caracteres especiales o está compuesto solo por números, también debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`snapVolume`
 a| 
Nombre del volumen Snapshot en el que se realizará una comprobación de coherencia. El nombre del volumen Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del volumen Snapshot contiene caracteres especiales o está compuesto solo por números, también debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`volume`
 a| 
Nombre del volumen fino en el que se realizará una comprobación de coherencia. El nombre del volumen fino debe escribirse entre corchetes ([ ]). Si el nombre del volumen fino contiene caracteres especiales o está compuesto solo por números, también debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`volumeCopy`
 a| 
Especifica que se comprueba la coherencia del objetivo de una relación de copia de volumen.



 a| 
`target`
 a| 
Utilice sólo junto con la `volumeCopy` parámetro para especificar el nombre del volumen que es el objetivo de la relación de copia de volumen. Si el nombre del volumen contiene caracteres especiales o está compuesto solo por números, también debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`asyncMirrorGroup`
 a| 
El nombre del grupo de reflejos asíncronos en el que se realizará una comprobación de coherencia. El nombre del grupo de reflejos asíncronos debe escribirse entre corchetes ([ ]). Si el nombre del grupo de reflejos asíncronos contiene caracteres especiales o está compuesto solo por números, también se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`localVolume`
 a| 
Utilice sólo con la `asyncMirrorGroup` parámetro para especificar el nombre de un volumen local que participa en la relación de reflejo. Se puede especificar un volumen local que sea el origen o el destino de una relación de reflejo. El nombre del volumen local debe escribirse entre comillas dobles (" ").



 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardará el informe que se origina como resultado de la comprobación de coherencia. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` Este parámetro debe aparecer en último lugar, después de los parámetros opcionales.

|===


== Notas

El soporte técnico utiliza el informe generado por este comando para analizar problemas.



== Nivel de firmware mínimo

7.83
