---
permalink: commands-a-z/clear-volume-unreadablesectors.html 
sidebar: sidebar 
keywords: clear, volume, unreadable, sectors 
summary: El comando clear volume unreadableSectors borra la información de sectores ilegibles de un volumen o más. 
---
= Borrar sectores ilegibles del volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `clear volume unreadableSectors` el comando borra la información de sectores ilegibles de uno o más volúmenes.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
clear (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]]) unreadableSectors
----


[[parameters]]
== Parámetros

|===
| Parámetro | Descripción 


 a| 
`allVolumes`
 a| 
La configuración para borrar información de sectores ilegibles de todos los volúmenes de la cabina de almacenamiento.



 a| 
`volume`
 a| 
El nombre de un volumen para el cual se borra información de sectores ilegibles. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`volumes`
 a| 
Los nombres de varios volúmenes para los cuales se borra información de sectores ilegibles. Para introducir los nombres de los volúmenes miembro, se deben respetar las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.


|===


[[notes]]
== Notas

Puedes utilizar cualquier combinación de caracteres alfanuméricos, guiones y guiones bajos para los nombres. Los nombres de los volúmenes estándar y delgados pueden tener un máximo de 60 caracteres.
