---
permalink: commands-a-z/clear-storagearray-eventlog.html 
sidebar: sidebar 
keywords: clear, storage array, event log 
summary: El comando clear storageArray EventLog borra el registro de eventos en la cabina de almacenamiento eliminando los datos en el búfer del registro de eventos. 
---
= Borrar registro de eventos de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `clear storageArray eventLog` Comando borra el registro de eventos en la cabina de almacenamiento eliminando los datos en el búfer del registro de eventos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

[NOTE]
====
*Posible daño en la configuración de la cabina de almacenamiento* -- tan pronto como se ejecuta este comando, se elimina el registro de eventos existente en la cabina de almacenamiento.

====


== Sintaxis

[listing]
----
clear storageArray eventLog
----


== Parámetros

Ninguno.
