---
permalink: commands-a-z/clear-storagearray-firmwarependingarea.html 
sidebar: sidebar 
keywords: clear, storage array, firmware, pending, area 
summary: El comando clear storageArray firmwarePendingArea elimina una imagen de firmware o valores de NVSRAM que se descargaron previamente del búfer de área pendiente. 
---
= Borrar el área pendiente del firmware de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `clear storageArray firmwarePendingArea` El comando elimina una imagen de firmware o los valores de NVSRAM que se descargaron previamente del búfer de área pendiente.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

[NOTE]
====
*Posible daño a la configuración de la cabina de almacenamiento* -- tan pronto como se ejecuta este comando, se elimina el contenido del área pendiente existente en la cabina de almacenamiento.

====


== Sintaxis

[source, cli]
----
clear storageArray firmwarePendingArea
----


== Parámetros

Ninguno.
