---
permalink: commands-a-z/clear-storagearray-eventlog.html 
sidebar: sidebar 
keywords: clear, storage array, event log 
summary: El comando clear storageArray EventLog borra el registro de eventos en la cabina de almacenamiento eliminando los datos en el búfer del registro de eventos. 
---
= Borrar el registro de eventos de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `clear storageArray eventLog` Comando borra el registro de eventos en la cabina de almacenamiento eliminando los datos en el búfer del registro de eventos.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

[NOTE]
====
*Posible daño en la configuración de la cabina de almacenamiento* -- tan pronto como se ejecuta este comando, se elimina el registro de eventos existente en la cabina de almacenamiento.

====


== Sintaxis

[source, cli]
----
clear storageArray eventLog
----


== Parámetros

Ninguno.
