---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: El comando create volumeGroup permite crear un grupo de volúmenes con capacidad libre o un grupo de volúmenes con un volumen cuando se introduce un conjunto de unidades sin asignar. 
---
= Crear un grupo de volúmenes - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `create volumeGroup` comando crea un grupo de volúmenes con capacidad libre o un grupo de volúmenes con un volumen cuando se introduce un conjunto de unidades sin asignar.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`drives`
 a| 
Las unidades que se desean asignar al grupo de volúmenes que se va a crear. En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`raidLevel`
 a| 
El nivel de RAID del grupo de volúmenes que contiene el volumen. Los valores válidos son `0`, `1`, `3`, `5`, o. `6`.



 a| 
`userLabel`
 a| 
El nombre que se desea otorgar al nuevo grupo de volúmenes. El nombre del grupo de volúmenes debe escribirse entre comillas dobles (" ").



 a| 
`driveMediaType`
 a| 
El tipo de unidad que se desea usar para el grupo de volúmenes

Se debe usar este parámetro cuando hay más de un tipo de medio de unidad en la cabina de almacenamiento.

Las unidades válidas son las siguientes:

* `HDD` -- Utilice esta opción cuando tenga unidades de disco duro en la bandeja de unidades
* `SSD` -- esta opción se usa cuando hay unidades de estado sólido en el soporte de unidades
* `unknown` -- use esta opción si no está seguro de qué tipos de unidades hay en el soporte
* `allMedia` -- esta opción se usa cuando se desean utilizar todos los tipos de unidades del soporte




 a| 
`driveType`
 a| 
El tipo de unidad que se desea usar en el grupo de volúmenes. No es posible mezclar tipos de unidad.

Se debe usar este parámetro cuando existe más de un tipo de unidad en la cabina de almacenamiento.

Los tipos de unidades válidos son los siguientes:

* `SAS`
* `NVMe4K`


Si no se especifica un tipo de unidad, el código no verifica si las unidades especificadas corresponden a este tipo de unidad.



 a| 
`trayLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de soporte cuando se crea el grupo de volúmenes. Para aplicar la protección contra pérdida de soporte, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`drawerLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de cajón cuando se crea el grupo de volúmenes. Para aplicar la protección contra pérdida de cajón, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`securityType`
 a| 
El ajuste para especificar el nivel de seguridad cuando se crean los grupos de volúmenes y todos los volúmenes asociados. Los ajustes válidos son los siguientes:

* `none` -- el grupo de volúmenes y los volúmenes no están protegidos.
* `capable` -- el grupo de volúmenes y los volúmenes pueden tener la configuración de seguridad, pero la seguridad no está habilitada.
* `enabled` -- el grupo de volúmenes y los volúmenes tienen la seguridad habilitada.




 a| 
`resourceProvisioningCapable`
 a| 
El ajuste para especificar si las capacidades de aprovisionamiento de recursos están habilitadas. Para deshabilitar el aprovisionamiento de recursos, establezca este parámetro en `FALSE`. El valor predeterminado es `TRUE`.

|===


== Unidades y grupos de volúmenes

Un grupo de volúmenes es un conjunto de unidades agrupadas lógicamente por las controladoras de la cabina de almacenamiento. La cantidad de unidades de un grupo de volúmenes se limita según el nivel de RAID y el firmware de la controladora. Al crear un grupo de volúmenes, se deben seguir estas directrices:

* A partir de la versión de firmware 7.10, es posible crear un grupo de volúmenes vacío y reservar la capacidad para un uso posterior.
* No se pueden mezclar tipos de unidades dentro de un mismo grupo de volúmenes.
* No se pueden mezclar unidades HDD y SSD dentro de un mismo grupo de volúmenes.
* La cantidad máxima de unidades de un grupo de volúmenes depende de las siguientes condiciones:
+
** Tipo de controladora
** Nivel de RAID


* Los niveles de RAID incluyen: 0, 1, 3, 5 y 6 .
+
** Un grupo de volúmenes con nivel de RAID 3, 5 o 6 puede tener hasta 30 unidades.
** Un grupo de volúmenes con nivel de RAID 6 debe tener un mínimo de 5 unidades.
** Si un grupo de volúmenes con nivel de RAID 1 tiene al menos 4 unidades, el software de administración del almacenamiento convierte automáticamente el grupo de volúmenes al nivel de RAID 10, es decir, nivel de RAID 1 + nivel de RAID 0.


* En las siguientes tablas, se presentan criterios adicionales para habilitar la protección contra pérdida de soporte o de cajón:


|===
| Nivel | Criterios para la protección contra pérdida de soporte | Cantidad mínima requerida de bandejas 


 a| 
`Disk Pool`
 a| 
El pool de discos consta de dos unidades como máximo en un solo soporte
 a| 
6



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo soporte
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un soporte aparte
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja RAID 1 se debe ubicar en un soporte aparte
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de soporte.
 a| 
No aplicable

|===
|===
| Nivel | Criterios para la protección contra pérdida de cajón | Cantidad mínima requerida de cajones 


 a| 
`Disk Pool`
 a| 
El pool incluye las unidades de los cinco cajones y existe la misma cantidad de unidades por cajón. Un soporte de 60 unidades puede brindar protección contra pérdida de cajón cuando el pool de discos consta de 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 unidades.
 a| 
5



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo cajón.
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un cajón aparte.
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja reflejada se debe ubicar en un cajón aparte.
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de cajón.
 a| 
No aplicable

|===


== Piezas de repuesto

Con los grupos de volúmenes, una estrategia útil para proteger los datos es asignar las unidades disponibles en la cabina de almacenamiento como unidades de repuesto. Una pieza de repuesto es una unidad que no contiene datos y permanece en espera en la cabina de almacenamiento en caso de que se produzca un error en alguna unidad de un grupo de volúmenes RAID 1, RAID 3, RAID 5 o RAID 6. La pieza de repuesto añade otro nivel de redundancia a la cabina de almacenamiento.

En general, las unidades de repuesto deben tener una capacidad igual o mayor que la capacidad utilizada en las unidades que protegen. Las unidades de repuesto deben ser del mismo tipo de medio, el mismo tipo de interfaz y la misma capacidad que las unidades que protegen.

Si se produce un error en la unidad de la cabina de almacenamiento, la pieza de repuesto normalmente sustituye automáticamente la unidad con el error sin intervención del usuario. Si existe una pieza de repuesto disponible cuando se produce un error en la unidad, la controladora usa la paridad de datos de redundancia para reconstruir los datos en la pieza de repuesto. La compatibilidad con la evacuación de datos también permite copiar los datos en una pieza de repuesto antes de que el software marque la unidad como "con error".

Una vez que se sustituye físicamente la unidad con el error, existen diferentes opciones para restaurar los datos:

Tras la sustitución de la unidad con el error, los datos de la pieza de repuesto se vuelven a copiar en la unidad de reemplazo. Esta acción se denomina "copia posterior".

Si se designa la unidad de repuesto como miembro permanente de un grupo de volúmenes, no se necesita la operación de copia posterior.

La disponibilidad de la protección contra pérdida de soporte y la protección contra pérdida de cajón en un grupo de volúmenes dependen de la ubicación de las unidades que incluye ese grupo de volúmenes. La protección contra pérdida de soporte o cajón puede perderse debido a una unidad con error y a la ubicación de la unidad de repuesto. Para asegurarse de que la protección contra pérdida de soporte y la protección contra pérdida de cajón no se vean afectadas, debe reemplazar una unidad con error para iniciar el proceso de copyback.

La cabina de almacenamiento selecciona automáticamente unidades compatibles con la función Garantía de datos (DA) para brindar cobertura de piezas de repuesto a los volúmenes con la función DA habilitada.

Siempre debe haber unidades compatibles con DA en la cabina de almacenamiento si se desea contar con cobertura de piezas de repuesto para los volúmenes con la función DA habilitada. Para obtener más información sobre las unidades compatibles con DA, consulte la función Garantía de datos.

Las unidades compatibles con la función de seguridad (FIPS y FDE) pueden usarse como piezas de repuesto para unidades compatibles y no compatibles con la función de seguridad. Las unidades no compatibles con la función de seguridad pueden brindar cobertura a otras unidades no compatibles con la función de seguridad y a unidades compatibles con la función de seguridad, siempre que el grupo de volúmenes no tenga habilitada la función de seguridad. Un grupo de volúmenes FIPS solo puede usar una unidad FIPS como pieza de repuesto. Sin embargo, es posible usar una pieza de repuesto FIPS para grupos de volúmenes no compatibles con la función de seguridad, compatibles con la función de seguridad y con la función de seguridad habilitada.

Si no existe una pieza de repuesto, es igualmente posible reemplazar una unidad con error mientras la cabina de almacenamiento está en funcionamiento. Si la unidad forma parte de un grupo de volúmenes RAID 1, RAID 3, RAID 5 o RAID 6, la controladora usa la paridad de datos de redundancia para reconstruir automáticamente los datos en la unidad de reemplazo. Esta acción se denomina "reconstrucción".



== Tamaño de los segmentos

El tamaño de un segmento determina cuántos bloques de datos escribe la controladora en una sola unidad de un volumen antes de pasar a la siguiente unidad. Cada bloque de datos almacena 512 bytes de datos. Un bloque de datos es la unidad mínima de almacenamiento. El tamaño de un segmento determina cuántos bloques de datos contiene. Por ejemplo, un segmento de 8 KB contiene 16 bloques de datos. Un segmento de 64 KB contiene 128 bloques de datos.

Cuando se introduce un valor para el tamaño de segmento, se controla si corresponde a los valores admitidos que indica la controladora en el tiempo de ejecución. Si el valor especificado no es válido, la controladora muestra una lista de valores válidos. Cuando se utiliza una sola unidad para una solicitud única, las demás unidades disponibles pueden atender simultáneamente otras solicitudes. Si el volumen se encuentra en un entorno en el que un único usuario transfiere grandes unidades de datos (como multimedia), el rendimiento se maximiza cuando se atiende una única solicitud de transferencia de datos con una única franja de datos. (Una franja de datos es el tamaño de segmento multiplicado por la cantidad de unidades en el grupo de volúmenes que se usan para la transferencia de datos.) En este caso, se usan varias unidades para la misma solicitud, pero se accede una sola vez a cada unidad.

Para lograr un rendimiento óptimo en un entorno de almacenamiento con base de datos multiusuario o sistema de archivos, se debe configurar un tamaño de segmento que minimice la cantidad de unidades necesarias para satisfacer una solicitud de transferencia de datos.



== Consejo de uso

[NOTE]
====
No es necesario introducir un valor para `cacheReadPrefetch` o el `segmentSize` parámetro. Si no se introduce un valor, el firmware de la controladora utiliza `usageHint` parámetro con `fileSystem` como valor predeterminado. Introducir un valor para `usageHint` parámetro y un valor para `cacheReadPrefetch` o un valor para `segmentSize` el parámetro no provoca un error. El valor que se introduce para `cacheReadPrefetch` o el `segmentSize` el parámetro tiene prioridad sobre el valor de `usageHint` parámetro. En la siguiente tabla, se muestran el tamaño del segmento y la configuración de captura previa de lectura de caché para varios consejos de uso:

====
|===
| Consejo de uso | Configuración de tamaño de segmento | Configuración de captura previa de lectura de caché dinámica 


 a| 
Sistema de archivos
 a| 
128 KB
 a| 
Activado



 a| 
Base de datos
 a| 
128 KB
 a| 
Activado



 a| 
Multimedia
 a| 
256 KB
 a| 
Activado

|===


== Captura previa de lectura de caché

La captura previa de lectura de caché permite que la controladora copie en caché bloques de datos adicionales mientras lee y copia en caché bloques de datos solicitados por el host desde la unidad. Esta acción aumenta las posibilidades de satisfacer una solicitud de datos futura desde la caché. La captura previa de lectura de caché es importante para las aplicaciones multimedia en las que se usa la transferencia de datos secuencial. Valores válidos para `cacheReadPrefetch` los parámetros son `TRUE` o. `FALSE`. El valor predeterminado es `TRUE`.



== Tipo de seguridad

Utilice la `securityType` parámetro para especificar la configuración de seguridad de la cabina de almacenamiento.

Antes de poder ajustar la `securityType` parámetro a. `enabled`, debe crear una clave de seguridad de la cabina de almacenamiento. Utilice la `create storageArray securityKey` comando para crear una clave de seguridad de la cabina de almacenamiento. Los siguientes comandos se relacionan con la clave de seguridad:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Unidades seguras

Las unidades compatibles con la función de seguridad pueden ser unidades de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS). Utilice la `secureDrives` parámetro para especificar el tipo de unidades seguras que se usarán. Los valores que puede utilizar son `fips` y.. `fde`.



== Gestión de garantía de datos

La función Data Assurance (DA) mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite a la cabina de almacenamiento comprobar si se producen errores cuando se transfieren datos entre hosts y unidades. Si esta función está habilitada, la cabina de almacenamiento añade códigos de comprobación de errores (también conocidos como comprobaciones de redundancia cíclicas o CRC) a cada bloque de datos del volumen. Una vez movido un bloque de datos, la cabina de almacenamiento utiliza estos códigos de CRC para determinar si se produjeron errores durante la transmisión. Los datos posiblemente dañados no se escriben en el disco ni se vuelven a transferir al host.

Si desea usar la función DA, comience con un pool o grupo de volúmenes que solo incluya unidades que sean compatibles con DA. A continuación, cree volúmenes compatibles con DA. Por último, asigne estos volúmenes compatibles con DA al host por medio de una interfaz de I/o compatible con DA. Las interfaces de I/o compatibles con DA son Fibre Channel, SAS e Iser over InfiniBand (extensiones iSCSI para RDMA/IB). ISCSI sobre Ethernet o SRP over InfiniBand no admiten LA función DA.

[NOTE]
====
Si todas las unidades son compatibles con DA, es posible configurar la `dataAssurance` parámetro a. `enabled` Y luego usar DA con ciertas operaciones. Por ejemplo, es posible crear un grupo de volúmenes que incluya unidades compatibles con DA y, luego, crear un volumen dentro de ese grupo que tenga la función DA habilitada. Otras operaciones que usan volúmenes con la función DA habilitada tienen opciones para admitir la función DA.

====
Si la `dataAssurance` el parámetro se establece en `enabled`, sólo se considerarán unidades compatibles con garantía de datos para candidatos de volumen; de lo contrario, se considerarán unidades compatibles con garantía de datos o no compatibles con esta función. Si solamente existen unidades con garantía de datos disponibles, se crea el nuevo grupo de volúmenes mediante las unidades compatibles con esa función.



== Nivel de firmware mínimo

7.10

7.50 añade el `securityType` parámetro.

7.60 añade el `drawerID` entrada del usuario, la `driveMediaType` y la `drawerLossProtect` parámetro.

7.75 añade el `dataAssurance` parámetro.

8.63 añade el `resourceProvisioningCapable` parámetro.
