---
permalink: commands-a-z/create-raid-volume-manual-drive-select.html 
sidebar: sidebar 
keywords: create, raid, volume, manual, drive, select 
summary: El comando create volume permite crear un nuevo grupo de volúmenes y un volumen, y especificar las unidades del volumen. 
---
= Crear un volumen RAID (selección manual de unidad) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `create volume` el comando crea un nuevo grupo de volúmenes y volumen, y permite especificar las unidades del volumen.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
create volume drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeName"_]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`drives`
 a| 
Las unidades que se desean asignar al volumen que se va a crear. En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`volumeGroupUserLabel`
 a| 
El nombre que se desea otorgar al nuevo grupo de volúmenes. El nombre del grupo de volúmenes debe escribirse entre comillas dobles (" ").

[NOTE]
====
Si no se especifica una etiqueta de usuario para el grupo de volúmenes, el firmware de la controladora le asigna un número.

====


 a| 
`raidLevel`
 a| 
El nivel de RAID del grupo de volúmenes que contiene el volumen. Los valores válidos son `0`, `1`, `3`, `5`, o. `6`.



 a| 
`userLabel`
 a| 
El nombre que se desea otorgar al nuevo volumen. El nombre del nuevo volumen debe escribirse entre comillas dobles (" ").

[NOTE]
====
Este parámetro es obligatorio.

====


 a| 
`capacity`
 a| 
El tamaño del volumen que se añadirá a la cabina de almacenamiento. El tamaño se define en unidades de `bytes`, `KB`, `MB`, `GB`, o. `TB`.



 a| 
`owner`
 a| 
La controladora propietaria del volumen. Los identificadores válidos de la controladora son los siguientes `a` o. `b`, donde `a` Es la controladora en la ranura A, y. `b` Es la controladora en la ranura B. Si no se especifica un propietario, el firmware de la controladora lo determina.



 a| 
`cacheReadPrefetch`
 a| 
El ajuste para activar o desactivar la captura previa de lectura de caché. Para desactivar la captura previa de lectura de caché, este parámetro debe configurarse en `FALSE`. Para activar la captura previa de lectura de caché, este parámetro debe configurarse en `TRUE`.



 a| 
`segmentSize`
 a| 
La cantidad de datos (en KB) que la controladora escribe en una sola unidad de un volumen antes de escribir datos en la siguiente unidad. Los valores válidos son``4 (SSD only)``/, `16`, `32`, `64`, `128`, `256`, o. `512`.



 a| 
`usageHint`
 a| 
La configuración de ambos `cacheReadPrefetch` y la `segmentSize` parámetro para que sea valores predeterminados. Los valores predeterminados se basan en el patrón de uso de I/o típico de la aplicación que utiliza el volumen. Los valores válidos son `fileSystem`, `dataBase`, o. `multiMedia`.



 a| 
`trayLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de soporte cuando se crea el repositorio. Para aplicar la protección contra pérdida de soporte, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`drawerLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de cajón cuando se crea el volumen de repositorios reflejados. Para aplicar la protección contra pérdida de cajón, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`dssPreAllocate`
 a| 
El ajuste para garantizar que se asigne capacidad de reserva para futuros aumentos de tamaño de los segmentos. El valor predeterminado es `TRUE`.



 a| 
`securityType`
 a| 
El ajuste para especificar el nivel de seguridad cuando se crean los grupos de volúmenes y todos los volúmenes asociados. Los ajustes válidos son los siguientes:

* `none` -- el grupo de volúmenes y los volúmenes no están protegidos.
* `capable` -- el grupo de volúmenes y los volúmenes pueden tener la configuración de seguridad, pero la seguridad no está habilitada.
* `enabled` -- el grupo de volúmenes y los volúmenes tienen la seguridad habilitada.




 a| 
`resourceProvisioningCapable`
 a| 
El ajuste para especificar si las capacidades de aprovisionamiento de recursos están habilitadas. Para deshabilitar el aprovisionamiento de recursos, establezca este parámetro en `FALSE`. El valor predeterminado es `TRUE`.



 a| 
`mapping`
 a| 
Este parámetro permite asignar el volumen a un host. Si se prefiere realizar la asignación más tarde, el parámetro debe configurarse en `none`. Si se prefiere realizar la asignación en el momento, el parámetro debe configurarse en `default`. El volumen se asignará a todos los hosts que tengan acceso al pool de almacenamiento. El valor predeterminado es `none`.



 a| 
`blockSize`
 a| 
Este parámetro configura el tamaño de bloque del volumen que se está creando. Un valor de 0 o el parámetro no configurado utiliza el tamaño de bloque predeterminado.

|===


== Notas

La `drives` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.

Si establece la `raidLevel` Parámetro a nivel de RAID 1:

* Hay una cantidad par de unidades en el grupo, según la definición de RAID 1
* La primera mitad del grupo, en el orden en que se enumeran (y en orden de franja), son unidades primarias
* La segunda mitad del grupo, en el orden en que se enumeran (y en orden de franja), son las unidades de reflejo correspondientes


Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.

La `owner` el parámetro define qué controladora es propietaria del volumen. La propiedad de controladora preferida de un volumen es la controladora a la que actualmente pertenece el grupo de volúmenes.

Si no se especifica una capacidad con el `capacity` se usa toda la capacidad de la unidad disponible en el grupo de volúmenes. Si no se especifican unidades de capacidad, `bytes` se utiliza como valor predeterminado.



== Protección contra pérdida de soporte y protección contra pérdida de cajón

Para que la protección contra pérdida de soporte funcione, la configuración debe cumplir las siguientes directrices:

|===
| Nivel | Criterios para la protección contra pérdida de soporte | Cantidad mínima requerida de bandejas 


 a| 
`Disk Pool`
 a| 
El pool de discos consta de dos unidades como máximo en un solo soporte
 a| 
6



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo soporte
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un soporte aparte
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja RAID 1 se debe ubicar en un soporte aparte
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de soporte.
 a| 
No aplicable

|===
Para que la protección contra pérdida de cajón funcione (en entornos de compartimentos de alta densidad), la configuración debe respetar las siguientes directrices:

|===
| Nivel | Criterios para la protección contra pérdida de cajón | Cantidad mínima requerida de cajones 


 a| 
`Disk Pool`
 a| 
El pool incluye las unidades de los cinco cajones y existe la misma cantidad de unidades por cajón. Un soporte de 60 unidades puede brindar protección contra pérdida de cajón cuando el pool de discos consta de 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 unidades.
 a| 
5



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo cajón.
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un cajón aparte.
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja reflejada se debe ubicar en un cajón aparte.
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de cajón.
 a| 
No aplicable

|===


== Tamaño de los segmentos

El tamaño de un segmento determina cuántos bloques de datos escribe la controladora en una sola unidad de un volumen antes de pasar a la siguiente unidad. Cada bloque de datos almacena 512 bytes de datos. Un bloque de datos es la unidad mínima de almacenamiento. El tamaño de un segmento determina cuántos bloques de datos contiene. Por ejemplo, un segmento de 8 KB contiene 16 bloques de datos. Un segmento de 64 KB contiene 128 bloques de datos.

Cuando se introduce un valor para el tamaño de segmento, se controla si corresponde a los valores admitidos que indica la controladora en el tiempo de ejecución. Si el valor especificado no es válido, la controladora muestra una lista de valores válidos. Cuando se utiliza una sola unidad para una solicitud única, las demás unidades disponibles pueden atender simultáneamente otras solicitudes. Si el volumen se encuentra en un entorno en el que un único usuario transfiere grandes unidades de datos (como multimedia), el rendimiento se maximiza cuando se atiende una única solicitud de transferencia de datos con una única franja de datos. (Una franja de datos es el tamaño de segmento multiplicado por la cantidad de unidades en el grupo de volúmenes que se usan para la transferencia de datos.) En este caso, se usan varias unidades para la misma solicitud, pero se accede una sola vez a cada unidad.

Para lograr un rendimiento óptimo en un entorno de almacenamiento con base de datos multiusuario o sistema de archivos, se debe configurar un tamaño de segmento que minimice la cantidad de unidades necesarias para satisfacer una solicitud de transferencia de datos.



== Consejo de uso

[NOTE]
====
No es necesario introducir un valor para `cacheReadPrefetch` o el `segmentSize` parámetro. Si no se introduce un valor, el firmware de la controladora utiliza `usageHint` parámetro con `fileSystem` como valor predeterminado. Introducir un valor para `usageHint` parámetro y un valor para `cacheReadPrefetch` o un valor para `segmentSize` el parámetro no provoca un error. El valor que se introduce para `cacheReadPrefetch` o el `segmentSize` el parámetro tiene prioridad sobre el valor de `usageHint` parámetro. En la siguiente tabla, se muestran el tamaño del segmento y la configuración de captura previa de lectura de caché para varios consejos de uso:

====
|===
| Consejo de uso | Configuración de tamaño de segmento | Configuración de captura previa de lectura de caché dinámica 


 a| 
Sistema de archivos
 a| 
128 KB
 a| 
Activado



 a| 
Base de datos
 a| 
128 KB
 a| 
Activado



 a| 
Multimedia
 a| 
256 KB
 a| 
Activado

|===


== Captura previa de lectura de caché

La captura previa de lectura de caché permite que la controladora copie en caché bloques de datos adicionales mientras lee y copia en caché bloques de datos solicitados por el host desde la unidad. Esta acción aumenta las posibilidades de satisfacer una solicitud de datos futura desde la caché. La captura previa de lectura de caché es importante para las aplicaciones multimedia en las que se usa la transferencia de datos secuencial. Valores válidos para `cacheReadPrefetch` los parámetros son `TRUE` o. `FALSE`. El valor predeterminado es `TRUE`.

No es necesario introducir un valor para `cacheReadPrefetch` o el `segmentSize` parámetro. Si no se introduce un valor, el firmware de la controladora utiliza `usageHint` parámetro con `fileSystem` como valor predeterminado. Introducir un valor para `usageHint` parámetro y un valor para `cacheReadPrefetch` o un valor para `segmentSize` el parámetro no provoca un error. El valor que se introduce para `cacheReadPrefetch` o el `segmentSize` el parámetro tiene prioridad sobre el valor de `usageHint` parámetro.



== Tipo de seguridad

Utilice la `securityType` parámetro para especificar la configuración de seguridad de la cabina de almacenamiento.

Antes de poder ajustar la `securityType` parámetro a. `enabled`, debe crear una clave de seguridad de la cabina de almacenamiento. Utilice la `create storageArray securityKey` comando para crear una clave de seguridad de la cabina de almacenamiento. Los siguientes comandos se relacionan con la clave de seguridad:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Nivel de firmware mínimo

7.10 añade la funcionalidad para el nivel de RAID 6 y el `dssPreAllocate` parámetro.

7.50 añade el `securityType` parámetro.

7.60 añade la entrada de usuario _drawerID_ y el `drawerLossProtect` parámetro.

7.75 añade el `dataAssurance` parámetro.

8.63 añade el `resourceProvisioningCapable` parámetro.

11.70 añade el `blockSize` parámetro.
