---
permalink: commands-a-z/create-cgsnapimage-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency group, snapshot image 
summary: El comando create cgSnapImage consistencyGroup crea una nueva imagen Snapshot para cada volumen base que forma parte del grupo de coherencia Snapshot. 
---
= Crear una imagen instantánea de un grupo de consistencia - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `create cgSnapImage consistencyGroup` el comando crea una imagen snapshot nueva para cada volumen base que es miembro de un grupo de coherencia snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
create cgSnapImage consistencyGroup=pass:quotes[_"consistencyGroupName"_]
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`consistencyGroup`
 a| 
El nombre del grupo de coherencia para el que se crean las imágenes Snapshot. El nombre del grupo de coherencia debe escribirse entre comillas dobles (" ").

|===


== Notas

En los nombres, se puede usar cualquier combinación de caracteres alfanuméricos, guiones y guiones bajos. Los nombres pueden tener hasta 30 caracteres.

El comando hace que todas las operaciones de I/o pendientes de cada volumen base que forma parte del grupo de coherencia se depuren y se suspendan antes de crear las imágenes Snapshot. Si no es posible finalizar la creación de todas las imágenes Snapshot para todos los miembros del grupo de coherencia, la operación falla y no se crean las nuevas imágenes Snapshot.

Normalmente, todos los miembros de un grupo de coherencia Snapshot tienen la misma cantidad de imágenes Snapshot. Cuando se añade un nuevo miembro a un grupo de coherencia Snapshot, ese nuevo miembro no tiene las imágenes Snapshot que se habían creado previamente en los miembros establecidos del grupo de coherencia Snapshot. Esta situación no es un error. Las solicitudes de eliminación o reversión de imágenes Snapshot que solo existen en un subconjunto de los miembros del grupo de coherencia Snapshot afectan únicamente a los miembros para los cuales existe la imagen Snapshot especificada.



== Nivel de firmware mínimo

7.83
