---
permalink: commands-a-z/create-raid-volume-automatic-drive-select.html 
sidebar: sidebar 
keywords: create, raid, volume, automatic, drive, select 
summary: El comando create volume crea un grupo de volúmenes en las unidades de la cabina de almacenamiento y un nuevo volumen en el grupo de volúmenes. Las controladoras de la cabina de almacenamiento eligen las unidades que se incluirán en el volumen. 
---
= Crear volumen RAID (selección automática de unidad) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `create volume` el comando crea un grupo de volúmenes en las unidades de la cabina de almacenamiento y un nuevo volumen del grupo de volúmenes. Las controladoras de la cabina de almacenamiento eligen las unidades que se incluirán en el volumen.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

[NOTE]
====
Si tiene unidades con distintas capacidades, no puede crear volúmenes automáticamente mediante el valor de `driveCount` parámetro. La creación de volúmenes con unidades de diversas capacidades se explica en link:create-raid-volume-manual-drive-select.html["Crear volumen RAID (selección manual de unidad)"].

====


== Sintaxis

[source, cli, subs="+macros"]
----
create volume driveCount=pass:quotes[_numberOfDrives_]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupUserLabel"_]]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"userLabel"_]
driveMediaType=(HDD | SSD | unknown | allMedia)
[driveType=(SAS | NVMe4K)]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[secureDrives=(fips | fde )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`driveCount`
 a| 
La cantidad de unidades sin asignar que se desea usar en el grupo de volúmenes.



 a| 
`volumeGroupUserLabel`
 a| 
El nombre que se desea otorgar al nuevo grupo de volúmenes. El nombre del nuevo grupo de volúmenes debe escribirse entre comillas dobles (" ").

[NOTE]
====
Si no se especifica una etiqueta de usuario para el grupo de volúmenes, el firmware de la controladora le asigna un número.

====


 a| 
`raidLevel`
 a| 
El nivel de RAID del grupo de volúmenes que contiene el volumen. Los valores válidos son `0`, `1`, `3`, `5`, o. `6`.



 a| 
`userLabel`
 a| 
El nombre que se desea otorgar al nuevo volumen. El nombre del nuevo volumen debe escribirse entre comillas dobles (" ").

[NOTE]
====
Este parámetro es obligatorio.

====


 a| 
`driveMediaType`
 a| 
El tipo de unidad que se desea usar para el grupo de volúmenes. Las unidades válidas son las siguientes:

* `HDD` -- Utilice esta opción cuando tenga unidades de disco duro en la bandeja de unidades
* `SSD` -- esta opción se usa cuando hay unidades de estado sólido en el soporte de unidades
* `unknown` -- use esta opción si no está seguro de qué tipos de unidades hay en el soporte
* `allMedia` -- esta opción se usa cuando se desean utilizar todos los tipos de unidades del soporte




 a| 
`driveType`
 a| 
El tipo de unidad que se desea usar en el volumen. No es posible mezclar tipos de unidad.

Se debe usar este parámetro cuando existe más de un tipo de unidad en la cabina de almacenamiento.

Los tipos de unidades válidos son los siguientes:

* `SAS`
* `NVMe4K`


Si no se especifica un tipo de unidad, la configuración predeterminada del comando es `any type`.



 a| 
`capacity`
 a| 
El tamaño del volumen que se añadirá a la cabina de almacenamiento. El tamaño se define en unidades de `bytes`, `KB`, `MB`, `GB`, o. `TB`.



 a| 
`owner`
 a| 
La controladora propietaria del volumen. Los identificadores válidos de la controladora son los siguientes `a` o. `b`, donde `a` Es la controladora en la ranura A, y. `b` Es la controladora en la ranura B. Si no se especifica un propietario, el firmware de la controladora lo determina.



 a| 
`cacheReadPrefetch`
 a| 
El ajuste para activar o desactivar la captura previa de lectura de caché. Para desactivar la captura previa de lectura de caché, este parámetro debe configurarse en `FALSE`. Para activar la captura previa de lectura de caché, este parámetro debe configurarse en `TRUE`.



 a| 
`segmentSize`
 a| 
La cantidad de datos (en KB) que la controladora escribe en una sola unidad de un volumen antes de escribir datos en la siguiente unidad. Los valores válidos son `8`, `16`, `32`, `64`, `128`, `256`, o. `512`.



 a| 
`usageHint`
 a| 
El ajuste para ambos `cacheReadPrefetch` y la `segmentSize` parámetro para que sea valores predeterminados. Los valores predeterminados se basan en el patrón de uso de I/o típico de la aplicación que utiliza el volumen. Los valores válidos son `fileSystem`, `dataBase`, o. `multiMedia`.



 a| 
`trayLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de soporte cuando se crea el grupo de volúmenes. Para aplicar la protección contra pérdida de soporte, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`drawerLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de cajón cuando se crea el grupo de volúmenes de repositorios de reflejos. Para aplicar la protección contra pérdida de cajón, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`dssPreAllocate`
 a| 
El ajuste para garantizar que se asigne capacidad de reserva para futuros aumentos de tamaño de los segmentos. El valor predeterminado es `TRUE`.



 a| 
`securityType`
 a| 
El ajuste para especificar el nivel de seguridad cuando se crean los grupos de volúmenes y todos los volúmenes asociados. Los ajustes válidos son los siguientes:

* `none` -- el grupo de volúmenes y los volúmenes no están protegidos.
* `capable` -- el grupo de volúmenes y los volúmenes pueden tener la configuración de seguridad, pero la seguridad no está habilitada.
* `enabled` -- el grupo de volúmenes y los volúmenes tienen la seguridad habilitada.




 a| 
`resourceProvisioningCapable`
 a| 
El ajuste para especificar si las capacidades de aprovisionamiento de recursos están habilitadas. Para deshabilitar el aprovisionamiento de recursos, establezca este parámetro en `FALSE`. El valor predeterminado es `TRUE`.



 a| 
`mapping`
 a| 
Este parámetro permite asignar el volumen a un host. Si se prefiere realizar la asignación más tarde, el parámetro debe configurarse en `none`. Si se prefiere realizar la asignación en el momento, el parámetro debe configurarse en `default`. El volumen se asignará a todos los hosts que tengan acceso al pool de almacenamiento. El valor predeterminado es `none`.



 a| 
`blockSize`
 a| 
Este parámetro configura el tamaño de bloque del volumen que se está creando. Un valor de 0 o el parámetro no configurado utiliza el tamaño de bloque predeterminado.

|===


== Notas

En los nombres, se puede usar cualquier combinación de caracteres alfanuméricos, guiones y guiones bajos. Los nombres pueden tener hasta 30 caracteres.

La `driveCount` parámetro permite seleccionar la cantidad de unidades que se desea usar en el grupo de volúmenes. No es necesario especificar las unidades por ID de soporte e ID de ranura. Las controladoras eligen las unidades específicas que se usan en el grupo de volúmenes.

La `owner` el parámetro define qué controladora es propietaria del volumen.

Si no se especifica una capacidad con el `capacity` se usa toda la capacidad de la unidad disponible en el grupo de volúmenes. Si no se especifican unidades de capacidad, `bytes` se utiliza como valor predeterminado.



== Tamaño de los segmentos

El tamaño de un segmento determina cuántos bloques de datos escribe la controladora en una sola unidad de un volumen antes de pasar a la siguiente unidad. Cada bloque de datos almacena 512 bytes de datos. Un bloque de datos es la unidad mínima de almacenamiento. El tamaño de un segmento determina cuántos bloques de datos contiene. Por ejemplo, un segmento de 8 KB contiene 16 bloques de datos. Un segmento de 64 KB contiene 128 bloques de datos.

Cuando se introduce un valor para el tamaño de segmento, se controla si corresponde a los valores admitidos que indica la controladora en el tiempo de ejecución. Si el valor especificado no es válido, la controladora muestra una lista de valores válidos. Cuando se utiliza una sola unidad para una solicitud única, las demás unidades disponibles pueden atender simultáneamente otras solicitudes. Si el volumen se encuentra en un entorno en el que un único usuario transfiere grandes unidades de datos (como multimedia), el rendimiento se maximiza cuando se atiende una única solicitud de transferencia de datos con una única franja de datos. (Una franja de datos es el tamaño de segmento multiplicado por la cantidad de unidades en el grupo de volúmenes que se usan para la transferencia de datos.) En este caso, se usan varias unidades para la misma solicitud, pero se accede una sola vez a cada unidad.

Para lograr un rendimiento óptimo en un entorno de almacenamiento con base de datos multiusuario o sistema de archivos, se debe configurar un tamaño de segmento que minimice la cantidad de unidades necesarias para satisfacer una solicitud de transferencia de datos.



== Consejo de uso

[NOTE]
====
No es necesario introducir un valor para `cacheReadPrefetch` o el `segmentSize` parámetro. Si no se introduce un valor, el firmware de la controladora utiliza `usageHint` parámetro con `fileSystem` como valor predeterminado. Introducir un valor para `usageHint` parámetro y un valor para `cacheReadPrefetch` o un valor para `segmentSize` el parámetro no provoca un error. El valor que se introduce para `cacheReadPrefetch` o el `segmentSize` el parámetro tiene prioridad sobre el valor de `usageHint` parámetro. En la siguiente tabla, se muestran el tamaño del segmento y la configuración de captura previa de lectura de caché para varios consejos de uso:

====
|===
| Consejo de uso | Configuración de tamaño de segmento | Configuración de captura previa de lectura de caché dinámica 


 a| 
Sistema de archivos
 a| 
128 KB
 a| 
Activado



 a| 
Base de datos
 a| 
128 KB
 a| 
Activado



 a| 
Multimedia
 a| 
256 KB
 a| 
Activado

|===


== Captura previa de lectura de caché

La captura previa de lectura de caché permite que la controladora copie en caché bloques de datos adicionales mientras lee y copia en caché bloques de datos solicitados por el host desde la unidad. Esta acción aumenta las posibilidades de satisfacer una solicitud de datos futura desde la caché. La captura previa de lectura de caché es importante para las aplicaciones multimedia en las que se usa la transferencia de datos secuencial. Valores válidos para `cacheReadPrefetch` los parámetros son `TRUE` o. `FALSE`. El valor predeterminado es `TRUE`.



== Tipo de seguridad

Utilice la `securityType` parámetro para especificar la configuración de seguridad de la cabina de almacenamiento.

Antes de poder ajustar la `securityType` parámetro a. `enabled`, debe crear una clave de seguridad de la cabina de almacenamiento. Utilice la `create storageArray securityKey` comando para crear una clave de seguridad de la cabina de almacenamiento. Los siguientes comandos se relacionan con la clave de seguridad:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Unidades seguras

Las unidades compatibles con la función de seguridad pueden ser unidades de cifrado de disco completo (FDE) o de estándar de procesamiento de información federal (FIPS). Utilice la `secureDrives` parámetro para especificar el tipo de unidades seguras que se usarán. Los valores que puede utilizar son `fips` y.. `fde`.



== Protección contra pérdida de soporte y protección contra pérdida de cajón

En las siguientes tablas, se presentan criterios adicionales para habilitar la protección contra pérdida de soporte o de cajón:

|===
| Nivel | Criterios para la protección contra pérdida de soporte | Cantidad mínima requerida de bandejas 


 a| 
`Disk Pool`
 a| 
El pool de discos consta de dos unidades como máximo en un solo soporte
 a| 
6



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo soporte
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un soporte aparte
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja RAID 1 se debe ubicar en un soporte aparte
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de soporte.
 a| 
No aplicable

|===
|===
| Nivel | Criterios para la protección contra pérdida de cajón | Cantidad mínima requerida de cajones 


 a| 
`Disk Pool`
 a| 
El pool incluye las unidades de los cinco cajones y existe la misma cantidad de unidades por cajón. Un soporte de 60 unidades puede brindar protección contra pérdida de cajón cuando el pool de discos consta de 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 unidades.
 a| 
5



 a| 
`RAID 6`
 a| 
El grupo de volúmenes consta de dos unidades como máximo en un solo cajón.
 a| 
3



 a| 
`RAID 3` o. `RAID 5`
 a| 
Cada unidad del grupo de volúmenes se encuentra en un cajón aparte.
 a| 
3



 a| 
`RAID 1`
 a| 
Cada unidad de una pareja reflejada se debe ubicar en un cajón aparte.
 a| 
2



 a| 
`RAID 0`
 a| 
No puede contar con protección contra pérdida de cajón.
 a| 
No aplicable

|===


== Comando de ejemplo

[listing]
----
create volume driveCount=2 volumeGroupUserLabel="FIPS_VG" raidLevel=1 userLabel="FIPS_V"
----
[listing]
----
driveMediaType=HDD securityType=capable secureDrives=fips
----


== Nivel de firmware mínimo

7.10 añade la funcionalidad para el nivel de RAID 6 y el `dssPreAllocate` parámetro.

7.50 añade el `securityType` parámetro.

7.60 añade el `drawerLossProtect` parámetro.

7.75 añade el `dataAssurance` parámetro.

8.25 añade el `secureDrives` parámetro.

8.63 añade el `resourceProvisioningCapable` parámetro.

11.70 añade el `blockSize` parámetro.
