---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: El comando Deactivate storageArray feature desactiva la función Asynchronous Mirroring. 
---
= Desactivar las operaciones de mirroring asíncrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `deactivate storageArray feature` Desactiva la función Asynchronous Mirroring.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800 y E5700, Siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800 o E5700, se deben poseer los roles Storage Admin.



== Contexto

Para poder desactivar la función Asynchronous Mirroring, es necesario eliminar todos los grupos de reflejos asíncronos o las parejas reflejadas asíncronas existentes de la cabina de almacenamiento local y de la cabina de almacenamiento remota.



== Sintaxis

[listing]
----
deactivate storageArray feature=asyncRemoteMirror
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

7.84
