---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: El comando Deactivate storageArray feature desactiva la función Asynchronous Mirroring. 
---
= Desactivar la duplicación asincrónica - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `deactivate storageArray feature` Desactiva la función Asynchronous Mirroring.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Para poder desactivar la función Asynchronous Mirroring, es necesario eliminar todos los grupos de reflejos asíncronos o las parejas reflejadas asíncronas existentes de la cabina de almacenamiento local y de la cabina de almacenamiento remota.



== Sintaxis

[source, cli]
----
deactivate storageArray feature=asyncRemoteMirror
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

7.84
