---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: El comando delete ssdCache elimina la caché SSD. Se depuran todos los datos de la caché SSD. 
---
= Elimine la caché SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `delete ssdCache` El comando elimina la caché SSD. Se depuran todos los datos de la caché SSD.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de soporte.



== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
El nombre de la caché SSD que se desea eliminar. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD incluye caracteres especiales o está compuesto solo de números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
