---
permalink: commands-a-z/delete-iscsiinitiator.html 
sidebar: sidebar 
keywords: delete, initiator, command, specific, object, supported, array, role 
summary: El comando delete iscsiInitiator elimina un objeto iniciador de iSCSI específico. 
---
= Eliminar iniciador iSCSI - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete iscsiInitiator` El comando elimina un objeto iniciador iSCSI específico.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.

[IMPORTANT]
====
Este comando quedó obsoleto y fue sustituido por el xref:delete-initiator.adoc[Elimine el iniciador] comando.

====


[[syntax]]
== Sintaxis

[source, cli]
----
delete iscsiInitiator (<"iscsiID"> | ["name"])
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`iscsiInitiator`
 a| 
El identificador del iniciador de iSCSI que se desea eliminar. El identificador del iniciador de iSCSI puede ser un ID de iSCSI o un nombre exclusivo.

Este ID de iSCSI debe escribirse entre comillas dobles (" ") dentro de paréntesis angulares (< >).

El nombre debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.10

8.41 este comando quedó obsoleto.
