---
permalink: commands-a-z/delete-emailalert.html 
sidebar: sidebar 
keywords: delete, email, alert, recipient 
summary: El comando delete emailAlert elimina direcciones de destinatarios de la configuración de alertas de correo electrónico. 
---
= Eliminar destinatario de alerta de correo electrónico - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete emailAlert` El comando elimina las direcciones de correo electrónico de destinatarios de la configuración de alertas de correo electrónico.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
delete emailAlert
       (allEmailRecipients |
        emailRecipients pass:quotes[[_emailAddress1 ... emailAddressN_]])
----


[[parameters]]
== Parámetros

|===
| Parámetro | Descripción 


 a| 
`allEmailRecipients`
 a| 
Permite eliminar todos los destinatarios de correo electrónico.



 a| 
`emailRecipients`
 a| 
Permite eliminar direcciones de destinatarios específicas. Las direcciones de correo electrónico deben escribirse entre corchetes ([ ]).

|===


[[examples]]
== Ejemplos

[listing]
----

SMcli -n Array1 -c "delete emailAlert allEmailRecipients;"

SMcli -n Array1 -c "delete emailAlert emailRecipients ["person1@email.domain.com" "person3@email.domain.com"];"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40
