---
permalink: commands-a-z/delete-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, key, management, certificate, command, remove, install, external 
summary: El comando delete storageArray keyManagementCertificate quita el certificado de gestión de claves externas instalado en la cabina de almacenamiento. 
---
= Eliminar el certificado de administración de claves externo instalado - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete storageArray keyManagementCertificate` el comando quita el certificado de gestión de claves externas instalado de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



== Contexto

[NOTE]
====
Este comando se aplica solo a la gestión de claves externas.

====


== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[delete storageArray keyManagementCertificate certificateType=_certificate_type_]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`certificateType`
 a| 
Permite especificar el tipo de certificado que se quitará. Las opciones válidas son: `client` o. `server`.

|===


== Ejemplo

[listing]
----
 SMcli -n Array1 -c "delete storageArray keyManagementCertificate certificateType="client";"

   SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40
