---
permalink: commands-a-z/delete-sgsnapvolume.html 
sidebar: sidebar 
keywords: delte, snapvolume, command, snapshot, consistency, group, optionally, repository, members 
summary: El comando delete sgSnapVolume elimina el volumen Snapshot de un grupo de coherencia. Opcionalmente, también es posible eliminar los miembros de repositorio. 
---
= Elimine el volumen Snapshot de grupo de coherencia
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `delete sgSnapVolume` el comando elimina el volumen snapshot de un grupo de coherencia. Opcionalmente, también es posible eliminar los miembros de repositorio.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[delete cgSnapVolume ["_snapVolumeName_"]]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`cgSnapVolume`
 a| 
El nombre del volumen Snapshot de grupo de coherencia que se desea eliminar. El nombre del volumen Snapshot de grupo de coherencia debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`deleteRepositoryMembers`
 a| 
El parámetro para guardar o eliminar los volúmenes miembro. Para guardar los volúmenes miembro, este parámetro debe configurarse en `TRUE`. Para eliminar los volúmenes miembro, este parámetro debe configurarse en `FALSE`. El valor predeterminado es `TRUE`.

|===


== Nivel de firmware mínimo

7.83
