---
permalink: commands-a-z/delete-initiator.html 
sidebar: sidebar 
keywords: delete, initiator, command, object, supported, array, role 
summary: El comando delete initiator elimina el objeto iniciador. 
---
= Eliminar iniciador - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete initiator` comando elimina el objeto iniciador.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

[IMPORTANT]
====
Este comando reemplaza a la obsoleto xref:delete-iscsiinitiator.adoc[Elimine el iniciador de iSCSI] comando.

====
[NOTE]
====
Este comando se aplica únicamente a iSCSI, Iser, NVMe over roce, NVMe over InfiniBand y NVMe over Fibre Channel.

====


== Sintaxis

[source, cli]
----
delete initiator (["initiatorName"] | <"initiatorQualifiedName">)
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`initiator`
 a| 
Permite especificar el identificador del iniciador que se desea eliminar. El nombre debe escribirse entre comillas dobles ("' "'). También se debe escribir entre corchetes ([ ]) si el valor es una etiqueta de usuario o entre paréntesis angulares (< >) si el valor es un nombre completo (por ejemplo, IQN o nqn).

|===


== Nivel de firmware mínimo

8.41
