---
permalink: commands-a-z/delete-auditlog.html 
sidebar: sidebar 
keywords: delete, audit, log, records 
summary: El comando delete auditlog elimina algunas o todas las entradas del registro de auditoría. 
---
= Eliminar registros de auditoría - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete auditLog` el comando elimina algunos o todos los registros de auditoría.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
delete auditLog (all | (endRecord=pass:quotes[_timestamp_ | endDate=_date_) |
 (retentionCount=_integer_))]
----


[[parameters]]
== Parámetros

|===
| Parámetro | Descripción 


 a| 
`all`
 a| 
Permite eliminar todas las entradas del registro de auditoría.



 a| 
`endRecord`
 a| 
Permite especificar la última entrada que se desea eliminar, comenzando por la más antigua. El valor es el valor entero que representa la Marca de hora de la última entrada del registro de auditoría, inclusive.



 a| 
`endDate`
 a| 
Permite especificar la última fecha que se desea eliminar, comenzando por la entrada más antigua. El formato para introducir la fecha es MM:DD:AA en la zona horaria del cliente.

[NOTE]
====
Se eliminarán las entradas del registro de auditoría, incluida la fecha especificada.

====


 a| 
`retentionCount`
 a| 
Permite especificar la cantidad de entradas más recientes del registro de auditoría que se desea conservar.

|===


[[examples]]
== Ejemplos

[listing]
----

SMcli -n Array1 -c "delete auditLog all;"

SMcli -n Array1 -c "delete auditLog endRecord=1493070393313;"

SMcli -n Array1 -c "delete auditLog endDate=04:30:17;"

SMcli -n Array1 -c "delete auditLog retentionCount=1000;"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40
