---
permalink: commands-a-z/delete-storagearray-directoryservers.html 
sidebar: sidebar 
keywords: delete, storage, array, directory, servers, command, allow, directory, role 
summary: El comando delete storageArray directoryServers permite eliminar un servidor de directorio o varios. 
---
= Eliminar servidor de directorio de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete storageArray directoryServers` comando permite eliminar uno o varios servidores de directorio.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[delete storageArray (allDirectoryServers |
 directoryServers ["_domainId1_" ... "_domainIdN_"])
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allDirectoryServers`
 a| 
Permite eliminar todos los servidores de directorio.



 a| 
`directoryServers`
 a| 
Permite especificar un servidor de directorio o varios para eliminar, identificados por el ID de dominio.

[NOTE]
====
Los ID deben escribirse entre corchetes ([ ]). Si hay más de uno, deben escribirse separados por un espacio.

====
|===


== Ejemplos

[listing]
----

SMcli -n Array1 -c "delete storageArray directoryServers ["domain1" "domain3"];"

SMcli -n Array1 -c "delete storageArray allDirectoryServers;"

SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40 añade el comando.
