---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: El comando delete ssdCache elimina la caché SSD. Se depuran todos los datos de la caché SSD. 
---
= Eliminar caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete ssdCache` El comando elimina la caché SSD. Se depuran todos los datos de la caché SSD.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Support Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
El nombre de la caché SSD que se desea eliminar. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD incluye caracteres especiales o está compuesto solo de números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
