---
permalink: commands-a-z/delete-hostgroup.html 
sidebar: sidebar 
keywords: delete, hostgroup, command, support, role 
summary: El comando delete hostGroup elimina un grupo de hosts. 
---
= Eliminar grupo de hosts - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `delete hostGroup` el comando elimina un grupo de hosts.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

[NOTE]
====
*Posible daño en la configuración de la matriz de almacenamiento* -- este comando elimina todas las definiciones de host del grupo de hosts.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[delete hostGroup [_hostGroupName_]]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`hostGroup`
 a| 
El nombre del grupo de hosts que se desea eliminar. El nombre del grupo de hosts debe escribirse entre corchetes ([ ]). Si el nombre del grupo de hosts contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


[[notes]]
== Notas

Un grupo de hosts es un elemento topológico opcional para representar una recogida de hosts que comparten el acceso a los mismos volúmenes. El grupo de hosts es una entidad lógica.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

5.20
