---
permalink: commands-a-z/disable-storagearray-externalkeymanagement-file.html 
sidebar: sidebar 
keywords: disable, storage, array, external, management, file, command, disable, security, key, full, disk, encryption, drives 
summary: El comando disable storageArray externalKeyManagement file deshabilita la gestión de claves de seguridad externas para una cabina de almacenamiento que contiene unidades de cifrado de disco completo. 
---
= Deshabilitar la administración de claves de seguridad externas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `disable storageArray externalKeyManagement file` El comando deshabilita la gestión de claves de seguridad externas para una cabina de almacenamiento que tiene unidades de cifrado de disco completo.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
disable storageArray externalKeyManagement
pass:quotes[file="_fileName_"]
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[saveFile=(_TRUE_ | _FALSE_)]
----


[[context]]
== Contexto

[NOTE]
====
Este comando habilita la gestión de claves internas como forma alternativa de seguridad de unidades.

====
[NOTE]
====
Este comando se aplica solo a la gestión de claves externas.

====


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se debe almacenar el archivo de claves de seguridad internas. Por ejemplo:

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[IMPORTANT]
====
El nombre de archivo debe tener la extensión de `.slk`.

====


 a| 
`passPhrase`
 a| 
Una cadena de caracteres que cifra la clave de seguridad para poder almacenarla en un archivo externo.



 a| 
`saveFile`
 a| 
Verifica y guarda la clave de seguridad en un archivo. Establezca en `FALSE` no guardar y verificar la clave de seguridad en un archivo. El valor predeterminado es `TRUE`.

|===


[[notes]]
== Notas

La frase de contraseña debe cumplir los siguientes criterios:

* Debe tener entre 8 y 32 caracteres.
* Sin espacios en blanco.
* Debe incluir al menos una letra mayúscula.
* Debe incluir al menos una letra minúscula.
* Debe incluir al menos un número.
* Debe incluir al menos un carácter alfanumérico, por ejemplo, < > @ +.


[NOTE]
====
Si la frase de contraseña no cumple estos criterios, se muestra un mensaje de error.

====


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40

8.70 añade el `saveFile` parámetro.
