---
permalink: commands-a-z/download-tray-configurationsettings.html 
sidebar: sidebar 
keywords: download, tray, configuration, settings, commands, factory, default, drive, array, specific, storage, roles, support 
summary: El comando download tray configurationSettings descarga la configuración predeterminada de fábrica en todos los soportes de unidades de la cabina de almacenamiento o en un soporte específico de la cabina de almacenamiento. 
---
= Descargar configuración de la bandeja - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `download tray configurationSettings` el comando descarga la configuración predeterminada de fábrica en todos los soportes de unidades de la cabina de almacenamiento o en un soporte específico de las unidades de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[download (allTrays | tray [_trayID_]] configurationSettings
pass:quotes[file="_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allTrays`
 a| 
Este parámetro descarga el nuevo firmware en todos los soportes de la cabina de almacenamiento.



 a| 
`tray`
 a| 
El soporte de unidades que contiene la tarjeta ESM donde se desea cargar el nuevo firmware. Los valores de ID de soporte son `0` para `99`. El valor de ID de soporte debe escribirse entre corchetes ([ ]).



 a| 
`file`
 a| 
La ruta y el nombre del archivo que contiene la imagen de firmware. La ruta y el nombre del archivo de la imagen de firmware deben escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\dnld\trayset.dlp"`

Los nombres de archivo válidos tienen un `.dlp` extensión.

|===


== Notas

La `tray` el parámetro descarga la configuración predeterminada de fábrica en un soporte de unidades específico Si se necesita descargar la configuración predeterminada de fábrica en varios soportes de unidades, pero no en todos, se debe introducir este comando para cada soporte de unidades



== Nivel de firmware mínimo

7.75
