---
permalink: commands-a-z/download-storagearray-nvsram.html 
sidebar: sidebar 
keywords: download, storagearray, down, values, controller, support, role, command, array 
summary: El comando download storageArray NVSRAM descarga los valores de NVSRAM para la controladora de la cabina de almacenamiento. 
---
= Descargar matriz de almacenamiento NVSRAM - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `download storageArray NVSRAM` El comando descarga los valores de NVSRAM para la controladora de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[download storageArray NVSRAM file="_filename_"]
[healthCheckMelOverride=(TRUE | FALSE)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo que contiene los valores de NVSRAM. El nombre del archivo de NVSRAM debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\dnld\afrm.dlp"`

Los nombres de archivo válidos tienen un `.dlp` extensión.



 a| 
`healthCheckMelOverride`
 a| 
El ajuste para anular los resultados de la comprobación de estado del registro de eventos serios (MEL). La validación DE MEL se ejecuta de todos modos, no se omite. Si se produce un error en la comprobación de MEL, es posible omitir el error mediante el uso de este parámetro cuando se ejecuta el comando.

Antes de cualquier descarga, la controladora comprueba el registro de eventos para determinar si se produjo algún evento que pudiera impedir la correcta descarga de la nueva memoria NVSRAM. Si se produjo algún evento de este tipo, la controladora normalmente no descarga la nueva NVSRAM.

El parámetro fuerza a la controladora a descargar la nueva NVSRAM. El valor predeterminado es `FALSE`. Establezca este valor en `TRUE` Si desea forzar la controladora a descargar la nueva NVSRAM.

|===


== Nivel de firmware mínimo

6.10

8.10 añade el `healthCheckMelOverride` parámetro.
