---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: El comando download drive firmware descarga una imagen de firmware en una unidad. 
---
= Descargue el firmware de la unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `download drive firmware` el comando descarga una imagen de firmware en una unidad.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Contexto

[CAUTION]
====
*Posible daño en la configuración de la matriz de almacenamiento* -- la descarga incorrecta del firmware de la unidad puede provocar daños en las unidades o la pérdida del acceso a los datos.

====
[NOTE]
====
La `content` el parámetro quedó obsoleto. Utilice la `firmware` ahora mismo parámetro.

====
Este comando permite descargar una imagen de firmware en un solo modelo de unidad por vez. Si se usa este comando en un script, se debe utilizar el comando una sola vez. Si se usa este comando más de una vez, se puede producir un error en la operación. Es posible descargar imágenes de firmware en todas las unidades de una cabina de almacenamiento a la vez mediante el `download storageArray driveFirmware` comando.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[download (drive \[_trayID_,[_drawerID,_]pass:quotes[_slotID_] \| drives\ pass:quotes[[_trayID1_,[_drawerID1_,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
 [online|offline] firmware file="filename"
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`drive` o. `drives`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`online` o. `offline`
 a| 
Seleccione `online` para realizar una descarga de firmware de la unidad en línea, si no se selecciona `offline`. El valor predeterminado es `offline`.



 a| 
`file`
 a| 
La ruta y el nombre del archivo que contiene la imagen de firmware. La ruta y el nombre del archivo de la imagen de firmware deben escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\dnld\drvfrm.dlp"`

Los nombres de archivo válidos tienen un `.dlp` extensión.



 a| 
`firmware`
 a| 
Indica que se debe descargar el firmware de la controladora.

|===


== Notas

Antes de intentar descargar el firmware de unidad, se deben tomar las siguientes precauciones:

* A menos que esté utilizando la `online` Parámetro, detenga toda la actividad de I/o de la cabina de almacenamiento antes de descargar la imagen de firmware. La `download drive firmware` comando sin el `online` El parámetro bloquea toda la actividad de I/o hasta que se completa la descarga o se produce un error; no obstante, como precaución, es conveniente verificar que se haya detenido toda la actividad de I/o que pudiera afectar la unidad.
* Se debe confirmar que el archivo de imagen de firmware sea compatible con el soporte de unidades Si se descarga un archivo de imagen de firmware que no es compatible con el soporte de unidades seleccionado, el soporte puede quedar inutilizable.
* No se debe modificar la configuración de la cabina de almacenamiento mientras se descarga el firmware de unidad. Intentar modificar la configuración puede provocar un error en la descarga del firmware y dejar las unidades seleccionadas en un estado inutilizable.
* Para las solicitudes de actualización de firmware de unidad en línea emitidas con este comando, la controladora quita las unidades del grupo de volúmenes de RAID 0 de la lista de unidades donde se descarga el nuevo firmware. El estado de devolución de la unidad individual se configurará en `Never Attempted With Reason`.


Cuando se descarga el firmware en las unidades, se deben especificar la ruta completa y el nombre de archivo para la imagen de firmware que se almacena en el sistema.

Puede utilizar `download drive` el comando para probar el firmware en una unidad antes de instalarlo en todas las unidades de una cabina de almacenamiento. La descarga devuelve uno de los siguientes Estados:

* Exitoso
* No se ha podido establecer la razón
* Nunca se intentó con razón


La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.



== Nivel de firmware mínimo

7.60 añade el `drawerID` entrada del usuario.

8.25 añade el `online` parámetro.
