---
permalink: commands-a-z/enable-controller-datatransfer.html 
sidebar: sidebar 
keywords: enable, controller, datatransfer, command, revive, quiesced, running, diagnostics, role, syntax, parameter, firmware level 
summary: El comando enable Controller dataTransfer reactiva una controladora que se colocó en modo inactivo durante la ejecución de diagnósticos. 
---
= Habilitar la transferencia de datos del controlador - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `enable controller dataTransfer` el comando reactiva una controladora que se colocó en modo inactivo durante la ejecución de diagnósticos.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli]
----
enable controller [(a|b)] dataTransfer
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`controller`
 a| 
La controladora que se desea reactivar. Los identificadores válidos de la controladora son los siguientes `a` o. `b`, donde `a` Es la controladora en la ranura A, y. `b` Es la controladora en la ranura B. El identificador de la controladora debe escribirse entre corchetes ([ ]). Si no se especifica una controladora, el software de administración del almacenamiento devuelve un error de sintaxis.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
