---
permalink: commands-a-z/recreate-storagearray-mirrorrepository.html 
sidebar: sidebar 
keywords: recreate, synchronous, mirror, repository, volume 
summary: 'El comando recreate storageArray mirrorRepository crea un nuevo volumen de repositorios de mirroring síncrono (también llamado volumen de repositorios de reflejos) mediante parámetros definidos para un volumen de repositorios de reflejos anterior.' 
---
= Volver a crear volumen de repositorios de mirroring síncrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `recreate storageArray mirrorRepository` El comando crea un nuevo volumen de repositorios de mirroring síncrono (también denominado volumen de repositorios de reflejos) mediante los parámetros definidos para un volumen de repositorios de reflejos anterior.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800 y E5700, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800 o E5700, debe contar con el rol de administrador de almacenamiento.



== Contexto

[NOTE]
====
Con la versión de firmware 7.80, el `recreate storageArray mirrorRepository` el comando queda obsoleto. Este comando ya no es compatible con la interfaz gráfica de usuario ni con la interfaz de línea de comandos. Si se intenta ejecutar este comando, se muestra un mensaje de error que indica que esta funcionalidad ya no es compatible y que no se realizarán cambios en los repositorios de reflejos remotos especificados.

====
El requisito subyacente es haber creado previamente un volumen de repositorios de reflejos. Cuando se utiliza este comando, se puede definir el volumen de repositorios de reflejos mediante una de tres maneras: Unidades definidas por el usuario, grupo de volúmenes definido por el usuario o cantidad de unidades definida por el usuario para el volumen de repositorios de reflejos. Si se opta por definir una cantidad de unidades, el firmware de la controladora elige las unidades que se utilizarán para el volumen de repositorios de reflejos.



== Sintaxis (unidades definidas por el usuario)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_,pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1
... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN_])
[trayLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Sintaxis (grupo de volúmenes definido por el usuario)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryVolumeGroup=pass:quotes[_volumeGroupName_
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== Sintaxis (cantidad de unidades definida por el usuario)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
(
  [driveMediaType=(HDD | SSD | unknown | allMedia)] |
  [driveType=(SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel="userLabel"] |
[trayLossProtect=(TRUE | FALSE)] |
[drawerLossProtect=(true|false)] |
[dataAssurance=(none | enabled)]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`repositoryRAIDLevel`
 a| 
Nivel de RAID para el volumen de repositorios de reflejos. Los valores válidos son `1`, `3`, `5`, o. `6`.



 a| 
`repositoryDrives`
 a| 
Unidades que se desean usar para el volumen de repositorios de reflejos. Los valores de ID de cajón son `1` para `5`. Los valores de ID de ranura son `1` para `24`. Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]). Para introducir los nombres de los volúmenes de repositorios, se deben respetar las siguientes reglas:

En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

* Todos los valores de ID de soporte, ID de cajón e ID de ranura se deben escribir entre corchetes ([ ]).
* Los valores de ID de soporte, ID de cajón e ID de ranura se deben separar con comas.
* Separe cada una de las posiciones de conducción con un espacio.




 a| 
`repositoryVolumeGroup`
 a| 
Nombre del grupo de volúmenes donde se encuentra el volumen de repositorios de reflejos.



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
El nombre que se desea otorgar al nuevo grupo de volúmenes donde se ubicará el volumen de repositorios de reflejos. El nombre del grupo de volúmenes debe escribirse entre comillas dobles (" ").



 a| 
`freeCapacityArea`
 a| 
Número de índice del espacio libre en un grupo de volúmenes existente que se desea usar para recrear el volumen de repositorios de reflejos. La capacidad libre es la capacidad libre en los volúmenes existentes de un grupo de volúmenes. Por ejemplo, un grupo de volúmenes puede incluir las siguientes áreas: Volumen 1, capacidad libre, volumen 2, capacidad libre, volumen 3, capacidad libre. Para usar la capacidad libre seguida del volumen 2, se debe especificar lo siguiente:

[listing]
----
freeCapacityArea=2
----
Ejecute el `show volumeGroup` comando para determinar si existe un área de capacidad libre.



 a| 
`repositoryDriveCount`
 a| 
Cantidad de unidades sin asignar que se desean usar para el volumen de repositorios de reflejos.



 a| 
`driveMediaType`
 a| 
El tipo de medio de la unidad acerca de la cual se desea recuperar información. Los siguientes valores son tipos válidos de medios de unidades:

* `HDD` indica que dispone de unidades de disco duro en el soporte de la unidad
* `SSD` indica que dispone de discos de estado sólido en el soporte de la unidad
* `unknown` indica que no está seguro del tipo de medios de unidad que hay en el soporte de la unidad
* `allMedia` indica que dispone de todos los tipos de medios en el soporte de la unidad




 a| 
`driveType`
 a| 
Tipo de unidad que se desea usar para el volumen de repositorios de reflejos. No es posible mezclar tipos de unidad.

Se debe usar este parámetro cuando existe más de un tipo de unidad en la cabina de almacenamiento.

Los tipos de unidades válidos son los siguientes:

* `SAS`
* `NVMe4K`


Si no se especifica un tipo de unidad, los valores predeterminados del comando son any type.



 a| 
`trayLossProtect`
 a| 
Configuración para aplicar la protección contra pérdida de soporte cuando se crea el volumen de repositorios de reflejos. Para aplicar la protección contra pérdida de soporte, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.



 a| 
`drawerLossProtect`
 a| 
El ajuste para aplicar la protección contra pérdida de cajón cuando se crea el volumen de repositorios de reflejos. Para aplicar la protección contra pérdida de cajón, se debe establecer este parámetro en `TRUE`. El valor predeterminado es `FALSE`.

|===


== Notas

Si se introduce un valor de espacio de almacenamiento del volumen de repositorios de reflejos demasiado pequeño, el firmware de la controladora devuelve un mensaje de error que indica la cantidad de espacio necesario para el volumen de repositorios de reflejos. El comando no intenta cambiar el volumen de repositorios de reflejos. Se puede volver a introducir el comando con el valor indicado en el mensaje de error para el espacio de almacenamiento del volumen de repositorios de reflejos.

La `repositoryDrives` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.

Cuando se asignan las unidades, si se configuran las `trayLossProtect` parámetro a. `TRUE` y seleccionó más de una unidad de cualquier soporte, la cabina de almacenamiento muestra un error. Si establece la `trayLossProtect` parámetro a. `FALSE`, la matriz de almacenamiento realiza operaciones, pero es posible que el volumen de repositorios de reflejos que se crea no tenga protección contra pérdida de bandeja.

Cuando el firmware de la controladora asigna las unidades, si se configuran las `trayLossProtect` parámetro a. `TRUE`, la cabina de almacenamiento devuelve un error si el firmware de la controladora no puede proporcionar unidades que provoquen que el nuevo volumen de repositorios de reflejos tenga protección contra pérdida de soporte. Si establece la `trayLossProtect` parámetro a. `FALSE`, la matriz de almacenamiento realiza la operación aunque esto implique que el volumen del repositorio de reflejo no tenga protección contra pérdida de bandeja.



== Gestión de garantía de datos

La función Data Assurance (DA) mejora la integridad de los datos en todo el sistema de almacenamiento. DA permite a la cabina de almacenamiento comprobar si se producen errores cuando se transfieren datos entre hosts y unidades. Si esta función está habilitada, la cabina de almacenamiento añade códigos de comprobación de errores (también conocidos como comprobaciones de redundancia cíclicas o CRC) a cada bloque de datos del volumen. Una vez movido un bloque de datos, la cabina de almacenamiento utiliza estos códigos de CRC para determinar si se produjeron errores durante la transmisión. Los datos posiblemente dañados no se escriben en el disco ni se vuelven a transferir al host.

Si desea usar la función DA, comience con un pool o grupo de volúmenes que solo incluya unidades que sean compatibles con DA. A continuación, cree volúmenes compatibles con DA. Por último, asigne estos volúmenes compatibles con DA al host por medio de una interfaz de I/o compatible con DA. Las interfaces de I/o compatibles con DA son Fibre Channel, SAS e Iser over InfiniBand (extensiones iSCSI para RDMA/IB). ISCSI sobre Ethernet o SRP over InfiniBand no admiten LA función DA.

[NOTE]
====
Si todas las unidades son compatibles con DA, es posible configurar la `dataAssurance` parámetro a. `enabled` Y luego usar DA con ciertas operaciones. Por ejemplo, es posible crear un grupo de volúmenes que incluya unidades compatibles con DA y, luego, crear un volumen dentro de ese grupo que tenga la función DA habilitada. Otras operaciones que usan volúmenes con la función DA habilitada tienen opciones para admitir la función DA.

====
Si la `dataAssurance` el parámetro se establece en `enabled`, sólo se considerarán unidades compatibles con garantía de datos para candidatos de volumen; de lo contrario, se considerarán unidades compatibles con garantía de datos o no compatibles con esta función. Si solamente existen unidades con garantía de datos disponibles, se crea el nuevo grupo de volúmenes mediante las unidades compatibles con esa función.



== Nivel de firmware mínimo

6.10

7.10 añade la funcionalidad para el nivel de RAID 6

7.75 añade el `dataAssurance` parámetro.

8.60 añade el `driveMediaType`, `repositoryVolumeGroupUserLabel`, y. `drawerLossProtect` parámetros.
