---
permalink: commands-a-z/remove-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, incomplete, asynchronous, mirror, pair, group 
summary: El comando remove asyncMirrorGroup quita un volumen de pareja reflejada huérfano de la cabina de almacenamiento. 
---
= Eliminar un par reflejado asincrónico incompleto del grupo de espejos asincrónicos - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `remove asyncMirrorGroup` el comando elimina un volumen de pareja reflejada huérfano de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Se crea un volumen de pareja reflejada huérfano cuando se elimina un volumen miembro de un grupo de reflejos asíncronos de un lado del grupo de reflejos asíncronos (ya sea el lado primario o el lado secundario), pero no del otro lado.

Los volúmenes de parejas reflejadas huérfanos se detectan cuando se restaura la comunicación entre las controladoras y los dos lados de la configuración reflejada concilian los parámetros de reflejo.

Este comando se debe utilizar cuando se quita correctamente la relación de reflejo de la cabina de almacenamiento local o remota, pero no se puede quitar de la cabina de almacenamiento correspondiente debido a un problema de comunicación.



== Sintaxis

[source, cli, subs="+macros"]
----
remove asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
incompleteMirror volume=pass:quotes[_"volumeName"_]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`asyncMirrorGroup`
 a| 
Nombre del grupo de reflejos asíncronos que contiene el volumen huérfano que se desea quitar. El nombre del grupo de reflejos asíncronos debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`volume`
 a| 
Nombre del volumen huérfano que se desea quitar del grupo de reflejos asíncronos. El nombre del volumen debe escribirse entre comillas dobles (" ").

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
