---
permalink: commands-a-z/remove-syncmirror.html 
sidebar: sidebar 
keywords: remove, synchronous, mirror 
summary: El comando remove SyncMirror elimina la relación de reflejo entre el volumen primario y el volumen secundario en una pareja reflejada remota. 
---
= Quite el mirroring síncrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `remove syncMirror` el comando elimina la relación de reflejo entre el volumen primario y el volumen secundario en una pareja reflejada remota.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800 y E5700, Siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800 o E5700, se deben poseer los roles Storage Admin.



== Contexto

[NOTE]
====
En las versiones anteriores de este comando, el identificador de función era `remoteMirror`. Este identificador de función ya no es válido y lo reemplaza `syncMirror`.

====


== Sintaxis

[listing, subs="+macros"]
----
remove syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1 ... volumeNameN_]])
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`localVolume`
 a| 
Nombre del volumen primario (el volumen de la cabina de almacenamiento local) que se desea quitar. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`localVolumes`
 a| 
Nombres de varios volúmenes primarios (los volúmenes de la cabina de almacenamiento local) que se desean quitar. Para introducir los nombres de los volúmenes primarios, se deben respetar las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Los nombres deben estar separados por un espacio.


Si los nombres de los volúmenes primarios tienen caracteres especiales o están compuestos solo por números, se deben introducir de acuerdo con las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.


|===


== Nivel de firmware mínimo

6.10
