---
permalink: commands-a-z/remove-volumecopy-target.html 
sidebar: sidebar 
keywords: remove, volume, copy 
summary: El comando remove VolumeCopy target quita una pareja de copia de volumen. 
---
= Eliminar copia de volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `remove volumeCopy target` el comando quita una pareja de copia de volumen.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Este comando es válido para las parejas de copias de volumen Snapshot.

[NOTE]
====
Con la versión de firmware 7.83 `copyType=(online | offline)` el parámetro ya no se utiliza.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
remove volumeCopy target pass:quotes[[_targetName_]] [source pass:quotes[[_sourceName_]]]
----


[[parameters]]
== Parámetros

|===
| Parámetro | Descripción 


 a| 
`target`
 a| 
Nombre del volumen objetivo que se desea quitar. El nombre del volumen objetivo se debe escribir entre corchetes ([ ]). Si el nombre del volumen objetivo contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`source`
 a| 
Nombre del volumen de origen que se desea quitar. El nombre del volumen de origen se debe escribir entre corchetes ([ ]). Si el nombre del volumen de origen contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

5.40

7.83 elimina la `copyType=(online | offline)` parámetro.
