---
permalink: commands-a-z/remove-storagearray-directoryserver.html 
sidebar: sidebar 
keywords: remove, storage array, directory, server, role, mapping 
summary: El comando remove storageArray directoryServer quita del directorio especificado las asignaciones de roles definidas para el servidor. 
---
= Eliminar la asignación de roles del servidor de directorio de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `remove storageArray directoryServer` quita las asignaciones de roles definidas para el servidor de directorio especificado.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
remove storageArray directoryServer pass:quotes[[_domainId_]]
    (allGroupDNs | groupDNs=pass:quotes[(_groupDN1 ... groupDNN_))]
----


[[parameters]]
== Parámetros

|===
| Parámetro | Descripción 


 a| 
`directoryServer`
 a| 
Permite especificar el dominio, mediante un ID de dominio, en el que se quitará la asignación.



 a| 
`allGroupDNs`
 a| 
Permite quitar del dominio todas las asignaciones de nombre distintivo del grupo.



 a| 
`groupDNs`
 a| 
Permite especificar el nombre distintivo (DN) de los grupos' que se van a eliminar.

[NOTE]
====
Si se introducen varios grupos, se deben separar los valores con un espacio.

====
|===


[[examples]]
== Ejemplos

[listing]
----

SMcli -n Array1 -c "remove storageArray directoryServer ["domain1"]
                    groupDNs=("CN=company-distlist,OU=Managed,
                    OU=MyCompanyGroups,DC=hq,DC=mycompany,DC=com");"

SMcli -n Array1 -c "remove storageArray directoryServer ["domain1"]
                    allGroupDNs;"

SMcli completed successfully.
----