---
permalink: commands-a-z/remove-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, volume, asynchronous, mirror, group 
summary: El comando remove volume asyncMirrorGroup quita un volumen miembro de un grupo de reflejos asíncronos existente. 
---
= Eliminar volumen de un grupo de espejo asincrónico - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `remove volume asyncMirrorGroup` el comando quita un volumen miembro de un grupo de reflejos asíncronos existente.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

De manera opcional, se pueden eliminar los volúmenes miembro del repositorio del grupo de reflejos asíncronos.

Este comando es válido únicamente en la cabina de almacenamiento local que contiene el grupo de reflejos asíncronos cuyo volumen miembro se desea quitar.



== Sintaxis

[source, cli, subs="+macros"]
----
remove volume pass:quotes[[_"volumeName"_]] asyncMirrorGroup=pass:quotes[_"asyncMirrorGroupName"_]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`volume`
 a| 
Nombre del volumen específico que se desea quitar del grupo de reflejos asíncronos. El nombre del volumen debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`asyncMirrorGroup`
 a| 
Nombre del grupo de reflejos asíncronos que contiene el volumen miembro que se desea quitar. El nombre del grupo de reflejos asíncronos debe escribirse entre comillas dobles (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Determina si se quitarán del grupo de reflejos asíncronos todos los miembros del repositorio.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
