---
permalink: commands-a-z/remove-drives-from-ssd-cache.html 
sidebar: sidebar 
keywords: remove, drives, ssd, cache 
summary: 'El comando set ssdCache reduce la capacidad de la caché SSD mediante la eliminación de discos de estado sólido (SSD).' 
---
= Eliminar unidades de la caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set ssdCache` El comando reduce la capacidad de la caché SSD al eliminar los discos de estado sólido (SSD).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de soporte.



== Sintaxis

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
Nombre de la caché SSD de la que se desea quitar discos SSD. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`removeDrives`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

|===


== Notas

No se puede utilizar este comando para quitar todos los SSD de la caché SSD; se debe conservar al menos un disco SSD en la caché SSD. Si desea quitar por completo la caché SSD, use `delete ssdCache` en su lugar del comando.



== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
