---
permalink: commands-a-z/rename-ssd-cache.html 
sidebar: sidebar 
keywords: rename, ssd, cache 
summary: El comando set ssdCache cambia el nombre de la caché SSD. 
---
= Cambie el nombre de la caché SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set ssdCache` El comando cambia el nombre de la caché SSD.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de soporte.



== Sintaxis

[listing, subs="+macros"]
----
set ssdCache pass:quotes[[_old_ssdCacheName_]] userLabel=pass:quotes[_"new_ssdCacheName_"]
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
Nombre de la caché SSD que se desea cambiar. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD contiene caracteres especiales o está compuesto solo por números, también se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`userLabel`
 a| 
Nombre nuevo de la caché SSD. El nombre debe escribirse entre comillas dobles (" "). Puede usar cualquier combinación de caracteres alfanuméricos, guion bajo (_), guion (-) y almohadilla (#) para el identificador. Los identificadores pueden tener un máximo de 30 caracteres.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
