---
permalink: commands-a-z/reset-storagearray-iserstatsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, iser, baseline 
summary: El comando reset storageArray iserStatsBaseline restablece la base de Iser a 0 para la cabina de almacenamiento. 
---
= Restablecer la línea base iSER de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `reset storageArray iserStatsBaseline` El comando restablece la base Iser en 0 para la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800 y E5700, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800 o E5700, debe contar con el rol de administrador de almacenamiento.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:reset-storagearray-hostportstatisticsbaseline.adoc[Restablecer la línea de base para las estadísticas de puertos de host de la cabina de almacenamiento] comando.

====


== Sintaxis

[source, cli]
----
reset storageArray iserStatsBaseline
----


== Parámetros

Ninguno.



== Notas

Este comando no restablece realmente los números de formato mantenidos en el hardware y el firmware. En su lugar, el firmware crea una Snapshot de los valores del contador actual y utiliza estos valores para informar de las diferencias en los números cuando se recuperan las estadísticas. El nuevo tiempo de base se aplica a las dos controladoras de manera que los números de la controladora se sincronizan entre sí. Si una controladora se restablece y la otra no, los números ya no están sincronizados. El cliente nota que las controladoras no están sincronizadas porque los datos de la Marca de hora que se informan junto a las estadísticas no son los mismos para ambas controladoras.



== Nivel de firmware mínimo

8.20

8.41 este comando quedó obsoleto.
