---
permalink: commands-a-z/reset-storagearray-iscsistatsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, iscsi, baseline 
summary: El comando reset storageArray iscsiStatsBaseline restablece la base de iSCSI a 0 para la cabina de almacenamiento. 
---
= Restablezca la línea de base iSCSI de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `reset storageArray iscsiStatsBaseline` El comando restablece la base iSCSI a 0 para la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800 y E5700, Siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800 o E5700, se deben poseer los roles Storage Admin.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:reset-storagearray-hostportstatisticsbaseline.adoc[Restablecer la línea de base para las estadísticas de puertos de host de la cabina de almacenamiento] comando.

====


== Sintaxis

[listing]
----
reset storageArray iscsiStatsBaseline
----


== Parámetros

Ninguno.



== Notas

Este comando restablece la base a 0 para ambas controladoras en la cabina de almacenamiento. El propósito de restablecer las bases de las dos controladoras es ayudar a asegurar que los números de la controladora estén sincronizados entre las controladoras. Si una controladora se restablece, pero la segunda no lo hace, se le informa al host de que las controladoras no están sincronizadas. Se notifica al host por medio de las marcas de tiempo que se informan con las estadísticas.



== Nivel de firmware mínimo

7.10

8.41 este comando quedó obsoleto.
