---
permalink: commands-a-z/reset-drive.html 
sidebar: sidebar 
keywords: reset, drive 
summary: El comando reset drive apaga y enciende una unidad en un grupo de volúmenes o un pool de discos para asistir en la recuperación de una unidad que presenta una conducta incoherente o que no es óptima. 
---
= Restablezca una unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `reset drive` la alimentación de comandos enciende una unidad en un grupo de volúmenes o un pool de discos para asistir en la recuperación de una unidad que presenta una conducta incoherente o que no es óptima.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Al apagar y encender una unidad, se pueden borrar algunos errores que ocasionan conductas incoherentes o que no son óptimas. Esto evita el reemplazo de una unidad cuando está experimentando solo un error puntual, no grave, y la unidad puede seguir estando operativa. Al restablecer una unidad de esta manera, se reducen las interrupciones y se evita su reemplazo.

Si el problema no se puede corregir mediante el ciclo de apagado y encendido de la unidad, los datos se copian desde la unidad y esta se apaga para realizar el reemplazo.

[NOTE]
====
Este comando no se puede utilizar para las unidades SSD fabricadas por Pliant. Utilice la `show storageArray profile` o el `show drive` comando para mostrar el fabricante de la(s) unidad(es).

====


== Sintaxis

[source, cli]
----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`drive`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`drive`
 a| 
Identificador a nivel mundial (WWID) de la unidad que se desea reemplazar. El nombre del WWID debe escribirse entre comillas dobles (" ") entre paréntesis angulares (< >).

|===


== Notas

La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0` , Y especifique el ID de la ranura en la que reside una unidad.

Después del ciclo de apagado y encendido de la unidad, la controladora debe verificar que la unidad sea funcional para poder colocarla nuevamente en uso. Si la unidad no se puede verificar, se Marca como una unidad con error. Para apagar y encender una unidad con error, es necesario contar con unidades de repuesto globales y una copia completa para una unidad de reemplazo después de que se pone en servicio.

No se pueden restablecer las unidades con errores mediante un ciclo de encendido y apagado más de una vez en un periodo de 24 horas y, en algunos casos, no se pueden restablecer más de una vez. Los umbrales y los contadores para los ciclos de apagado y encendido de la unidad se conservan en un almacenamiento persistente y se incluyen en los datos de captura de estado. Los eventos informativos se registran cuando se realiza el ciclo de apagado y encendido de una unidad.



== Nivel de firmware mínimo

8.20
