---
permalink: commands-a-z/reset-storagearray-hostportstatisticsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, host, port, statistics, baseline 
summary: El comando reset storageArray hostPortStatisticsBaseline restablece la base de estadística del puerto de host de la cabina de almacenamiento. 
---
= Restablecer la línea de base para las estadísticas de puertos de host de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `reset storageArray hostPortStatisticsBaseline` el comando restablece la base para las estadísticas de puertos de host de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Contexto

[NOTE]
====
Este comando reemplaza a la obsoleto xref:reset-storagearray-ibstatsbaseline.adoc[Restablezca la línea de base para las estadísticas InfiniBand de la cabina de almacenamiento], xref:reset-storagearray-iscsistatsbaseline.adoc[Restablezca la línea de base iSCSI de la cabina de almacenamiento], y. xref:reset-storagearray-iserstatsbaseline.adoc[Restablezca la línea de base Iser de la cabina de almacenamiento] comandos.

====


== Sintaxis

[listing]
----

reset storageArray hostPortStatisticsBaseline type=(ISCSI| ISER | SRP | NVMEOF)
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`type`
 a| 
Permite indicar el tipo de estadísticas que se recogerán. Las opciones válidas son: `ISCSI`, `ISER`, `SRP`, y. `NVMEOF`.

|===


== Nivel de firmware mínimo

8.41
