---
permalink: commands-a-z/reset-storagearray-socbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, soc, baseline 
summary: 'El comando reset storageArray SOCBaseline restablece la base para todos los dispositivos de switch en un chip (SOC) a los que se accede a través de las controladoras.' 
---
= Restablecer la línea base del SOC de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `reset storageArray SOCBaseline` El comando restablece la base para todos los dispositivos de switch en un chip (SOC) a los que se accede a través de las controladoras.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Este comando restablece la base mediante el restablecimiento de todos los números de SOC en 0. Este comando solo es válido para dispositivos de tipo Fibre Channel en una topología de bucle arbitrado.



== Sintaxis

[source, cli]
----
reset storageArray SOCBaseline
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

6.16
