---
permalink: commands-a-z/resume-cgsnapvolume.html 
sidebar: sidebar 
keywords: resume, consistency, group, snapshot, volume 
summary: El comando resume cgSnapVolume reinicia una operación de copia en escritura para crear un volumen Snapshot de grupo de coherencia que se detuvo mediante el uso del comando stop cgSnapVolume. 
---
= Reanude el volumen Snapshot de grupo de coherencia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `resume cgSnapVolume` el comando reinicia una operación de copia en escritura para crear un volumen snapshot de grupo de coherencia que se ha detenido mediante el `stop cgSnapVolume` comando.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
resume cgSnapVolume pass:quotes[[_"snapVolumeName"_]]
cgSnapImage=pass:quotes[_"snapImageName"_]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`cgSnapVolume`
 a| 
Nombre del volumen Snapshot de grupo de coherencia que se desea reanudar. El nombre del volumen Snapshot de grupo de coherencia debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`cgSnapImage`
 a| 
Nombre de la imagen Snapshot en un grupo de coherencia que se reinicia. El nombre de la imagen Snapshot consta de dos partes:

* El nombre del grupo de coherencia
* Un identificador de la imagen Snapshot del grupo de coherencia


El identificador de la imagen Snapshot puede ser una de las siguientes opciones:

* Un valor entero que es el número de secuencia de la Snapshot en el grupo de coherencia.
* `NEWEST` - Esta opción debe usarse para mostrar la imagen Snapshot más reciente creada en el grupo de coherencia.
* `OLDEST` - Esta opción debe usarse para mostrar la imagen Snapshot más antigua creada en el grupo de coherencia.


El nombre de la imagen Snapshot debe escribirse entre comillas dobles (" ").

|===


== Notas

El nombre de una imagen Snapshot consta de dos partes separadas por dos puntos (:):

* El identificador del grupo de coherencia
* El identificador de la imagen Snapshot


Por ejemplo, si se desea reiniciar una operación de copia en escritura para una imagen Snapshot 12345, que se encuentra en el grupo de coherencia Snapshot snapgroup1 en un volumen Snapshot de grupo de coherencia denominado snapVol1, se debe usar este comando:

[listing]
----
resume cgSnapVolume ["snapVol1"] cgSnapImage=["snapgroup1:12345"]
----


== Nivel de firmware mínimo

7.83
