---
permalink: commands-a-z/resume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: resume, asynchronous, mirror, group 
summary: El comando resume asyncMirrorGroup reanuda la transferencia de datos entre todas las parejas reflejadas en un grupo de reflejos asíncronos. 
---
= Reanudar grupo de reflejos asíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `resume asyncMirrorGroup` el comando reanuda la transferencia de datos entre todas las parejas reflejadas de un grupo de reflejos asíncronos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Los datos que se escriben en los volúmenes primarios mientras el grupo de reflejos asíncronos estaba suspendido se escriben en los volúmenes secundarios de inmediato. La sincronización periódica se reanuda si se estableció un intervalo de sincronización automática.



== Sintaxis

[listing, subs="+macros"]
----
resume asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
[deleteRecoveryPointIfNecessary]
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`asyncMirrorGroup`
 a| 
El nombre del grupo de reflejos asíncronos en el cual se desea iniciar la sincronización. El nombre del grupo de reflejos asíncronos debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]").



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
El parámetro para eliminar el punto de recuperación si los datos de sincronización recuperables superaron el umbral de tiempo para la recuperación. El punto de recuperación se mide desde la hora en que se congelaron los datos en la cabina de almacenamiento principal.

|===


== Nivel de firmware mínimo

7.84

8,10 añade el `deleteRecoveryPointIfNecessary` parámetro

11,80 añade compatibilidad con cabinas EF600 y EF300
