---
permalink: commands-a-z/resume-ssdcache.html 
sidebar: sidebar 
keywords: resume, ssd, cache 
summary: El comando resume ssdCache reinicia el almacenamiento en caché para todos los volúmenes en los que se utiliza la caché SSD que se detuvo temporalmente con el comando suspend ssdCache. 
---
= Reanudar caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `resume ssdCache` El comando reinicia el almacenamiento en caché de todos los volúmenes que utilizan la caché SSD que se detuvo temporalmente con el `suspend ssdCache` comando.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Support Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
resume ssdCache pass:quotes[[_ssdCacheName_]]
----


[[parameter]]
== Parámetro

|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
El nombre de la caché SSD en la cual se desean reanudar operaciones de almacenamiento en caché. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
