---
permalink: commands-a-z/resume-snapimage-rollback.html 
sidebar: sidebar 
keywords: resume, snapshot, image, rollback 
summary: El comando resume snapImage rollback reanuda una operación de reversión que se encuentra en pausa. 
---
= Reanudar la reversión de imágenes instantáneas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `resume snapImage rollback` el comando reanuda una operación de reversión que se ha introducido en el estado de pausa.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Las operaciones de reversión pueden estar en pausa debido a errores de procesamiento, que generan la condición necesita atención en la cabina de almacenamiento.

Si no se puede reanudar la operación de reversión, la imagen Snapshot seleccionada se revierte al estado de pausa y se muestra la condición necesita atención.

[NOTE]
====
No se puede usar este comando para las imágenes Snapshot incluidas en una copia de volumen en línea.

====


== Sintaxis

[source, cli, subs="+macros"]
----
resume snapImage pass:quotes[[_snapImageName_]] rollback
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`snapImage`
 a| 
Nombre de la imagen Snapshot en la que se desea reiniciar una operación de reversión. El nombre de la imagen Snapshot consta de dos partes:

* El nombre del grupo Snapshot
* Un identificador de la imagen Snapshot en el grupo Snapshot


El identificador de la imagen Snapshot puede ser una de las siguientes opciones:

* Un valor entero que corresponde al número de secuencia de la Snapshot en el grupo Snapshot.
* `NEWEST` - Esta opción debe usarse para mostrar la imagen Snapshot más reciente creada en el grupo Snapshot.
* `OLDEST` - Esta opción debe usarse para mostrar la imagen Snapshot más antigua creada en el grupo Snapshot.


El nombre de la imagen Snapshot debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).

|===


== Notas

El nombre de una imagen Snapshot consta de dos partes separadas por dos puntos (:):

* El identificador del grupo Snapshot
* El identificador de la imagen Snapshot


Por ejemplo, si se desea reiniciar una operación de reversión para una imagen Snapshot 12345 que se encuentra en un grupo Snapshot denominado snapgroup1, se debe usar este comando:

[listing]
----
resume snapImage ["snapgroup1:12345"] rollback;
----


== Nivel de firmware mínimo

7.83
