---
permalink: commands-a-z/revive-snapvolume.html 
sidebar: sidebar 
keywords: revive, snapshot, volume 
summary: El comando revive snapVolume fuerza un volumen Snapshot especificado al estado Optimal. 
---
= Reactivar volumen Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `revive snapVolume` El comando fuerza a un volumen Snapshot especificado al estado Optimal.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Contexto

El volumen Snapshot puede ser de uno de los siguientes tipos:

* Un volumen Snapshot independiente
* Un volumen Snapshot miembro de un grupo de coherencia


Si el estado del volumen Snapshot no es con errores, el firmware muestra un mensaje de error y no ejecuta este comando.

[NOTE]
====
No se puede usar este comando para un volumen Snapshot que se usa en una copia de volumen en línea.

====


== Sintaxis

[listing, subs="+macros"]
----
revive snapVolume pass:quotes[[_snapVolumeName_]]
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`snapVolume`
 a| 
El nombre del volumen Snapshot que se desea configurar en el estado Optimal. El nombre del volumen Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del volumen Snapshot contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.



== Nivel de firmware mínimo

7.83
