---
permalink: commands-a-z/revive-volumegroup.html 
sidebar: sidebar 
keywords: revive, volume, group 
summary: El comando revive volumeGroup fuerza el grupo de volúmenes especificado y sus unidades con error asociadas al estado Optimal. 
---
= Reactivar grupo de volúmenes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `revive volumeGroup` El comando fuerza al grupo de volúmenes especificado y sus unidades con errores asociadas al estado Optimal.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



[[context]]
== Contexto

[NOTE]
====
*Posible pérdida de acceso a los datos* -- el uso correcto de este comando depende de la configuración de los datos en todas las unidades del grupo de volúmenes. Jamás intente reactivar una unidad a menos que el soporte técnico lo supervise.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----


[[parameter]]
== Parámetro

|===
| Parámetro | Descripción 


 a| 
`volumeGroup`
 a| 
El nombre del grupo de volúmenes que se desea establecer en el estado Optimal. El nombre del grupo de volúmenes debe escribirse entre corchetes ([ ]).

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
