---
permalink: commands-a-z/revive-snapgroup.html 
sidebar: sidebar 
keywords: revive, snapshot, group 
summary: El comando revive snapGroup fuerza el grupo Snapshot especificado al estado Optimal. 
---
= Reactivar grupo de instantáneas - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `revive snapGroup` El comando fuerza al grupo Snapshot especificado al estado Optimal.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



== Contexto

Si el estado del grupo Snapshot no es con errores, el firmware muestra un mensaje de error y no ejecuta este comando.



== Sintaxis

[source, cli, subs="+macros"]
----
revive snapGroup pass:quotes[[_snapGroupName_]]
----


== Parámetro

|===
| Parámetro | Descripción 


 a| 
`snapGroup`
 a| 
El nombre del grupo Snapshot que se desea configurar en el estado Optimal. El nombre del grupo Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo Snapshot contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.



== Nivel de firmware mínimo

7.83
