---
permalink: commands-a-z/save-alltrays-logfile.html 
sidebar: sidebar 
keywords: save, tray log 
summary: El comando save allTrays logfile guarda en un archivo los datos de detección del registro. 
---
= Guardar registro de bandeja - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save allTrays logFile` el comando guarda en un archivo los datos de detección del registro.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Las tarjetas medioambientales mantienen datos de detección del registro para cada soporte No todas las tarjetas medioambientales contienen datos de detección del registro.



== Sintaxis

[source, cli, subs="+macros"]
----
save allTrays logFile=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`*logFile*`
 a| 
La ruta y el nombre del archivo donde se guardarán los datos de detección del registro. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\traylogdat.txt"`

Este comando no anexa automáticamente ninguna extensión de archivo al archivo guardado. Se debe especificar una extensión de archivo al introducir el nombre del archivo.

|===


== Nivel de firmware mínimo

6.50
