---
permalink: commands-a-z/save-storagearray-ibstats.html 
sidebar: sidebar 
keywords: save, storage, array, infiniband, statistics 
summary: El comando save storageArray ibStats guarda en un archivo las estadísticas de rendimiento de InfiniBand de la cabina de almacenamiento. 
---
= Guarde las estadísticas InfiniBand de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `save storageArray ibStats` El comando guarda en un archivo las estadísticas de rendimiento de InfiniBand de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:save-storagearray-hostportstatistics.adoc[Guarde estadísticas de puertos de host de la cabina de almacenamiento] comando.

====


== Sintaxis

[listing, subs="+macros"]
----
save storageArray ibStats [raw | baseline]
file=pass:quotes["_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`raw`
 a| 
Las estadísticas que se recogen son todas estadísticas del inicio del día de la controladora. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`baseline`
 a| 
Las estadísticas que se recogen son todas estadísticas desde la hora en que se restablecieron a cero las controladoras mediante el `reset storageArray ibStatsBaseline` comando. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán las estadísticas de rendimiento. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\sup\ibstat.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de rendimiento de InfiniBand es `ib-statistics.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Notas

Si no se restablecieron las estadísticas de línea de base de InfiniBand desde el inicio del día de la controladora, la hora de inicio del día es la línea de base predeterminada.



== Nivel de firmware mínimo

7.32

8.41 este comando quedó obsoleto.
