---
permalink: commands-a-z/save-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, external, key management, certificate 
summary: El comando save storageArray keyManagementCertificate recupera el certificado instalado. 
---
= Recuperar el certificado de administración de claves externas instalado - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray keyManagementCertificate` el comando recupera el certificado instalado.



== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



== Contexto

[NOTE]
====
Este comando se aplica solo a la gestión de claves externas.

====


== Sintaxis

[source, cli, subs="+macros"]
----

save storageArray keyManagementCertificate certificateType=pass:quotes["_certificateType_"]
file=pass:quotes["_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`certificateType`
 a| 
Permite especificar el tipo de certificado que se desea instalar. Las opciones válidas son: `client` o. `server`.



 a| 
`file`
 a| 
Permite especificar el nombre de archivo para el certificado firmado o el certificado de CA de servidor.

|===


== Nivel de firmware mínimo

8.40
