---
permalink: commands-a-z/save-alldrives-logfile.html 
sidebar: sidebar 
keywords: save, drive log 
summary: El comando save allDrives logfile guarda los registros de la unidad en un archivo. 
---
= Guardar registro de unidad - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save allDrives logFile` el comando guarda los registros de la unidad en un archivo.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

La cabina de almacenamiento mantiene datos de registro de unidad para cada unidad.

[NOTE]
====
No ejecute este comando a menos que el soporte técnico le indique hacerlo.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
save allDrives logFile=pass:quotes["_filename_"]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`*logFile*`
 a| 
La ruta y el nombre del archivo donde se guardarán los registros de unidades. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\drive01.zip"`

[NOTE]
====
Este comando no anexa automáticamente ninguna extensión de archivo al archivo guardado. Es necesario especificar la extensión de archivo .zip al introducir el nombre del archivo.

====
|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
