---
permalink: commands-a-z/save-auditlog.html 
sidebar: sidebar 
keywords: save, audit log, records 
summary: El comando save auditlog recupera los registros de auditoría. 
---
= Guardar registros de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `save auditLog` el comando recupera los registros de auditoría.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Sintaxis

[listing, subs="+macros"]
----

save auditLog (all | (beginDate=pass:quotes[_date_ | endDate=_date_)]
|(beginRecord=pass:quotes[_timestamp_] | endRecord=pass:quotes[_timestamp_))] file=pass:quotes["_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`all`
 a| 
Permite recuperar todos los registros de auditoría.



 a| 
`beginDate`
 a| 
Permite especificar la fecha de inicio hasta la cual se deben recuperar los registros. El formato para introducir la fecha es MM:DD:AA en la zona horaria del cliente. El primer registro de auditoría recuperado será el primero que se haya publicado en la fecha especificada o después.

[NOTE]
====
El rango de medianoche a medianoche dependerá de la zona horaria del cliente.

====


 a| 
`endDate`
 a| 
Permite especificar la fecha de finalización hasta la cual se deben recuperar los registros. Si no se especifica, se recuperará la última entrada del registro. El formato para introducir la fecha es MM:DD:AA en la zona horaria del cliente. El último registro de auditoría recuperado será el último que se haya publicado en la fecha especificada o antes.

[NOTE]
====
El rango de medianoche a medianoche dependerá de la zona horaria del cliente.

====


 a| 
`beginRecord`
 a| 
Permite especificar el registro inicial desde el cual se deben recuperar registros. El valor es el valor entero que representa la Marca de hora de la primera entrada del registro de auditoría, inclusive. Si no se especifica, se recuperará la primera entrada del registro.



 a| 
`endRecord`
 a| 
Permite especificar el registro final hasta el cual se deben recuperar registros. El valor es el valor entero que representa la Marca de hora de la última entrada del registro de auditoría, inclusive. Si no se especifica, se recuperará la última entrada del registro.



 a| 
`file`
 a| 
Permite especificar el nombre del archivo de salida del registro de auditoría.

[NOTE]
====
Las entradas del registro de auditoría se guardan en orden descendente en el archivo, de la más nueva a la más antigua.

====
|===


== Ejemplos

[listing]
----

SMcli -n Array1 -c "save auditLog all file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog endRecord=1493070393313 file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog beginDate=12:12:16 endDate=04:01:17 file="myAuditLog.txt";"


SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40
