---
permalink: commands-a-z/save-storagearray-sasphycounts.html 
sidebar: sidebar 
keywords: save, storage, array, sas, phy, counts 
summary: 'El comando save storageArray SASPHYCounts guarda en un archivo los números de capa física SAS (SAS PHY).' 
---
= Guarde los números de PHY SAS de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `save storageArray SASPHYCounts` El comando guarda en un archivo los números de la capa física SAS (SAS PHY).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Para restablecer los números de SAS PHY, ejecute el `reset storageArray SASPHYBaseline` comando.



== Sintaxis

[listing, subs="+macros"]
----
save storageArray SASPHYCounts file=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán los números de SAS PHY. Escriba la ruta de acceso y el nombre del archivo entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\sasphy.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de error de SAS PHY es `sas-phy-error-log.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Nivel de firmware mínimo

6.10
