---
permalink: commands-a-z/save-storagearray-iserstatistics.html 
sidebar: sidebar 
keywords: save, storage, array, iser, statistics 
summary: El comando save storageArray iserStatistics guarda en un archivo las estadísticas de rendimiento de Iser de la cabina de almacenamiento. 
---
= Guarde estadísticas de Iser de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray iserStatistics` El comando guarda en un archivo las estadísticas de rendimiento de Iser de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:save-storagearray-hostportstatistics.adoc[Guarde estadísticas de puertos de host de la cabina de almacenamiento] comando.

====


== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray iserStatistics [(raw | baseline)] file=pass:quotes["_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`raw`
 a| 
Las estadísticas recogidas son todas estadísticas del inicio del día de la controladora. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`baseline`
 a| 
Las estadísticas que se recogen son todas estadísticas desde la hora en que se restablecieron a cero las controladoras mediante el `reset storageArray iserStatsBaseline` comando. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán las estadísticas de rendimiento. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\iserstat.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de rendimiento de iSCSI es `iser-statistics.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Notas

Si no se restablecieron las estadísticas de línea de base de Iser desde el inicio del día de la controladora, la hora de inicio del día es la línea de base predeterminada.



== Nivel de firmware mínimo

8.20

8.41 este comando quedó obsoleto.
