---
permalink: commands-a-z/save-storagearray-soccounts.html 
sidebar: sidebar 
keywords: save, storage, array, soc, counts 
summary: El comando save storageArray SOCCounts guarda en un archivo las estadísticas de error de SOC. 
---
= Guardar recuentos de SOC de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray SOCCounts` El comando guarda las estadísticas de error de SOC en un archivo.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Este comando solo es válido para dispositivos de tipo Fibre Channel en una topología de bucle arbitrado.



== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray SOCCounts file=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán las estadísticas de error de SOC. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\socstat.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de error de SOC es `soc-statistics.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Notas

Para guardar de manera más efectiva las estadísticas de error de SOC en un archivo, siga estos pasos:

. Ejecute el `reset storageArray SOCBaseline` Comando para establecer todos los números de SOC en 0.
. Ejecute la cabina de almacenamiento durante un periodo predeterminado (por ejemplo, dos horas).
. Ejecute el `save storageArray SOCCounts file`="[.code]``_filename_``comando ".




== Nivel de firmware mínimo

6.16
