---
permalink: commands-a-z/save-storage-array-diagnostic-data.html 
sidebar: sidebar 
keywords: save, storage, array, diagnostic, data 
summary: 'El comando save storageArray diagnosticData guarda en un archivo datos de diagnóstico de la cabina de almacenamiento de las controladoras o los módulos de servicios de entorno (ESM).' 
---
= Guarde los datos de diagnóstico de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray diagnosticData` Comando guarda en un archivo los datos de diagnóstico de la cabina de almacenamiento de las controladoras o los módulos de servicios de entorno (ESM).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Es posible revisar el contenido del archivo más adelante. También es posible enviar el archivo al soporte técnico para su ulterior revisión.

Después de guardar los datos de diagnóstico, es posible reiniciar los registros de NVSRAM que contienen los datos de diagnóstico para poder sobrescribir los datos antiguos. Utilice la `reset storageArray diagnosticData` comando para restablecer los registros de datos de diagnóstico.

[NOTE]
====
Este comando se debe ejecutar solo con la ayuda del soporte técnico.

====


== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray diagnosticData [(controller | tray)]
file=pass:quotes["_filename_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`diagnosticData`
 a| 
Este parámetro permite descargar los datos de diagnóstico de las controladoras o los ESM.



 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán los datos de diagnóstico de la cabina de almacenamiento. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\sadiag.zip"`

Este comando guarda automáticamente los datos en un archivo comprimido; sin embargo, este comando no anexa automáticamente una extensión al archivo guardado. Debe especificar el `.zip` extensión al introducir el nombre del archivo.

|===


== Notas

En versiones de este comando anteriores a 7.77, la opción de usuario era `esm` en lugar de `tray`. Desde 7.77, `tray` sustituye `esm`. Uso de `esm` todavía es compatible, pero puede sustituir la mejor compatibilidad con futuras versiones `esm` con `tray`.



== Nivel de firmware mínimo

6.16

7.77 `tray` sustituye `esm`.
