---
permalink: commands-a-z/save-storagearray-iscsistatistics.html 
sidebar: sidebar 
keywords: save, storage, array, iscsi, statistics 
summary: El comando save storageArray iscsiStatistics guarda en un archivo las estadísticas de rendimiento de iSCSI de la cabina de almacenamiento. 
---
= Guardar estadísticas iSCSI de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray iscsiStatistics` El comando guarda en un archivo las estadísticas de rendimiento de iSCSI de la cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:save-storagearray-hostportstatistics.adoc[Guarde estadísticas de puertos de host de la cabina de almacenamiento] comando.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray iscsiStatistics [(raw | baseline)] file=pass:quotes["_filename_"]
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`raw`
 a| 
Las estadísticas recogidas son todas estadísticas del inicio del día de la controladora. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`baseline`
 a| 
Las estadísticas que se recogen son todas estadísticas desde la hora en que se restablecieron a cero las controladoras mediante el `reset storageArray ibStatsBaseline` comando. El parámetro debe escribirse entre corchetes ([ ]).



 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán las estadísticas de rendimiento. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\iscsistat.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de rendimiento de iSCSI es `iscsi-statistics.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


[[notes]]
== Notas

Si no se restablecieron las estadísticas de línea de base de iSCSI desde el inicio del día de la controladora, la hora de inicio del día es la línea de base predeterminada.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.10

8.41 este comando quedó obsoleto.
