---
permalink: commands-a-z/save-storagearray-firmwareinventory.html 
sidebar: sidebar 
keywords: save, storage, array, firmware, inventory 
summary: El comando save storageArray firmwareInventory guarda un informe en un archivo con todo el firmware que se ejecuta actualmente en la cabina de almacenamiento. 
---
= Guarde el inventario de firmware de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `save storageArray firmwareInventory` el comando guarda un informe en un archivo de todo el firmware que se está ejecutando actualmente en la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

El informe incluye el firmware de estos componentes:

* Controladoras
* Unidades
* Cajones (si corresponde)
* Módulos de servicios de entorno (ESM)
* Fuentes de alimentación


Es posible usar la información para identificar el firmware desactualizado o el firmware que no coincide con el resto del firmware en la cabina de almacenamiento. También es posible enviar el informe al soporte técnico para su ulterior revisión.



== Sintaxis

[listing, subs="+macros"]
----
save storageArray firmwareInventory file=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardará el inventario de firmware. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\fwinvent.txt"`

El nombre predeterminado del archivo que contiene el inventario de firmware es `firmware-inventory.txt`. Este comando no anexa automáticamente ninguna extensión de archivo al archivo guardado. Se debe especificar una extensión de archivo al introducir el nombre del archivo.

|===


== Nivel de firmware mínimo

7.70
