---
permalink: commands-a-z/save-storagearray-sasphycounts.html 
sidebar: sidebar 
keywords: save, storage, array, sas, phy, counts 
summary: 'El comando save storageArray SASPHYCounts guarda en un archivo los números de capa física SAS (SAS PHY).' 
---
= Guardar recuentos de PHY SAS de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray SASPHYCounts` El comando guarda en un archivo los números de la capa física SAS (SAS PHY).



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Para restablecer los números de SAS PHY, ejecute el `reset storageArray SASPHYBaseline` comando.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray SASPHYCounts file=pass:quotes["_filename_"]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán los números de SAS PHY. Escriba la ruta de acceso y el nombre del archivo entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\sasphy.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de error de SAS PHY es `sas-phy-error-log.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
