---
permalink: commands-a-z/save-storagearray-rlscounts.html 
sidebar: sidebar 
keywords: save, storage, array, rls, counts 
summary: 'El comando save storageArray RLSCounts guarda en un archivo los números de estado de lectura de enlace (RLS).' 
---
= Guarde números de RLS de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray RLSCounts` El comando guarda en un archivo los números de estado de enlace de lectura (RLS).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray RLSCounts file=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán los números de RLS. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\rlscnt.csv"`

El nombre predeterminado del archivo que contiene los números de RLS es `read-link-status.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Notas

Para guardar de manera más efectiva los números de RLS en un archivo, siga estos pasos:

. Ejecute el `reset storageArray RLSBaseline` Comando para establecer todos los números de RLS en 0.
. Ejecute la cabina de almacenamiento durante un periodo predeterminado (por ejemplo, dos horas).
. Ejecute el `save storageArray RLSCounts file`="[.code]``_filename_``comando ".




== Nivel de firmware mínimo

6.10
