---
permalink: commands-a-z/save-storagearray-performancestats.html 
sidebar: sidebar 
keywords: save, storage, array, performance, statistics 
summary: El comando save storageArray performanceStats guarda en un archivo las estadísticas de rendimiento. 
---
= Guardar estadísticas de rendimiento de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `save storageArray performanceStats` el comando guarda las estadísticas de rendimiento en un archivo.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Antes de usar este comando, ejecute el `set session performanceMonitorInterval` y la `set session performanceMonitorIterations` comando para especificar la frecuencia con la que se recopilan las estadísticas.



== Sintaxis

[source, cli, subs="+macros"]
----
save storageArray performanceStats file=pass:quotes["_filename_"]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se guardarán las estadísticas de rendimiento. El nombre del archivo debe escribirse entre comillas dobles (" "). Por ejemplo:

`file="C:\Program Files\CLI\logs\sastat.csv"`

El nombre predeterminado del archivo que contiene las estadísticas de rendimiento es `performanceStatistics.csv`. Puede utilizar cualquier nombre de archivo, pero debe utilizar `.csv` extensión.

|===


== Nivel de firmware mínimo

6.10
