---
permalink: commands-a-z/set-snapvolume-mediascanenabled.html 
sidebar: sidebar 
keywords: set, snapshot, volume, media, scan 
summary: El comando set snapVolume mediaScanEnabled ejecuta un análisis de medios en las unidades utilizadas para un volumen Snapshot. 
---
= Configurar análisis de medios de volumen Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set snapVolume mediaScanEnabled` el comando ejecuta un análisis de medios en las unidades utilizadas para un volumen snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

De manera opcional, es posible realizar una comprobación de redundancia de los datos.



== Sintaxis

[listing, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]]
mediaScanEnabled=(TRUE | FALSE) [redundancyCheckEnabled=(TRUE | FALSE)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`snapVolume`
 a| 
El nombre del volumen Snapshot para el cual se configuran las propiedades. El identificador del volumen Snapshot debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`mediaScanEnabled`
 a| 
La opción para activar o desactivar el análisis de medios en el volumen Snapshot. Para activar el análisis de medios, establezca este parámetro en `TRUE`. Para desactivar el análisis de medios, establezca este parámetro en `FALSE`. (Si se deshabilita el análisis de medios en el nivel de la cabina de almacenamiento, este parámetro queda sin efecto).



 a| 
`redundancyCheckEnabled`
 a| 
La opción para activar o desactivar la comprobación de redundancia durante un análisis de medios. Para activar la comprobación de redundancia, establezca este parámetro en `TRUE` . Para desactivar la comprobación de redundancia, establezca este parámetro en `FALSE`.

|===


== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.



== Nivel de firmware mínimo

7.83
