---
permalink: commands-a-z/set-initiator.html 
sidebar: sidebar 
keywords: set, initiator 
summary: El comando set initiator actualiza el objeto iniciador. 
---
= Establecer iniciador - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set initiator` comando actualiza el objeto iniciador.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

[NOTE]
====
Este comando reemplaza a la obsoleto xref:set-iscsiinitiator.adoc[Configure el iniciador de iSCSI] comando.

====
[NOTE]
====
Este comando se aplica únicamente a iSCSI, Iser, NVMe over roce, NVMe over InfiniBand y NVMe over Fibre Channel.

====


[[syntax]]
== Sintaxis

[source, cli]
----
set initiator (["initiatorName"] | <"initiatorQualifiedName">) ([userLabel="newInitiatorName"] |
[host="newHostName"] | [chapSecret="newSecurityKey"])
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`initiator`
 a| 
Permite especificar el identificador del iniciador en el que se desean definir propiedades. El nombre debe escribirse entre comillas dobles ("' "'). También se debe escribir entre corchetes ([ ]) si el valor es una etiqueta de usuario o entre paréntesis angulares (< >) si el valor es un nombre completo (por ejemplo, IQN o nqn).



 a| 
`userLabel`
 a| 
Permite introducir una nueva etiqueta de usuario para el objeto iniciador. La nueva etiqueta de usuario debe escribirse entre comillas dobles (" ").



 a| 
`host`
 a| 
Permite introducir un nuevo host al cual se conecta el puerto de host. El nombre de host debe escribirse entre comillas dobles (" ").



 a| 
`chapSecret`
 a| 
Permite introducir una clave de seguridad nueva que se desea usar para autenticar una conexión entre iguales. La clave de seguridad debe escribirse entre comillas dobles (" "). Este parámetro solo se aplica a. `iSCSI` y.. `iSER` tipos de interfaz del host.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.41
