---
permalink: commands-a-z/set-storagearray-isnslisteningport.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, listen, port 
summary: El comando set storageArray isnsListeningPort establece el puerto de escucha del servidor iSNS. 
---
= Establecer el puerto de escucha del servidor iSNS de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray isnsListeningPort` El comando configura el puerto de escucha del servidor iSNS.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
set storageArray isnsListeningPort=pass:quotes[_listeningPortIPAddress_]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`isnsListeningPort`
 a| 
La dirección IP que desea usar para el puerto de escucha del servidor iSNS. El intervalo de valores del puerto de escucha es `49152` para `65535`. El valor predeterminado es `53205`.

El puerto de escucha reside en el servidor y realiza las siguientes actividades:

* Supervisa solicitudes entrantes de conexión de clientes
* Gestiona el tráfico hacia el servidor


Cuando un cliente solicita una sesión de red con un servidor, el dispositivo de escucha recibe la solicitud. Si la información del cliente coincide con la información del dispositivo de escucha, este otorga una conexión con el servidor de bases de datos.

|===


[[notes]]
== Notas

Un puerto de escucha reside en el servidor de bases de datos y es responsable de estas actividades:

* Escucha (supervisión) de solicitudes entrantes de conexión de clientes
* Gestión del tráfico hacia el servidor


Cuando un cliente solicita una sesión de red con un servidor, un dispositivo de escucha recibe la solicitud Si la información del cliente coincide con la información del dispositivo de escucha, este otorga una conexión con el servidor de bases de datos.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.10
