---
permalink: commands-a-z/set-storagearray-traypositions.html 
sidebar: sidebar 
keywords: set, storage, array, tray, positions 
summary: El comando set storageArray trayPositions define la posición de los soportes en una cabina de almacenamiento. Al introducir este comando, se deben incluir todos los soportes de la cabina de almacenamiento. 
---
= Configure posiciones de soporte de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set storageArray trayPositions` el comando define la posición de los soportes de una cabina de almacenamiento. Al introducir este comando, se deben incluir todos los soportes de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[listing, subs="+macros"]
----
set storageArray trayPositions=pass:quotes[(controller | _trayID_ ... _trayIDn_)]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`trayPositions`
 a| 
Una lista de todos los ID de soporte. La secuencia de los ID de soporte de la lista define las posiciones para el soporte de la controladora y los soportes de las unidades de la cabina de almacenamiento. Los valores válidos son `0` para `99`. Introduzca los valores de ID de los soportes separados por un espacio. Escriba la lista de valores de ID de los soportes entre paréntesis. Para las cabinas de almacenamiento donde el soporte de la controladora tenga un identificador predefinido fuera del rango de valores de posición de soportes válidos, use la `controller` valor.

|===


== Notas

Este comando define la posición de un soporte en una cabina de almacenamiento mediante la posición del ID de soporte en la `trayPositions` lista. Por ejemplo, si tiene un soporte de controladoras con un ID configurado en 84 y los soportes de unidades con ID configurados en 1, 12 y 50, el `trayPositions` secuencia (`84 1 12 50`) coloca la bandeja del controlador en la primera posición, la bandeja de unidades 1 en la segunda posición, la bandeja de unidades 12 en la tercera posición y la bandeja de unidades 50 en la cuarta. La `trayPositions` secuencia (`1 84 50 12`) coloca la bandeja del controlador en la segunda posición, la bandeja de unidades 1 en la primera posición, la bandeja de unidades 50 en la tercera posición y la bandeja de unidades 12 en la cuarta.

[NOTE]
====
Se deben incluir todos los soportes de la cabina de almacenamiento de la lista definida por `trayPositions` parámetro. Si el número de soportes de la lista no coincide con el número total de soportes de la cabina de almacenamiento, se muestra un mensaje de error.

====
[NOTE]
====
El software de gestión muestra visualmente la primera posición en primer lugar, las demás posiciones en orden relativo debajo y la última posición en último lugar.

====


== Nivel de firmware mínimo

6.10

Para 6.14 y 6.16, `controller` no es un valor válido.
