---
permalink: commands-a-z/set-volumecopy-target.html 
sidebar: sidebar 
keywords: set, volume, copy 
summary: El comando set VolumeCopy target define las propiedades de una pareja de copias de volumen. 
---
= Configure la copia de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set volumeCopy target` el comando define las propiedades de una pareja de copia de volumen.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

[NOTE]
====
Con la versión de firmware 7.83 `copyType=(online | offline)` el parámetro ya no se utiliza.

====
Este comando es válido para las parejas de copias de volumen Snapshot.



== Sintaxis

[source, cli, subs="+macros"]
----
set volumeCopy target pass:quotes[[_targetName_]]
source pass:quotes[[_sourceName_]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`target`
 a| 
El nombre del volumen en el cual se copiarán datos. El nombre del volumen objetivo se debe escribir entre corchetes ([ ]). Si el nombre del volumen objetivo contiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`source`
 a| 
El nombre del volumen desde el cual se copiarán datos. El nombre del volumen de origen se debe escribir entre corchetes ([ ]). Si el nombre del volumen de origen contiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes



 a| 
`copyPriority`
 a| 
Prioridad que tiene la copia de volumen con respecto a la actividad de I/o del host. Los valores válidos son `highest`, `high`, `medium`, `low`, o. `lowest`.



 a| 
`targetReadOnlyEnabled`
 a| 
El ajuste para establecer si se puede escribir en el volumen objetivo o solo leer el volumen objetivo. Para escribir en el volumen objetivo, este parámetro debe configurarse en `FALSE`. Para impedir la escritura en el volumen objetivo, este parámetro debe configurarse en `TRUE`.



 a| 
`copyType`
 a| 
[NOTE]
====
Este parámetro quedó obsoleto.

====
|===


== Notas

Cuando se usa este comando, pueden especificarse uno o varios de los parámetros opcionales.



== Nivel de firmware mínimo

5.40

7.83 elimina la `copyType=(online | offline)` parámetro.
