---
permalink: commands-a-z/set-hostgroup.html 
sidebar: sidebar 
keywords: set, host, group 
summary: El comando set hostGroup cambia el nombre de un grupo de hosts. 
---
= Establecer grupo de hosts - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set hostGroup` el comando cambia el nombre de un grupo de hosts.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
set hostGroup pass:quotes[[_hostGroupName_]]
userLabel=pass:quotes["_newHostGroupName_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`hostGroup`
 a| 
El nombre del grupo de hosts que se desea cambiar. El nombre del grupo de hosts debe escribirse entre corchetes ([ ]). Si el nombre del grupo de hosts tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`userLabel`
 a| 
El nuevo nombre del grupo de hosts. El nuevo nombre del grupo de hosts debe escribirse entre comillas dobles (" ").

|===


== Notas

En los nombres, se puede usar cualquier combinación de caracteres alfanuméricos, guiones y guiones bajos. Los nombres pueden tener hasta 30 caracteres.



== Nivel de firmware mínimo

6.10
