---
permalink: commands-a-z/set-storagearray-isnsipv6address.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, ipv6, address 
summary: El comando set storageArray isnsIPv6Address establece la dirección IPv6 para el servidor iSNS. 
---
= Establecer la dirección IPv6 del servidor iSNS de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray isnsIPv6Address` El comando configura la dirección IPv6 para el servidor iSNS.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
set storageArray isnsIPv6Address=pass:quotes[_ipAddress_]
----


== Parámetro

[cols="2*"]
|===
| Parámetros | Descripción 


 a| 
`isnsIPv6Address`
 a| 
La dirección IPv6 que desea usar para el servidor iSNS.

|===


== Notas

El protocolo iSNS facilita la detección, la gestión y la configuración automatizadas de dispositivos iSCSI y dispositivos Fibre Channel en una red TCP/IP. ISNS ofrece servicios de detección y gestión de almacenamiento inteligente comparables a los que se encuentran en las redes Fibre Channel, para permitir que una red IP genérica funcione de manera similar a una red de área de almacenamiento. ISNS también facilita una integración fluida de redes IP y redes Fibre Channel gracias a su capacidad para emular servicios de estructura Fibre Channel y gestionar dispositivos iSCSI y Fibre Channel. ISNS agrega valor a cualquier red de almacenamiento que posea dispositivos iSCSI, dispositivos Fibre Channel o cualquier combinación de ambos.



== Nivel de firmware mínimo

7.10
