---
permalink: commands-a-z/set-iscsitarget.html 
sidebar: sidebar 
keywords: set, iscsi, target, properties 
summary: El comando set iscsiTarget define las propiedades de un destino iSCSI. 
---
= Configure propiedades de destino iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set iscsiTarget` El comando define las propiedades de un destino iSCSI.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.

[NOTE]
====
Este comando quedó obsoleto y fue sustituido por el xref:set-target.adoc[Configurar propiedades objetivo] comando.

====


== Sintaxis

[listing, subs="+macros"]
----
set iscsiTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`iscsiTarget`
 a| 
El destino iSCSI para el cual desea definir propiedades. Escriba el `_userLabel_` entre comillas dobles (" "). También debe escribir el `_userLabel_` En corchetes ([ ]) si la etiqueta de usuario es un alias objetivo, o entre paréntesis angulares (< >) si la etiqueta de usuario es un nombre completo de iSCSI (IQN).



 a| 
`authenticationMethod`
 a| 
El medio de autenticación de la sesión iSCSI.



 a| 
`chapSecret`
 a| 
La clave de seguridad que se desea usar para autenticar una conexión entre iguales.



 a| 
`targetAlias`
 a| 
El nuevo nombre que se desea usar para el destino. El nombre debe escribirse entre comillas dobles (" ").

|===


== Notas

El protocolo de autenticación por desafío mutuo (CHAP) es un protocolo que autentica los iguales de una conexión. EL FUNCIONAMIENTO DE CHAP se basa en que los iguales compartan un _secret_. Un secreto es una clave de seguridad similar a una contraseña.

Utilice la `chapSecret` parámetro para configurar claves de seguridad para los iniciadores que requieren autenticación mutua. El secreto CHAP debe tener entre 12 y 57 caracteres. En esta tabla, se indican los caracteres válidos.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Espacio
 a| 
!
 a| 
"
 a| 
#
 a| 
$
 a| 
%
 a| 
&
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
A.
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
YO
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
P
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
#
 a| 
_
 a| 
'
 a| 
a.
 a| 
b
 a| 
c
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
yo
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p
 a| 
p
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== Nivel de firmware mínimo

7.10

8.41 este comando quedó obsoleto.
