---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: El comando set storageArray passwordlength permite que el usuario administrador configure una longitud mínima para todas las contraseñas nuevas o actualizadas de la cabina de almacenamiento. 
---
= Establecer la longitud de la contraseña de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray passwordlength` el comando permite al usuario administrador establecer una longitud mínima para todas las contraseñas nuevas o actualizadas de la cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[syntax]]
== Sintaxis

[source, cli]
----
set storageArray passwordLength=<INTEGER>
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`password length`
 a| 
Permite configurar la longitud mínima requerida para todas las contraseñas nuevas o actualizadas.



 a| 
`INTEGER`
 a| 
Permite configurar la longitud mínima requerida, entre 0 y 30, para todas las contraseñas nuevas o actualizadas.

|===


[[examples]]
== Ejemplos

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.41 añade el comando.
