---
permalink: commands-a-z/set-storagearray-loginbanner.html 
sidebar: sidebar 
keywords: set, storage, array, login, banner 
summary: El comando set storageArray loginBanner permite cargar un archivo de texto para usar como banner de inicio de sesión. El texto de un banner puede incluir un aviso y un mensaje de consentimiento, que se presentan a los usuarios antes de que establezcan sesiones en System Manager de SANtricity o ejecuten comandos. 
---
= Establecer el banner de inicio de sesión de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray loginBanner` permite cargar un archivo de texto para usar como banner de inicio de sesión. El texto de un banner puede incluir un aviso y un mensaje de consentimiento, que se presentan a los usuarios antes de que establezcan sesiones en System Manager de SANtricity o ejecuten comandos.



== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



== Sintaxis

[source, cli]
----
set storageArray loginBanner file="path_to_login_banner"
----


== Contexto

Después de cargar el archivo de texto, se guarda en la cabina de almacenamiento. El texto del banner se muestra antes de la pantalla de inicio de sesión de System Manager de SANtricity o antes de la ejecución de comandos.



== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo donde se almacena el archivo de texto del banner de inicio de sesión.

[NOTE]
====
El archivo del banner de inicio de sesión no puede estar vacío y debe ser de 5 KB o menos.

====
|===


== Nivel de firmware mínimo

8.41
