---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: El comando set storageArray controllerHealthImageAllowOverWrite establece una Marca en una cabina de almacenamiento para permitir que la imagen de estado de una nueva controladora sobrescriba la imagen de estado de una controladora existente en cabinas de almacenamiento que admiten la función de imagen de estado de controladora. 
---
= Configurar el permiso de sobrescritura de imagen de estado de controladora de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray controllerHealthImageAllowOverWrite` el comando configura una marca en la controladora para permitir que una imagen de estado de controladora nueva sobrescriba una imagen de estado de controladora existente en cabinas de almacenamiento que admiten la función de imágenes de estado.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Si la cabina de almacenamiento no es compatible con la función de imagen de estado de controladora, el comando devuelve un error.

[NOTE]
====
Con la versión de firmware 8.20 `coreDumpAllowOverWrite` el parámetro se sustituye por el `controllerHealthImageAllowOverWrite` parámetro.

====


== Sintaxis

[source, cli]
----
set storageArray controllerHealthImageAllowOverWrite
----


== Parámetros

Ninguno.



== Notas

Cuando se recupera la imagen de estado de la controladora, la `allow overwrite` se ha establecido el indicador. Si no se recupera la imagen de estado de la controladora, la imagen caduca en 48 horas, después del cual `allow overwrite` se ha establecido el indicador. Cuando utilice la `set storageArray controllerHealthImageAllowOverWrite` para establecer el `allow overwrite` indicador, la expiración de 48 horas se renuncia como si la imagen se hubiera recuperado.



== Nivel de firmware mínimo

7.86

8.20 sustituye la `*coreDumpAllowOverWrite*` con el `controllerHealthImageAllowOverWrite` parámetro.
