---
permalink: commands-a-z/set-hostchannel.html 
sidebar: sidebar 
keywords: set, host, channel 
summary: El comando set hostChannel define el identificador de bucle para el canal de host. 
---
= Establecer canal de host - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set hostChannel` El comando define el identificador de bucle para el canal de host.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
set hostChannel pass:quotes[[_hostChannelNumber_]]
preferredID=pass:quotes[_portID_]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`hostChannel`
 a| 
El número de identificador del canal de host en el que se desea configurar el identificador de bucle. El número del identificador del canal de host debe escribirse entre corchetes ([ ]).

Debe usarse un valor de canal de host que sea apropiado para el modelo de controladora correspondiente. Un soporte de controladoras puede admitir un canal de host como mínimo y ocho como máximo. Los valores de canal de host válidos son los siguientes `a1`, `a2`, `a3`, `a4`, `a5`, `a6`, `a7`, `a8`, `b1`, `b2`, `b3`, `b4`, `b5`, `b6`, `b7`, o. `b8`.



 a| 
`preferredID`
 a| 
El identificador de puerto para el canal del host especificado. Los valores de identificador de puerto son `0` para `127`.

|===


== Nivel de firmware mínimo

6.10

en la versión 6.14, se añade una actualización para el identificador del canal del host.

en la versión 7.15, se añade una actualización para el identificador del canal del host.
