---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: El comando set storageArray passwordlength permite que el usuario administrador configure una longitud mínima para todas las contraseñas nuevas o actualizadas de la cabina de almacenamiento. 
---
= Configure la longitud de contraseña de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set storageArray passwordlength` el comando permite al usuario administrador establecer una longitud mínima para todas las contraseñas nuevas o actualizadas de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Sintaxis

[listing]
----
set storageArray passwordLength=<INTEGER>
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`password length`
 a| 
Permite configurar la longitud mínima requerida para todas las contraseñas nuevas o actualizadas.



 a| 
`INTEGER`
 a| 
Permite configurar la longitud mínima requerida, entre 0 y 30, para todas las contraseñas nuevas o actualizadas.

|===


== Ejemplos

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


== Nivel de firmware mínimo

8.41 añade el comando.
