---
permalink: commands-a-z/set-storagearray-isnsipv6address.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, ipv6, address 
summary: El comando set storageArray isnsIPv6Address establece la dirección IPv6 para el servidor iSNS. 
---
= Establecer la dirección IPv6 del servidor iSNS de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray isnsIPv6Address` El comando configura la dirección IPv6 para el servidor iSNS.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
set storageArray isnsIPv6Address=pass:quotes[_ipAddress_]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetros | Descripción 


 a| 
`isnsIPv6Address`
 a| 
La dirección IPv6 que desea usar para el servidor iSNS.

|===


[[notes]]
== Notas

El protocolo iSNS facilita la detección, la gestión y la configuración automatizadas de dispositivos iSCSI y dispositivos Fibre Channel en una red TCP/IP. ISNS ofrece servicios de detección y gestión de almacenamiento inteligente comparables a los que se encuentran en las redes Fibre Channel, para permitir que una red IP genérica funcione de manera similar a una red de área de almacenamiento. ISNS también facilita una integración fluida de redes IP y redes Fibre Channel gracias a su capacidad para emular servicios de estructura Fibre Channel y gestionar dispositivos iSCSI y Fibre Channel. ISNS agrega valor a cualquier red de almacenamiento que posea dispositivos iSCSI, dispositivos Fibre Channel o cualquier combinación de ambos.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.10
