---
permalink: commands-a-z/set-storagearray-syslog.html 
sidebar: sidebar 
keywords: update, storage, array, syslog, configuration 
summary: El comando set storageArray syslog permite cambiar la dirección, el protocolo o el número de puerto del servidor de syslog. 
---
= Actualice la configuración de syslog de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray syslog` comando permite cambiar el protocolo, el número de puertos o la dirección del servidor de syslog.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Sintaxis

[source, cli]
----
set storageArray syslog id="<id>"
serverAddress="<address>"
port=<port> protocol=("udp" | "tcp" | "tls")
components=(componentName=("auditLog") ...)
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`serverAddress`
 a| 
Nombre de host o dirección IP del receptor de syslog.



 a| 
`port`
 a| 
Número de puerto del receptor de syslog.



 a| 
`protocol`
 a| 
Protocolo de transmisión de syslog. Los valores admitidos incluyen UDP, TCP o TLS.



 a| 
`components`
 a| 
Lista de entradas del componente que se registrarán en el servidor de syslog. En este momento, solo se admiten registros de auditoría.



 a| 
`componentName`
 a| 
Nombre del componente; en este momento, solo se admite "auditlog".

|===


=== Ejemplo

[listing]
----
SMcli -n Array1 -c "set storageArray syslog
id=\"331998fe-3154-4489-b773-b0bb60c6b48e\"
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e Server Address: 192.168.2.1
Port: 514 Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Nivel de firmware mínimo

8.42
