---
permalink: commands-a-z/set-tray-serviceallowedindicator.html 
sidebar: sidebar 
keywords: set, tray, service, action, allowed, indicator 
summary: 'El comando set tray serviceAllowedIndicator enciende o apaga la luz indicadora de permiso de acción de servicio en un contenedor de alimentación-ventilador, un contenedor de interconexión-batería o un contenedor de módulo de servicios de entorno (ESM).' 
---
= Configure indicador de permiso de acción de servicio del soporte
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set tray serviceAllowedIndicator` El comando enciende o apaga la luz indicadora de permiso de acción de servicio en un contenedor de alimentación-ventilador, un contenedor de interconexión-batería o un contenedor de módulo de servicios de entorno (ESM).



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Contexto

Si la cabina de almacenamiento no es compatible con la función de la luz indicadora de permiso de acción de servicio, este comando devuelve un error. Si la cabina de almacenamiento admite el comando, pero no puede apagar o encender la luz indicadora, este comando devuelve un error.

Para encender o apagar la luz indicadora de permiso de acción de servicio en el contenedor de la controladora, utilice `set controller serviceAllowedIndicator` comando.



== Sintaxis

[listing, subs="+macros"]
----
set tray pass:quotes[[_trayID_]]
(powerFan [(left | right | top | bottom)] |
interconnect |
esm [(left | right | top | bottom)]) |
battery [(left | right)] |
fanCanister [(left | right)]  |
powerCanister [(top | bottom)] |
serviceAllowedIndicator=(on | off)
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`tray`
 a| 
El soporte donde reside el contenedor de alimentación-ventilador, el contenedor de interconexión, el contenedor de ESM o el contenedor de baterías. Los valores de ID de soporte son `0` para `99`. El valor de ID de soporte debe escribirse entre corchetes ([ ]). Si no se introduce un valor de ID de soporte, el ID de soporte de la controladora será el valor predeterminado.



 a| 
`powerFan`
 a| 
La luz indicadora de permiso de acción de servicio en el contenedor de alimentación-ventilador que se desea encender o apagar. Los identificadores de contenedor de alimentación-ventilador válidos son los siguientes `left`, `right`, `top`, o. `bottom`. Escriba el identificador de contenedor de alimentación-ventilador entre corchetes ([ ]).



 a| 
`interconnect`
 a| 
La luz indicadora de permiso de acción de servicio para el contenedor de interconexión-batería.



 a| 
`esm`
 a| 
La luz indicadora de permiso de acción de servicio para un contenedor de ESM. Los identificadores de contenedor de ESM válidos son `left`, `right`, `top`, o. `bottom`.



 a| 
`battery`
 a| 
La luz indicadora de permiso de acción de servicio para una batería. Los identificadores de batería válidos son los siguientes `left` o. `right`.



 a| 
`fanCanister`
 a| 
La luz indicadora de permiso de acción de servicio para un contenedor de ventilador. Los identificadores de contenedor de ventilador válidos son los siguientes `left` o. `right`.



 a| 
`powerCanister`
 a| 
La luz indicadora de permiso de acción de servicio para un contenedor de alimentación. Los identificadores de contenedor de alimentación válidos son los siguientes `top` o. `bottom`.



 a| 
`serviceAllowedIndicator`
 a| 
La opción para encender o apagar la luz indicadora de permiso de acción de servicio. Para encenderla, configure este parámetro como `on`. Para apagarla, configure este parámetro como `off`.

|===


== Notas

Este comando se definió originalmente para ser usado con el soporte de controladoras CE6998 Este comando no es compatible con soportes de controladoras despachados antes de la introducción del soporte de controladoras CE6998



== Ejemplo

Este comando enciende la luz indicadora de permiso de acción de servicio para el ESM izquierdo del soporte 5 con la dirección IP 155.155.155.155.

[listing]
----
SMcli 123.145.167.214 123.145.167.215 -c "set tray [5]
ESM [left] serviceAllowedIndicator=on;"
----


== Nivel de firmware mínimo

en la versión 6.14, se añaden estos parámetros:

* `powerFan`
* `interconnect`


en la versión 6.16, se añaden estos parámetros:

* `tray`
* `esm`


7.60 añade los identificadores `top` y.. `bottom`.

7.60 añade el `powerCanister` y.. `fanCanister` parámetros.
