---
permalink: commands-a-z/set-storagearray-securitykey.html 
sidebar: sidebar 
keywords: set, internal, storage, array, security key 
summary: El comando set storageArray securityKey define la clave de seguridad que se utiliza en toda la cabina de almacenamiento para implementar la funciones de seguridad Drive Security. 
---
= Establecer la clave de seguridad de la matriz de almacenamiento interna - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray securityKey` Comando configura la clave de seguridad que se usa en la cabina de almacenamiento para implementar la función Drive Security.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[context]]
== Contexto

Cuando una unidad compatible con la función de seguridad en la cabina de almacenamiento se asigna a un grupo de volúmenes o un pool de discos protegido, esa unidad tiene la función de seguridad habilitada a través de la clave de seguridad. Para poder configurar la clave de seguridad, debe usar el `create storageArray securityKey` comando para crear la clave de seguridad.

[NOTE]
====
Este comando se aplica solo a la gestión de claves internas.

====


[[syntax]]
== Sintaxis

[source, cli]
----
set storageArray securityKey
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Las unidades compatibles con la función de seguridad tienen hardware para acelerar el procesamiento criptográfico y cada una tiene una clave de unidad única. Una unidad compatible con la función de seguridad se comporta como cualquier otra unidad hasta que se añade a un grupo de volúmenes protegido, momento en el cual se convierte en una unidad con la función de seguridad habilitada.

Siempre que se enciende una unidad con la función de seguridad habilitada. Se requiere la clave de seguridad correcta de la controladora para poder leer o escribir datos. Por lo tanto, una unidad con la función de seguridad habilitada utiliza dos claves: La clave de la unidad, que cifra y descifra los datos, y la clave de seguridad, que autoriza los proceso de cifrado y descifrado. La `set storageArray securityKey` el comando confirma la clave de seguridad con todas las controladoras y las unidades con la función de seguridad habilitada en la cabina de almacenamiento. La función de cifrado de disco completo garantiza que si una unidad con la función de seguridad habilitada se quita físicamente de una cabina de almacenamiento, ningún otro dispositivo puede leer sus datos a menos que se conozca la clave de seguridad.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.50
