---
permalink: commands-a-z/set-email-smtp-delivery-method-e2800-e5700.html 
sidebar: sidebar 
keywords: specify, email, smtp, delivery method, individual, E2800, E5700, arrays 
summary: 'El comando set storageArray AutoSupport deliveryMethod configura el método de entrega para enviar mensajes de AutoSupport al correo electrónico (SMTP).' 
---
= Especifique el método de entrega de correo electrónico (SMTP)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set storageArray autoSupport deliveryMethod` El comando configura el método de entrega para enviar mensajes de AutoSupport al correo electrónico (SMTP).



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Sintaxis

[listing, subs="+macros"]
----
set storageArray autoSupport deliveryMethod=email
mailRelayServer=pass:quotes["_serverAddress_" senderEmail="_emailAddress_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`deliveryMethod`
 a| 
Permite al usuario especificar el método de entrega para la recogida de AutoSupport. Las opciones válidas son:

* correo electrónico
* HTTP
* HTTPS


[NOTE]
====
Si se configura el método de correo electrónico, se deshabilitan AutoSupport OnDemand y Remote Diagnostics.

====


 a| 
`mailRelayServer`
 a| 
Permite al usuario especificar el servidor de transmisión de correo para la recogida de AutoSupport.



 a| 
`senderEmail`
 a| 
Permite al usuario especificar la dirección de correo electrónico de envío para la recogida de AutoSupport.

|===


=== Ejemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportConfig deliveryMethod=email mailRelayServer=\"mailserver.company.com\" senderEmail=\"user@company.com\";"

SMcli completed successfully.
----


=== Verificación

Envíe un mensaje de prueba mediante el `_start storageArray autoSupport deliveryTest_` comando para verificar que sus métodos de entrega están configurados correctamente.



== Nivel de firmware mínimo

8.40
