---
permalink: commands-a-z/set-drivechannel.html 
sidebar: sidebar 
keywords: set, drive, channel, status 
summary: El comando set driveChannel define el rendimiento del canal de la unidad. 
---
= Establecer el estado del canal de la unidad - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set driveChannel` el comando define el rendimiento del canal de la unidad.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



[[syntax]]
== Sintaxis

[source, cli]
----
set driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)]
status=(optimal | degraded)
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`driveChannel`
 a| 
El número de identificador del canal de la unidad en el que desea configurar el estado. Los valores de canal de unidad válidos son los siguientes `1`, `2`, `3`, `4`, `5`, `6`, `7`, o. `8`. El número de canal de la unidad debe escribirse entre corchetes ([ ]).



 a| 
`status`
 a| 
La condición del canal de la unidad. Puede configurarse el estado del canal de la unidad como `optimal` o. `degraded`.

|===


[[notes]]
== Notas

Utilice la `optimal` Opción para mover un canal de unidad degradado nuevamente al estado Optimal. Utilice la `degraded` opción cuando el canal de la unidad está experimentando problemas y la cabina de almacenamiento requiere más tiempo para las transferencias de datos.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10

en la versión 7.15, se añade la actualización del identificador del canal de la unidad.
