---
permalink: commands-a-z/set-autosupport-https-delivery-method.html 
sidebar: sidebar 
keywords: AutoSupport, HTTPS, HTTP, delivery method, 
summary: 'El comando set storageArray AutoSupport deliveryMethod configura el método de entrega para enviar mensajes de AutoSupport a HTTP(S).' 
---
= Especificar el método de entrega de AutoSupport http(s) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray autoSupport deliveryMethod` El comando configura el método de entrega para enviar mensajes de AutoSupport a HTTP(S).



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----

set storageArray autoSupport deliveryMethod=email mailRelayServer="mail.example.com" senderEmail="sender@example.com"
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`deliveryMethod`
 a| 
Permite al usuario especificar el método de entrega para la recogida de AutoSupport. Las opciones válidas son:

* correo electrónico
* HTTPS


[NOTE]
====
Si se configura el método de correo electrónico, se deshabilitan AutoSupport OnDemand y Remote Diagnostics.

====


 a| 
`direct`
 a| 
Permite al usuario conectarse directamente a los sistemas de soporte técnico de destino mediante los protocolos HTTP o HTTPS.



 a| 
`proxyConfigScript`
 a| 
Permite al usuario especificar la ubicación de un archivo de script de autoconfiguración de proxy (PAC)



 a| 
`proxyServer`
 a| 
Permite al usuario especificar los detalles del servidor del proxy HTTP(S) necesarios para establecer la conexión con el sistema de soporte técnico de destino.



 a| 
`hostAddress`
 a| 
Permite al usuario especificar la dirección de host del servidor del proxy. Es obligatorio si se utiliza ProxyServer.



 a| 
`portNumber`
 a| 
Permite al usuario especificar el número de puerto del servidor del proxy. Es obligatorio si se utiliza ProxyServer.



 a| 
`username`
 a| 
Permite al usuario especificar el nombre de usuario del servidor del proxy, si está configurado.



 a| 
`password`
 a| 
Permite al usuario especificar la contraseña del servidor del proxy, si está configurada.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40



[[examples]]
== Ejemplos

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


[[verification]]
== Verificación

Envíe un mensaje de prueba mediante el `start storageArray autoSupport deliveryTest` comando para verificar que sus métodos de entrega están configurados correctamente.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40
