---
permalink: commands-a-z/set-thin-volume-attributes.html 
sidebar: sidebar 
keywords: set, thin, volume, attributes 
summary: El comando set volume define las propiedades de un volumen fino. 
---
= Establecer atributos de volumen delgado - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set volume` el comando define las propiedades de un volumen fino.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Es posible usar los parámetros para definir las propiedades de uno o varios volúmenes finos.



== Sintaxis

[source, cli, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]] | volume <"wwID">)
[newCapacity=pass:quotes[_capacityValue_]]
[repositoryMaxCapacity=pass:quotes[_capacityValue_]]
[repositoryExpansionPolicy=(automatic|manual)]
[warningThresholdPercent=pass:quotes[_warningThresholdPercentValue_]]
[addRepositoryCapacity=capacity-spec][hostReportingPolicy=(standard | thin)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volume`
 a| 
El nombre del volumen para el cual se desean definir propiedades. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen tiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`volume`
 a| 
El identificador a nivel mundial (WWID) del volumen para el cual se desean definir propiedades. El nombre del WWID debe escribirse entre comillas dobles (" ") entre paréntesis angulares (< >).



 a| 
`volumes`
 a| 
Los nombres de varios volúmenes para los cuales se desean definir propiedades. Todos los volúmenes tendrán las mismas propiedades. Los nombres de los volúmenes deben escribirse de acuerdo con estas reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Los nombres deben estar separados por un espacio.


Si los nombres de los volúmenes contienen caracteres especiales o están compuestos solo por números, se deben introducir de acuerdo con las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.




 a| 
`newCapacity`
 a| 
Este parámetro aumenta la capacidad virtual del volumen fino. La capacidad virtual es el valor que el volumen informará a un host que esté asignado al volumen. Los valores menores o iguales a la capacidad existente se producirá un error. El tamaño se define en unidades de `bytes`, `KB`, `MB`, `GB`, o. `TB`.

La capacidad virtual mínima es 32 MB.

La capacidad virtual máxima es 256 TB.



 a| 
`repositoryMaxCapacity*`
 a| 
Este parámetro configura la capacidad máxima del volumen de repositorios. El valor no debe ser inferior a la capacidad física del volumen de repositorios. Si el valor nuevo produce una reducción de la capacidad a un nivel inferior al umbral de advertencia, el comando generará un error.

[NOTE]
====
El comando `repositoryMaxCapacity` trabaja con `repositoryExpansionPolicy=automatic`.

====


 a| 
`repositoryExpansionPolic*`
 a| 
Este parámetro establece la política de expansión en `automatic` o. `manual`.Al cambiar la directiva de `automatic` para `manual`, el valor de capacidad máxima (cuota) cambia a la capacidad física del volumen de repositorios.



 a| 
`warningThresholdPercent`
 a| 
El porcentaje de capacidad de un volumen fino que debe alcanzarse para que se envíe una alerta de advertencia de que el volumen está casi completo. Deben usarse valores enteros. Por ejemplo, el valor 70 significa 70 %.

Los valores válidos son de 1 a 100.

Si el parámetro se configura en 100, las alertas de advertencia quedan deshabilitadas.



 a| 
`addRepositoryCapacity`
 a| 
Este parámetro asigna la capacidad de la extensión libre del pool de discos. Si el espacio disponible es insuficiente, el comando falla.

[NOTE]
====
El comando `addRepositoryCapacity` trabaja con `repositoryExpansionPolicy=manual`.

====


 a| 
`*hostReportingPolicy*`
 a| 
Este parámetro cambia la manera en que el volumen fino se informa al host. Los valores válidos son `standard` o. `thin`.

|===


== Notas

Cuando se usa este comando, pueden especificarse uno o varios de los parámetros opcionales.

En la siguiente tabla, se enumeran los límites de capacidad para un volumen fino.

[cols="2*"]
|===
| Tipo de capacidad | Tamaño 


 a| 
Capacidad virtual mínima
 a| 
32 MB



 a| 
Capacidad virtual máxima
 a| 
256 TB



 a| 
Capacidad física mínima
 a| 
4 GB



 a| 
Capacidad física máxima
 a| 
257 TB

|===
Los volúmenes finos son compatibles con las mismas operaciones que los volúmenes estándar, con las siguientes excepciones:

* No se puede cambiar el tamaño de los segmentos de un volumen fino.
* No se puede habilitar la comprobación de redundancia de lectura previa de un volumen fino.
* No se puede utilizar un volumen fino como volumen objetivo en una copia de volumen.
* No se puede utilizar un volumen fino en una operación de mirroring síncrono.


Para cambiar un volumen fino por un volumen estándar, se debe utilizar la operación de copia de volumen para crear una copia del volumen fino. El destino de una copia de volumen siempre es un volumen estándar.



== Nivel de firmware mínimo

7.83
