---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: 'El comando set drive nativeState añade las unidades ausentes (externas) de nuevo a su grupo de volúmenes original y para que formen parte del grupo de volúmenes en la nueva cabina de almacenamiento.' 
---
= Establecer unidad externa como nativa - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set drive nativeState` el comando añade las unidades ausentes (externas) de nuevo a su grupo de volúmenes original y a formar parte del grupo de volúmenes en la nueva cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Se considera que una unidad es nativa cuando forma parte de un grupo de volúmenes en una cabina de almacenamiento. Se considera que una unidad es externa cuando no pertenece a un grupo de volúmenes en una cabina de almacenamiento o cuando no puede importarse con las unidades de un grupo de volúmenes que se transfieren a una nueva cabina de almacenamiento. El segundo de estos fallos crea un grupo de volúmenes incompleto en la nueva cabina de almacenamiento.

Use esta operación solo para recuperación de emergencia: Cuando es necesario cambiar el estado de una unidad externa y regresar a un estado nativo dentro de su grupo de volúmenes original.

[NOTE]
====
*Posible corrupción de datos o pérdida de datos* -- el uso de este comando por razones distintas de lo indicado anteriormente podría dar lugar a la pérdida de datos sin notificación.

====


== Sintaxis

[source, cli, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`drive` o. `drives`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800, E5700, EF600 y EF300 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`allDrives`
 a| 
La opción para seleccionar todas las unidades.

|===


== Notas

La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.



== Nivel de firmware mínimo

7.10

7.60 añade el `drawerID` entrada del usuario.
