---
permalink: commands-a-z/set-cgsnapvolume.html 
sidebar: sidebar 
keywords: set, consistency, group, snapshot, volume 
summary: El comando set cgSnapVolume crea un nombre único para un volumen Snapshot de un grupo de coherencia. 
---
= Establecer el volumen de la instantánea del grupo de consistencia - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set cgSnapVolume` el comando crea un nombre único para un volumen snapshot de un grupo de coherencia.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
set cgSnapVolume pass:quotes[[_cgSnapVolumeName_]]
userLabel=pass:quotes["_cgSnapVolumeName_"]
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`cgSnapVolume`
 a| 
El nombre del volumen del grupo de coherencia que se desea cambiar. El nombre del volumen Snapshot del grupo de coherencia debe escribirse entre corchetes ([ ]).



 a| 
`userLabel`
 a| 
El nuevo nombre que se desea otorgar al volumen Snapshot en el grupo de coherencia. El nombre nuevo del volumen Snapshot debe escribirse entre comillas dobles (" ").

|===


[[notes]]
== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83
