---
permalink: commands-a-z/set-snapgroup-increase-decreaserepositorycapacity.html 
sidebar: sidebar 
keywords: set, snapshot, group, repository, volume, capacity 
summary: El comando set snapGroup increase/decreaseRepositoryCapacity aumenta o reduce la capacidad de un volumen de repositorios de un grupo Snapshot. 
---
= Establecer la capacidad del volumen del repositorio del grupo de instantáneas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set snapGroup increase/decreaseRepositoryCapacity` comando aumenta o reduce la capacidad de un volumen de repositorios de grupo snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, 2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis para aumentar la capacidad

[source, cli, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]] increaseRepositoryCapacity
(repositoryVolumes="repos_xxxx" | repositoryVolumes=pass:quotes[((_volumeGroupName_]
pass:quotes[[capacity=_capacityValue_]])) | repositoryVolumes=pass:quotes[((_diskPoolName_]
pass:quotes[[capacity=_capacityValue_]])))
----


== Sintaxis para reducir la capacidad

[listing, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
decreaseRepositoryCapacity
count=pass:quotes[_numberOfVolumes_]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`snapGroup`
 a| 
El nombre del grupo Snapshot en el que se desea aumentar o reducir la capacidad. El nombre del grupo Snapshot debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`repositoryVolume`
 a| 
El nombre del volumen de repositorios en el que se desea aumentar la capacidad. Se agrega un volumen estándar disponible al volumen de repositorios para aumentar la capacidad del volumen de repositorios.

Existen dos opciones para definir el nombre de un volumen de repositorios:

* Usar un volumen de repositorios existente: Name
* Crear un nuevo volumen de repositorios cuando se ejecuta este comando


El nombre de un volumen de repositorios existente consiste en dos partes:

* El término "repos"
* Identificador numérico de cuatro dígitos que el software de administración del almacenamiento asigna al nombre del volumen de repositorios


El nombre del volumen de repositorios existente debe escribirse entre comillas dobles (" ").

Para crear un nuevo volumen de repositorios cuando se ejecuta este comando, es necesario introducir el nombre de un grupo de volúmenes o un pool de discos donde se ubicará el volumen de repositorios. Opcionalmente, también se puede definir la capacidad del volumen de repositorios. Para definir la capacidad, es posible usar los siguientes valores:

* Un valor entero que representa un porcentaje de la capacidad del volumen base
* Un valor de fracción decimal que representa un porcentaje de la capacidad del volumen base
* Un tamaño específico para el volumen de repositorios El tamaño se define en unidades de `bytes`, `KB`, `MB`, `GB`, o. `TB`.


Si no se usa la opción de capacidad, el software de administración del almacenamiento establece la capacidad en 20 % de la capacidad del volumen base.

Cuando se ejecuta este comando, el software de administración del almacenamiento crea el volumen de repositorios para el volumen Snapshot.



 a| 
`count`
 a| 
El número de volúmenes de repositorios que se desea quitar del grupo Snapshot. Deben usarse valores enteros.

|===


== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para la etiqueta de usuario. Las etiquetas de usuario pueden tener hasta 30 caracteres.

El firmware y el software de administración del almacenamiento crean automáticamente el nombre del volumen de repositorios cuando se crea un nuevo grupo Snapshot. No se puede cambiar el nombre del volumen de repositorios, ya que se interrumpiría el enlace con las imágenes Snapshot.

Un volumen de repositorios de grupo Snapshot es un volumen expandible que se estructura como un conjunto concatenado de hasta 16 entidades de volumen estándar. Inicialmente, un volumen de repositorios expandible tiene un solo elemento. La capacidad del volumen de repositorios expandible es exactamente igual a la de ese único elemento. Para aumentar la capacidad de un volumen de repositorios expandible, se deben añadir volúmenes estándar. La capacidad compuesta del volumen de repositorios expandible pasa a ser la suma de las capacidades de todos los volúmenes estándar concatenados.

Un volumen de repositorios de grupo Snapshot debe satisfacer un requisito de capacidad mínima que equivale a la suma de lo siguiente:

* 32 MB para admitir la sobrecarga fija para el grupo Snapshot y el procesamiento de copia en escritura.
* Capacidad para el procesamiento de reversiones, que es equivalente a 1/5000 de la capacidad del volumen base.


La capacidad mínima es una imposición del firmware de la controladora y del software de administración del almacenamiento.



== Nivel de firmware mínimo

7.83
