---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: El comando set drive SecurityID se utiliza para restablecer la configuración original de fábrica de una unidad FIPS. 
---
= Configure el identificador de seguridad de la unidad FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set drive securityID` El comando se utiliza para restablecer la configuración original de fábrica de una unidad FIPS.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Contexto

[NOTE]
====
Este comando restablece la configuración original de fábrica de una unidad FIPS y borra todos los datos existentes en la unidad. Esta operación es completamente irreversible. Esto puede ser necesario si la unidad está bloqueada debido a un archivo de claves de seguridad o una frase de contraseña desconocida o no válida o ausente. Se borrarán todos los datos existentes de la unidad.

====
Para borrar una unidad FDE, utilice `start secureErase` comando.



== Sintaxis

[listing, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`drive`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`securityID`
 a| 
El identificador de seguridad de la unidad que se va a borrar, en formato de cadena. Esta cadena puede tener un máximo de 32 caracteres. La forma del identificador de seguridad puede variar de acuerdo con el fabricante.

[NOTE]
====
Para encontrar el identificador de seguridad, retire la unidad y lea el identificador de seguridad en la etiqueta del compartimento.

====
|===


== Notas

La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.



== Ejemplo

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== Nivel de firmware mínimo

8.25
