---
permalink: commands-a-z/set-storagearray-isnslisteningport.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, listen, port 
summary: El comando set storageArray isnsListeningPort establece el puerto de escucha del servidor iSNS. 
---
= Configure el puerto de escucha de servidor iSNS de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set storageArray isnsListeningPort` El comando configura el puerto de escucha del servidor iSNS.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[listing, subs="+macros"]
----
set storageArray isnsListeningPort=pass:quotes[_listeningPortIPAddress_]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`isnsListeningPort`
 a| 
La dirección IP que desea usar para el puerto de escucha del servidor iSNS. El intervalo de valores del puerto de escucha es `49152` para `65535`. El valor predeterminado es `53205`.

El puerto de escucha reside en el servidor y realiza las siguientes actividades:

* Supervisa solicitudes entrantes de conexión de clientes
* Gestiona el tráfico hacia el servidor


Cuando un cliente solicita una sesión de red con un servidor, el dispositivo de escucha recibe la solicitud. Si la información del cliente coincide con la información del dispositivo de escucha, este otorga una conexión con el servidor de bases de datos.

|===


== Notas

Un puerto de escucha reside en el servidor de bases de datos y es responsable de estas actividades:

* Escucha (supervisión) de solicitudes entrantes de conexión de clientes
* Gestión del tráfico hacia el servidor


Cuando un cliente solicita una sesión de red con un servidor, un dispositivo de escucha recibe la solicitud Si la información del cliente coincide con la información del dispositivo de escucha, este otorga una conexión con el servidor de bases de datos.



== Nivel de firmware mínimo

7.10
