---
permalink: commands-a-z/set-syslog.html 
sidebar: sidebar 
keywords: configure, syslog, set 
summary: El comando set syslog configura la información de las alertas de syslog. Es posible configurar el monitor de eventos para que se envíen alertas al servidor de syslog cuando se produzca algún evento que genere alertas. 
---
= Configure los ajustes de syslog
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set syslog` comando configura la información de alertas de syslog. Es posible configurar el monitor de eventos para que se envíen alertas al servidor de syslog cuando se produzca algún evento que genere alertas.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

* Debe estar disponible la dirección del servidor de syslog. La dirección debe ser un nombre de dominio completo o una dirección IPv4 o IPv6.
* Debe estar disponible el número de puerto UDP del servidor de syslog. Por lo general, se trata del puerto 514.




== Sintaxis

[listing, subs="+macros"]
----

set syslog [defaultFacility=pass:quotes[_facilityNumber_]]
| [defaultTag=pass:quotes[_defaultTag_]]
| [syslogFormat=pass:quotes[_rfc3164_|_rfc5424_]]
| (serverAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_)]
| addServerAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_))]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`defaultFacility`
 a| 
Opcional. Permite especificar el número de la instalación predeterminada. La instalación predeterminada debe ser un valor numérico entre 0 y 23.



 a| 
`defaultTag`
 a| 
Opcional. Permite especificar la etiqueta predeterminada. La cadena debe escribirse entre comillas.



 a| 
`syslogFormat`
 a| 
El formato de mensajería utilizado para los mensajes de syslog. El valor puede ser uno de los siguientes:

* `rfc3164` - Formato compatible con RFC 3164
* `rfc5424` - Formato compatible con RFC 5424




 a| 
`serverAddresses`
 a| 
Permite establecer una o varias direcciones de servidor de syslog con números de puerto asociados. Cuando se usa esta opción, se borran las direcciones de servidor existentes. Esta dirección de servidor de syslog puede ser un nombre de dominio completo, una dirección IPv4 o una dirección IPv6. El puerto UDP debe ser un valor numérico entre 0 y 65535. Generalmente, el puerto UDP para syslog es 514. Las direcciones deben escribirse entre paréntesis. Si se introducen varias direcciones, es necesario separarlas con un espacio.



 a| 
`addServerAddresses`
 a| 
Permite añadir una o varias direcciones de servidor de syslog con números de puerto asociados. Cuando se usa esta opción, no se borran las direcciones de servidor existentes. Esta dirección de servidor de syslog puede ser un nombre de dominio completo, una dirección IPv4 o una dirección IPv6. El puerto UDP debe ser un valor numérico entre 0 y 65535. Generalmente, el puerto UDP para syslog es 514. Las direcciones deben escribirse entre paréntesis. Si se introducen varias direcciones, es necesario separarlas con un espacio.

|===


== Ejemplos

[listing]
----

SMcli -n Array1 -c "set syslog serverAddresses=("ICTM1402S02H2.company.com:22");"

SMcli -n Array1 -c "set syslog addServerAddresses=("serverName1.company.com:514"
"serverName2.company.com:514");"

SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40

11.70.1 añadió el `syslogFormat` Parámetro para especificar el formato del mensaje de syslog.
