---
permalink: commands-a-z/set-snmpcommunity.html 
sidebar: sidebar 
keywords: update, snmp, community 
summary: 'El comando set snmpCommunity crea un nombre nuevo para una comunidad de protocolo simple de gestión de redes (SNMP) existente.' 
---
= Actualice la comunidad SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `set snmpCommunity` El comando crea un nuevo nombre para una comunidad de protocolo simple de gestión de redes (SNMP) existente.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o administrador de soporte.



== Sintaxis

[listing, subs="+macros"]
----
set snmpCommunity communityName=pass:quotes["_snmpCommunityName_"]
newCommunityName=pass:quotes["_newSnmpCommunityName_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`communityName`
 a| 
El nombre de la comunidad SNMP existente que se desea cambiar. El nombre de la comunidad SNMP se debe escribir entre comillas dobles (" ").



 a| 
`newCommunityName`
 a| 
El nombre nuevo que se desea asignar a la comunidad SNMP. El nombre de la comunidad SNMP se debe escribir entre comillas dobles (" ").

|===


== Nivel de firmware mínimo

8.30
