---
permalink: commands-a-z/set-snapvolume.html 
sidebar: sidebar 
keywords: rename, snapshot, volume 
summary: El comando set snapVolume cambia el nombre de un volumen Snapshot existente. 
---
= Cambiar el nombre del volumen de instantáneas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set snapVolume` el comando cambia el nombre de un volumen snapshot existente.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] userLabel=pass:quotes["_snapImageVolumeName_"]
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`snapVolume`
 a| 
Nombre del volumen Snapshot que se desea cambiar. El nombre del volumen Snapshot debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`userLabel`
 a| 
Nombre nuevo que se le desea otorgar al volumen Snapshot. El nombre nuevo del volumen Snapshot debe escribirse entre comillas dobles (" ").

|===


[[notes]]
== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83
