---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: El comando set storageArray controllerHealthImageAllowOverWrite establece una Marca en una cabina de almacenamiento para permitir que la imagen de estado de una nueva controladora sobrescriba la imagen de estado de una controladora existente en cabinas de almacenamiento que admiten la función de imagen de estado de controladora. 
---
= Establecer la imagen del estado del controlador de la matriz de almacenamiento para permitir la sobrescritura - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray controllerHealthImageAllowOverWrite` el comando configura una marca en la controladora para permitir que una imagen de estado de controladora nueva sobrescriba una imagen de estado de controladora existente en cabinas de almacenamiento que admiten la función de imágenes de estado.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Si la cabina de almacenamiento no es compatible con la función de imagen de estado de controladora, el comando devuelve un error.

[NOTE]
====
Con la versión de firmware 8.20 `coreDumpAllowOverWrite` el parámetro se sustituye por el `controllerHealthImageAllowOverWrite` parámetro.

====


[[syntax]]
== Sintaxis

[source, cli]
----
set storageArray controllerHealthImageAllowOverWrite
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Cuando se recupera la imagen de estado de la controladora, la `allow overwrite` se ha establecido el indicador. Si no se recupera la imagen de estado de la controladora, la imagen caduca en 48 horas, después del cual `allow overwrite` se ha establecido el indicador. Cuando utilice la `set storageArray controllerHealthImageAllowOverWrite` para establecer el `allow overwrite` indicador, la expiración de 48 horas se renuncia como si la imagen se hubiera recuperado.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.86

8.20 sustituye la `*coreDumpAllowOverWrite*` con el `controllerHealthImageAllowOverWrite` parámetro.
