---
permalink: commands-a-z/set-hostport.html 
sidebar: sidebar 
keywords: set, host, port 
summary: El comando set hostPort cambia las propiedades de un puerto de host. 
---
= Configure el puerto de host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set hostPort` comando cambia las propiedades de un puerto de host.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

[NOTE]
====
Este comando no funciona en un entorno iSCSI, donde los puertos de host se consideran iniciadores. En su lugar, utilice la `set iscsiInitiator` comando. Consulte xref:set-iscsiinitiator.adoc[Configure el iniciador de iSCSI].

====


== Sintaxis

[source, cli, subs="+macros"]
----
set hostPort pass:quotes[[_portLabel_]] userLabel=pass:quotes[_newPortLabel_]
[host=pass:quotes[_hostName_]]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`hostPort`
 a| 
El nombre del puerto de host para el que desea cambiar el tipo de host, o para el que desea crear un nombre nuevo. El nombre del puerto de host debe escribirse entre corchetes ([ ]). Si el nombre del puerto de host tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`userLabel`
 a| 
El nombre nuevo que desea asignarle al puerto de host. Escriba el nuevo nombre del puerto de host entre comillas dobles (" ").



 a| 
`host`
 a| 
El nombre del host para el cual se define un puerto de host de HBA o HCA. El nombre de host debe escribirse entre comillas dobles (" ").

|===


== Notas

En la etiqueta de usuario, se puede usar cualquier combinación de caracteres alfanuméricos, guiones y guiones bajos. Las etiquetas de usuario pueden tener hasta 30 caracteres.



== Nivel de firmware mínimo

6.10
