---
permalink: commands-a-z/set-storagearray-externalkeymanagement.html 
sidebar: sidebar 
keywords: set, external, key, management, set 
summary: El comando set storageArray externalKeyManagement configura el número de puerto y la dirección del servidor de gestión de claves externo. 
---
= Establecer la configuración de administración de claves externas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `set storageArray externalKeyManagement` el comando configura la dirección del servidor de gestión de claves externo y el número de puertos.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[context]]
== Contexto

[NOTE]
====
Este comando se aplica solo a la gestión de claves externas.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
set storageArray externalKeyManagement serverAddress=pass:quotes[_serverAddress_]
serverPort=pass:quotes[_portNumber_]
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`serverAddress`
 a| 
Permite especificar la dirección del servidor de gestión de claves externo. La dirección del servidor debe ser un nombre de dominio completo, una dirección IPv4 o una dirección IPv6.



 a| 
`serverPort`
 a| 
Permite especificar el número de puerto del servidor de gestión de claves externo.

|===


[[example]]
== Ejemplo

[listing]
----
SMcli -n Array1 -c "set storageArray externalKeyManagement serverAddress=192.0.2.1 serverPort=8081;"

   SMcli completed successfully.
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40
