---
permalink: commands-a-z/show-volumegroup-importdependencies.html 
sidebar: sidebar 
keywords: show, volume, group, import, dependencies 
summary: El comando show volumeGroup Dependencies muestra una lista de dependencias de las unidades de un grupo de volúmenes que se desea transferir desde una cabina de almacenamiento hacia una segunda cabina de almacenamiento. 
---
= Mostrar dependencias de importación de grupos de volúmenes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show volumeGroup importDependencies` el comando muestra una lista de dependencias de las unidades de un grupo de volúmenes que se desea mover de una cabina de almacenamiento a una segunda cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] importDependencies
[cancelImport=(TRUE | FALSE)]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volumeGroup`
 a| 
El nombre del grupo de volúmenes del cual se desean ver las dependencias para importar. El nombre del grupo de volúmenes debe escribirse entre corchetes ([ ]).



 a| 
`cancelImport`
 a| 
La configuración para reducir la velocidad de giro de las unidades después de que se leyeron las dependencias del grupo de volúmenes. Para reducir la velocidad de giro de las unidades, configure este parámetro en `TRUE`. Para mantener girando las unidades, configure este parámetro en `FALSE`.

|===


== Notas

Este comando muestra las dependencias de un grupo de volúmenes específico y, para ello, debe estar en el estado exportado o forzado. Si se toma una decisión de conservar las dependencias de la lista, entonces el `cancelImport` se puede aplicar el parámetro para reducir la velocidad de giro de las unidades.

Debe ejecutar el `show volumeGroup importDependencies` antes de ejecutar el `start volumeGroup import` comando.



== Nivel de firmware mínimo

7.10
