---
permalink: commands-a-z/show-storagearray-autosupport.html 
sidebar: sidebar 
keywords: show, autosupport, configuration, e2800, e5700, storage, arrays 
summary: El comando show storageArray AutoSupport muestra la configuración de recogida de bundle de AutoSupport de la cabina de almacenamiento. 
---
= Muestra la configuración de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray autoSupport` Comando muestra la configuración de recogida de bundle de AutoSupport de la cabina de almacenamiento.



== Cabinas compatibles

Este comando resulta operativo para las cabinas de almacenamiento E4000, E2800, E5700, EF600 y EF300.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento, administrador de soporte o supervisor de almacenamiento.



== Contexto

El resultado de este comando muestra la siguiente información sobre la configuración:

* El estado de activación en este dominio de gestión de la función AutoSupport, la función AutoSupport OnDemand y la función AutoSupport Remote Diagnostics
* Parámetros de entrega que dependen del método de entrega configurado:
+
** El método de entrega es por correo electrónico (SMTP): Se muestran la dirección de correo electrónico de destino, el servidor de retransmisión de correo y la dirección de correo electrónico del remitente
** Cuando el método de entrega es HTTP o HTTPS:
+
*** Conexión directa: Se muestra la dirección IP de destino
*** Conexión por servidor del proxy: Se muestran la dirección del host, el número de puerto y los detalles de autenticación
*** Conexión por script de configuración automática de proxy (PAC): Se muestra la ubicación del script




* Rangos de tiempo diarios y semanales preferidos de AutoSupport
* Información acerca de las funcionalidades ASUP, el número de serie del chasis y las programaciones diarias y semanales configuradas




== Sintaxis

[source, cli]
----
show storageArray autoSupport
----


== Parámetros

Ninguno.



=== Ejemplos

[listing]
----

  SMcli -n Array1 -c "show storageArray autoSupport;"

   The AutoSupport feature is enabled on this storage array.
   The AutoSupport OnDemand feature is enabled on this storage array.
   The AutoSupport Remote Diagnostics feature is enabled on this storage array.

  Delivery Method: Email (SMTP)
    Destination email address: autosupport@netapp.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: Email (SMTP)
    Destination email address: destination1@example.com, destination2@example.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: 52428800

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: Unlimited

   The AutoSupport daily schedule preferred time range is from 12:00 AM to 01:00 AM.
   The AutoSupport weekly schedule preferred time range is from 10:00 PM to 11:00 PM on Thursday, Saturday.

   AutoSupport Capable  AutoSupport OnDemand Capable  Chassis Serial Number  Daily Schedule  Weekly Schedule
   Yes (enabled)        Yes                           SX94500434             12:55 AM        10:08 PM on Thursdays

   SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40
