---
permalink: commands-a-z/show-emailalert-summary.html 
sidebar: sidebar 
keywords: show, email, alert, configuration 
summary: El comando show emailAlert summary muestra información acerca de la configuración de alertas de correo electrónico. 
---
= Mostrar configuración de alertas de correo electrónico - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show emailAlert summary` comando muestra la información de configuración de alertas de correo electrónico.



== Cabinas compatibles

Este comando se aplica a una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300 individual. No funciona en cabinas de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento, administrador de soporte o supervisor de almacenamiento.



== Sintaxis

[source, cli]
----
show emailAlert summary
----


== Parámetros

Ninguno.



== Ejemplos

[listing]
----

SMcli -n Array1 -c "show emailAlert summary;"

EMAIL ALERT SETTINGS
   Mail server address: email@company.com
   Mail server encryption: starttls
   Mail server port: 587
   Mail server user name: accountName
   Mail server password: secret123
   Email sender address: no-reply@company.com
   Recipient Email
      recipient@company.com
      recipient-two@company.com

SMcli completed successfully.
----


== Nivel de firmware mínimo

8.40

11.70.01 se han agregado parámetros que especifican el cifrado SMTP (none, SMTPS, STARTTLS), el puerto SMTP y las credenciales SMTP (nombre de usuario y contraseña).
