---
permalink: commands-a-z/show-volumecopy-sourcecandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, source, candidates 
summary: El comando show VolumeCopy sourceCandidates muestra información acerca de los volúmenes de candidatos que se pueden usar como origen de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot. 
---
= Mostrar candidatos a fuentes de copia de volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show volumeCopy sourceCandidates` el comando muestra información acerca de los volúmenes candidatos que pueden usarse como origen de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



[[syntax]]
== Sintaxis

[source, cli]
----
show volumeCopy sourceCandidates
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Este comando muestra información acerca del origen de una copia de volumen, como se observa en el siguiente ejemplo:

[listing]
----
Volume Name: finance
   Capacity: 4.0 GB
   Volume Group: 1
Volume Name: engineering
   Capacity: 4.0 GB
   Volume Group: 2
----