---
permalink: commands-a-z/show-storagearray-controllerhealthimage.html 
sidebar: sidebar 
keywords: show, storage, array, controller, health, image 
summary: El comando show storageArray controllerHealthImage muestra detalles de la imagen de estado de la controladora en la caché de la controladora si existe una imagen de estado de la controladora disponible, en las cabinas de almacenamiento compatibles con la imagen de estado de la controladora. 
---
= Mostrar la imagen del estado del controlador de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray controllerHealthImage` el comando muestra detalles de la imagen de estado de la controladora en la caché de la controladora, si hay una imagen de estado de controladora disponible, en las cabinas de almacenamiento que admiten la imagen de estado de controladora.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



[[context]]
== Contexto

[NOTE]
====
Con la versión de firmware 8.20 `coreDump` el parámetro se sustituye por el `controllerHealthImage` parámetro.

====
Si la cabina de almacenamiento no admite la función Controller health image, este comando muestra un error.



[[syntax]]
== Sintaxis

[source, cli]
----
show storageArray controllerHealthImage
----


[[parameters]]
== Parámetros

Ninguno.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83

8.20 sustituye la `coreDump` con el `controllerHealthImage` parámetro.
