---
permalink: commands-a-z/show-volumegroup.html 
sidebar: sidebar 
keywords: show, volume, group 
summary: El comando show volumeGroup muestra información acerca de un grupo de volúmenes. 
---
= Mostrar grupo de volúmenes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show volumeGroup` el comando muestra información acerca de un grupo de volúmenes.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



[[context]]
== Contexto

Este comando muestra la siguiente información acerca de un grupo de volúmenes.

* El estado (como Optimal, degraded, Failed, Missing).
* La capacidad
* El propietario actual (la controladora de la ranura A o la controladora de la ranura B ).
* Nivel de RAID
* El tipo de medio de la unidad (HDD o SSD).
* El tipo de interfaz de la unidad (Fibre Channel, iSCSI, InfiniBand, SAS).
* Protección contra pérdida de soporte (sí o no).
* Secure capable: Indica si el grupo de volúmenes se compone de todas las unidades compatibles con la función de seguridad. Las unidades compatibles con esta función pueden ser unidades FDE o FIPS.
* Secure: Indica si el grupo de volúmenes tiene la seguridad de la unidad activada (a esto se denomina función de seguridad habilitada).
* Los volúmenes y la capacidad libre relacionados
* Las unidades relacionadas
* Funcionalidades de garantía de datos y presencia de volúmenes con garantía de datos habilitada
* Funcionalidades de aprovisionamiento de recursos




[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volumeGroup`
 a| 
El nombre del grupo de volúmenes del cual se desea ver información. El nombre del grupo de volúmenes debe escribirse entre corchetes ([ ]).

|===


[[notes]]
== Notas

Este comando muestra información acerca del grupo de volúmenes, como se observa en el siguiente ejemplo:

[listing]
----
Name:              SecureGroup

      Status:         Optimal
      Capacity:       120.000 GB
      Current owner: Controller in slot A

      Quality of Service (QoS) Attributes

         RAID level:                  5
         Drive media type:            Hard Disk Drive
         Drive interface type:        SAS
         Shelf loss protection:       No
         Secure Capable:              Yes
         Secure:                      No
         Data Assurance (DA) capable: Yes
         DA enabled volume present:   No
         Resource-provisioned:           Yes


      Total Volumes:          1
         Standard volumes:    1
         Repository volumes:  0
         Free Capacity:       110.000 GB

      Associated drives - present (in piece order)
      Total drives present: 5

         Tray     Slot
         99       1
         99       2
         99       3
         99       4
         99       5
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
