---
permalink: commands-a-z/show-storagearray-powerinfo.html 
sidebar: sidebar 
keywords: show, storage, array, power, information 
summary: El comando show storageArray powerInfo muestra información acerca de la cantidad de alimentación que consume toda la cabina de almacenamiento y cada soporte de la cabina de almacenamiento. 
---
= Mostrar información de energía de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray powerInfo` el comando muestra información acerca de la cantidad de alimentación que consume toda la cabina de almacenamiento y cada soporte de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



== Sintaxis

[source, cli]
----
show storageArray powerInfo
----


== Parámetros

Ninguno.



== Notas

Este comando muestra información de un consumo de alimentación que se asemeja a este ejemplo.

[listing]
----
total power drawn: 310 watts
number of trays: 1
tray power input details:
   tray id  power supply serial number  input power
   0        0                           160 watts
   0        1                           150 watts
----


== Nivel de firmware mínimo

8.10
