---
permalink: commands-a-z/show-volumecopy-source-targetcandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, target, candidates 
summary: El comando show VolumeCopy source targetCandidates muestra información acerca de los volúmenes candidatos que es posible usar como objetivo de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot. 
---
= Mostrar candidatos a objetivos de copia de volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show volumeCopy source targetCandidates` el comando muestra información acerca de los volúmenes candidatos que pueden usarse como objetivo de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



== Sintaxis

[source, cli, subs="+macros"]
----
show volumeCopy source pass:quotes[["_sourceName_"]] targetCandidates
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`source`
 a| 
El nombre del volumen de origen para el cual se intenta encontrar un volumen objetivo candidato. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen tiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===