---
permalink: commands-a-z/show-asyncmirrorgroup-summary.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, groups 
summary: El comando show asyncMirrorGroup summary muestra información de configuración de uno o más grupos de reflejos asíncronos. 
---
= Muestra grupos de reflejos asíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `show asyncMirrorGroup summary` el comando muestra información de configuración de uno o más grupos de reflejos asíncronos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800 y E5700, Siempre que se hayan instalado todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800 o E5700, se deben poseer los roles Storage Admin.



== Contexto

Este comando también muestra las parejas reflejadas asíncronas asociadas a cada grupo de reflejos asíncronos, incluidas las parejas reflejadas asíncronas incompletas.

También es posible usar este comando para mostrar el progreso de la sincronización de datos periódica en todas las parejas reflejadas dentro del grupo de reflejos asíncronos.



== Sintaxis

[listing, subs="+macros"]
----
show (allAsyncMirrorGroups |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_asyncMirrorGroupName1_ ... _asyncMirrorGroupNameN_]])
[summary]
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allAsyncMirrorGroups`
 a| 
Este parámetro permite mostrar las propiedades de todos los grupos de reflejos asíncronos.



 a| 
`asyncMirrorGroup`
 a| 
El nombre de un grupo de reflejos asíncronos para el cual se desea mostrar información de configuración y el progreso de la sincronización de datos periódica. El nombre del grupo de reflejos asíncronos debe escribirse entre corchetes ([ ]). Si el nombre del grupo de reflejos asíncronos contiene números o caracteres especiales, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`asyncMirrorGroups`
 a| 
Los nombres de varios grupos de reflejos asíncronos para los cuales se desea recuperar información. Para introducir los nombres de los grupos de reflejos asíncronos, se deben respetar las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Los nombres deben estar separados por un espacio.


Si los nombres de los grupos de reflejos asíncronos tienen caracteres especiales o números, se deben introducir de acuerdo con las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.




 a| 
`summary`
 a| 
Este parámetro muestra una lista concisa de información sobre el progreso de sincronización de uno o más grupos de reflejos asíncronos.

|===


== Nivel de firmware mínimo

7.84
