---
permalink: commands-a-z/show-storagearray-cachemirrordataassurancecheckenable.html 
sidebar: sidebar 
keywords: show, storage, array, cache, mirror, data, assurance, check, enable 
summary: El comando show storageArray cacheMirrorDataAssuranceCheckEnable devuelve el estado de preparación de la función de comprobación de garantía de datos de reflejo de la caché. 
---
= Muestre el estado de comprobación de garantía de datos de reflejo de la caché de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray cacheMirrorDataAssuranceCheckEnable` el comando devuelve el estado de preparación de la función verificación de garantía de datos de reflejo de la caché.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Sintaxis

[source, cli]
----
show storageArray cacheMirrorDataAssuranceCheckEnable
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

8.41 Nuevo parámetro de comando.
