---
permalink: commands-a-z/show-replaceabledrives.html 
sidebar: sidebar 
keywords: show, replaceable, drives 
summary: El comando show replaceableDrives muestra todas las unidades reemplazables de una cabina de almacenamiento. 
---
= Mostrar unidades reemplazables - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show replaceableDrives` el comando muestra todas las unidades reemplazables de una cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Este comando muestra la siguiente información de cada unidad reemplazable de la cabina de almacenamiento:

* La ubicación del soporte y de la ranura
* El nombre del grupo de volúmenes al que pertenece la unidad
* El nombre a nivel mundial (WWN);
* El estado de la unidad




[[syntax]]
== Sintaxis

[source, cli]
----
show replaceableDrives
----


[[example-output]]
== Resultado de ejemplo

[listing]
----
Replaceable drive at Tray 0, Slot 3
                Volume group: 2
                World-wide name: 5000c50028785aff0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 23
                Volume group: 2
                World-wide name: 5000c500095d46df0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 24
                Volume group: 2
                World-wide name: 5000c500287854d70000000000000000
                Status: Removed
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.10
