---
permalink: commands-a-z/show-snapvolume.html 
sidebar: sidebar 
keywords: show, snapshot, volumes 
summary: El comando show snapVolume muestra información acerca de uno o varios volúmenes Snapshot. 
---
= Mostrar volúmenes de instantáneas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show snapVolume` el comando muestra información acerca de uno o varios volúmenes snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Sintaxis

[source, cli, subs="+macros"]
----
show (allSnapVolumes | snapVolume pass:quotes[["_snapVolumeName_"]] |
snapVolumes pass:quotes[["_snapVolumeName1_" ... "_snapVolumeNamen_"]])
[summary]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allSnapVolumes`
 a| 
El parámetro que muestra información acerca de todos los volúmenes Snapshot de la cabina de almacenamiento.



 a| 
`snapVolume`
 a| 
El nombre de un volumen Snapshot del cual se desea recuperar información. El nombre del volumen Snapshot debe escribirse entre comillas dobles (" ") dentro de corchetes ([ ]).



 a| 
`snapVolumes`
 a| 
Los nombres de varios volúmenes Snapshot de los cuales se desea recuperar información. Para introducir los nombres de los volúmenes Snapshot, se deben respetar las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.




 a| 
`summary`
 a| 
El parámetro muestra una lista concisa de información acerca de los volúmenes Snapshot.

|===


== Notas

Puede utilizar cualquier combinación de caracteres alfanuméricos, subrayado (_), guión (-) y almohadilla (#) para los nombres. Los nombres pueden tener hasta 30 caracteres.

Este comando muestra información acerca del volumen Snapshot, como se observa en el siguiente ejemplo:

[listing]
----
SNAPSHOT VOLUME (SNAPSHOT-IMAGE BASED) SUMMARY
----
[listing]
----
SUMMARY

 Total Snapshot Volumes: 1
   Most Recent Snapshot Volume: Day month date hh:mm:ss yyyy
   Status: 1 Optimal, 0 Non Optimal

   Name        Type       Status     Capacity    Associated Base Volume
   2_SV_0001   Standard   Optimal    3.000 GB    2
----
[listing]
----
   Snapshot Volume Timestamp   Snapshot Image Timestamp    Mode
   1/23/12 6:44:31 PM IST      1/23/12 6:27:36 PM IST      Read Write
----
[listing]
----
   Total Repository Capacity   Available Repository Capacity
   1.199 GB                    0.125 MB (0%)
----
El tamaño del monitor determina la manera en la que la información se resume y aparece.



== Nivel de firmware mínimo

7.83
