---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: El comando show storageArray iscsiNegotiationDefaults muestra información acerca de la configuración a nivel de la conexión que está sujeta a la negociación iniciador-objetivo. 
---
= Mostrar valores predeterminados de negociación de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `show storageArray iscsiNegotiationDefaults` comando muestra información acerca de la configuración a nivel de la conexión sujeta a la negociación iniciador-objetivo.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Sintaxis

[listing]
----
show storageArray iscsiNegotiationDefaults
----


== Parámetros

Ninguno.



== Notas

La información que se muestra incluye la configuración predeterminada del soporte de la controladora (es decir, la configuración que es el punto inicial de la negociación) y la configuración activa actual.



== Nivel de firmware mínimo

7.10
