---
permalink: commands-a-z/show-replaceabledrives.html 
sidebar: sidebar 
keywords: show, replaceable, drives 
summary: El comando show replaceableDrives muestra todas las unidades reemplazables de una cabina de almacenamiento. 
---
= Muestra las unidades reemplazables
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show replaceableDrives` el comando muestra todas las unidades reemplazables de una cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Este comando muestra la siguiente información de cada unidad reemplazable de la cabina de almacenamiento:

* La ubicación del soporte y de la ranura
* El nombre del grupo de volúmenes al que pertenece la unidad
* El nombre a nivel mundial (WWN);
* El estado de la unidad




== Sintaxis

[source, cli]
----
show replaceableDrives
----


== Resultado de ejemplo

[listing]
----
Replaceable drive at Tray 0, Slot 3
                Volume group: 2
                World-wide name: 5000c50028785aff0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 23
                Volume group: 2
                World-wide name: 5000c500095d46df0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 24
                Volume group: 2
                World-wide name: 5000c500287854d70000000000000000
                Status: Removed
----


== Nivel de firmware mínimo

7.10
