---
permalink: commands-a-z/show-snmpsystemvariables.html 
sidebar: sidebar 
keywords: show, snmp, mib ii, system, group, variables 
summary: 'El comando show snmpSystemVariables muestra información acerca de las variables del sistema del protocolo SNMP. Las variables del sistema se conservan en una base de datos de información de gestión II (MIB-II).' 
---
= Mostrar variables del grupo del sistema SNMP MIB II - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show snmpSystemVariables` Comando muestra información acerca de las variables del sistema del protocolo simple de gestión de redes (SNMP). Las variables del sistema se conservan en una base de datos de información de gestión II (MIB-II).



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Storage Admin o Support Admin o Storage Monitor.



[[syntax]]
== Sintaxis

[source, cli]
----
show snmpSystemVariables
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Este comando muestra información de variables del sistema SNMP que se asemeja al siguiente ejemplo.

[listing]
----
SYSTEM VARIABLES
    Sys Name: NONE
    Sys Contact: NONE
    Sys Location: NONE
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.30
