---
permalink: commands-a-z/show-volumecopy-sourcecandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, source, candidates 
summary: El comando show VolumeCopy sourceCandidates muestra información acerca de los volúmenes de candidatos que se pueden usar como origen de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot. 
---
= Mostrar candidatos de origen de copia de volumen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `show volumeCopy sourceCandidates` el comando muestra información acerca de los volúmenes candidatos que pueden usarse como origen de una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Sintaxis

[listing]
----
show volumeCopy sourceCandidates
----


== Parámetros

Ninguno.



== Notas

Este comando muestra información acerca del origen de una copia de volumen, como se observa en el siguiente ejemplo:

[listing]
----
Volume Name: finance
   Capacity: 4.0 GB
   Volume Group: 1
Volume Name: engineering
   Capacity: 4.0 GB
   Volume Group: 2
----