---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: El comando show storageArray unconfiguredIscsiInitiators muestra una lista de iniciadores que detectó la cabina de almacenamiento, pero que todavía no se configuraron en la topología de la cabina de almacenamiento. 
---
= Mostrar iniciadores iSCSI no configurados de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray unconfiguredIscsiInitiators` el comando muestra una lista de iniciadores detectados por la cabina de almacenamiento que todavía no se configuraron en la topología de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.

Este comando queda obsoleto. El comando que lo reemplaza es link:show-storagearray-unconfiguredinitiators.html["Show storageArray unconfiguredInitiators"].



== Sintaxis

[source, cli]
----
show storageArray unconfiguredIscsiInitiators
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

7.10

este comando queda obsoleto en la versión 8.50.
