---
permalink: commands-a-z/show-storagearray-odxsetting.html 
sidebar: sidebar 
keywords: show, storage, array, odx, set 
summary: 'El comando show storageArray odxsetting muestra la configuración actual de la transferencia de datos descargados (ODX) y la arquitectura de cabinas de VMware vStorage API (VAAI) de la cabina de almacenamiento.' 
---
= Mostrar la configuración ODX de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray odxsetting` El comando muestra la configuración actual de la transferencia de datos descargados (ODX) y la arquitectura de cabinas de VMware vStorage API (VAAI) de la cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



[[context]]
== Contexto

La configuración de este comando puede ser alguna de las siguientes opciones:

* True -- ODX y VAAI están activados.
* False -- ODX y VAAI están desactivados.
* Inconsistent -- las controladoras no tienen la misma configuración.
* Unknown: No se puede determinar la configuración de ODX ni VAAI.




[[syntax]]
== Sintaxis

[source, cli]
----
show storageArray odxsetting
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Este comando muestra información de ODX y VAAI que se asemeja al siguiente ejemplo.

[listing]
----
Windows ODX Setting Status
odxEnabled  True | False | Inconsistent | Unknown
vaaiEnabled True | False | Inconsistent | Unknown
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.20
