---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: El comando show storageArray iscsiNegotiationDefaults muestra información acerca de la configuración a nivel de la conexión que está sujeta a la negociación iniciador-objetivo. 
---
= Mostrar valores predeterminados de negociación de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray iscsiNegotiationDefaults` comando muestra información acerca de la configuración a nivel de la conexión sujeta a la negociación iniciador-objetivo.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.



== Sintaxis

[source, cli]
----
show storageArray iscsiNegotiationDefaults
----


== Parámetros

Ninguno.



== Notas

La información que se muestra incluye la configuración predeterminada del soporte de la controladora (es decir, la configuración que es el punto inicial de la negociación) y la configuración activa actual.



== Nivel de firmware mínimo

7.10
