---
permalink: commands-a-z/show-storagearray-unconfiguredinitiators.html 
sidebar: sidebar 
keywords: show, unconfigured, initiators 
summary: El comando show storageArray unconfiguredInitiators muestra una lista de iniciadores que detectó la cabina de almacenamiento, pero que todavía no se configuraron en la topología de la cabina de almacenamiento. 
---
= Mostrar iniciadores no configurados - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray unconfiguredInitiators` el comando muestra una lista de iniciadores detectados por la cabina de almacenamiento que todavía no se configuraron en la topología de la cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin o Storage Monitor.

Este comando sustituye a link:show-storagearray-unconfigurediscsiinitiators.html["Show storageArray unconfiguredIscsiInitiators"] comando.



[[syntax]]
== Sintaxis

[source, cli]
----
show storageArray unconfiguredInitiators
----


[[parameters]]
== Parámetros

Ninguno.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.50
