---
permalink: commands-a-z/show-alldrives-performancestats.html 
sidebar: sidebar 
keywords: show, drive, performance, statistics 
summary: El comando show allDrives performanceStats muestra información acerca del rendimiento de la unidad. 
---
= Mostrar estadísticas de rendimiento de la unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show allDrives performanceStats` el comando muestra información acerca del rendimiento de la unidad.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Este comando muestra la siguiente información de cada unidad de la cabina de almacenamiento:

* La cabina de almacenamiento que contiene la unidad o las unidades
* La latencia de I/o actual
* La latencia de I/o máxima
* La latencia de I/o mínima
* La latencia de I/o promedio




== Sintaxis

[source, cli, subs="+macros"]
----
show (allDrives |drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]) performanceStats
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allDrives`
 a| 
La configuración que muestra información acerca de todas las unidades de la cabina de almacenamiento.



 a| 
`drive` o. `drives`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

|===


== Notas

La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.

La `show drive performanceStats` el comando muestra las estadísticas de rendimiento de la unidad, como se observa en el siguiente ejemplo:

[listing]
----
"Performance Monitor Statistics for Storage Array: remote_pp -
Date/Time: 10/23/12 3:47:27 PM -
Polling interval in seconds: 5"

"Objects","Current IO Latency","Maximum IO Latency","Minimum IO Latency",
"Average IO Latency"

"Capture Iteration: 1","","","",""
"Date/Time: 10/23/12 3:47:27 PM","","","",""
"Drive Tray 0, Slot 1","0.0","0.0","0.0","0.0"
----


== Nivel de firmware mínimo

7.86
