---
permalink: commands-a-z/show-storagearray-powerinfo.html 
sidebar: sidebar 
keywords: show, storage, array, power, information 
summary: El comando show storageArray powerInfo muestra información acerca de la cantidad de alimentación que consume toda la cabina de almacenamiento y cada soporte de la cabina de almacenamiento. 
---
= Muestra información de alimentación de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show storageArray powerInfo` el comando muestra información acerca de la cantidad de alimentación que consume toda la cabina de almacenamiento y cada soporte de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Sintaxis

[source, cli]
----
show storageArray powerInfo
----


== Parámetros

Ninguno.



== Notas

Este comando muestra información de un consumo de alimentación que se asemeja a este ejemplo.

[listing]
----
total power drawn: 310 watts
number of trays: 1
tray power input details:
   tray id  power supply serial number  input power
   0        0                           160 watts
   0        1                           150 watts
----


== Nivel de firmware mínimo

8.10
