---
permalink: commands-a-z/show-volume-summary.html 
sidebar: sidebar 
keywords: show, volume 
summary: El comando show volume summary devuelve información acerca de un volumen. 
---
= Mostrar volumen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `show volume summary` el comando muestra información acerca de un volumen.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Contexto

Este comando devuelve la información siguiente sobre los volúmenes en una cabina de almacenamiento:

* El número de volúmenes
* El nombre
* El estado
* La capacidad
* Nivel de RAID
* El grupo de volúmenes en el que se encuentra el volumen
* Detalles
+
** El ID del volumen
** El ID del subsistema
** El tipo de unidad (SAS)
** Protección contra pérdida de soporte
** El propietario preferido
** El propietario actual
** El tamaño de segmento
** La prioridad de modificación
** El estado de la caché de lectura (habilitada o deshabilitada)
** El estado de la caché de escritura (habilitada o deshabilitada)
** El estado de la caché de escritura sin baterías (habilitada o deshabilitada)
** El estado de la caché de escritura con reflejo (habilitada o deshabilitada)
** El periodo posterior al vaciado de la caché de escritura
** La configuración de captura previa de lectura de la caché (TRUE o FALSE)
** El estado de habilitación del análisis de medios en segundo plano (habilitado o deshabilitado)
** El estado del análisis de medios con comprobación de redundancia (habilitado o deshabilitado)


* Los volúmenes del repositorio de reflejo




== Sintaxis

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`allVolumes`
 a| 
Este parámetro devuelve las estadísticas de rendimiento de todos los volúmenes de la cabina de almacenamiento.



 a| 
`volume`
 a| 
El nombre de un volumen del cual se desea recuperar información. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`volumes`
 a| 
Los nombres de varios volúmenes de los cuales se desea recuperar información. Los nombres de los volúmenes deben escribirse de acuerdo con estas reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Los nombres deben estar separados por un espacio.


Si los nombres de los volúmenes tienen caracteres especiales o números, se deben introducir de acuerdo con las siguientes reglas:

* Todos los nombres deben escribirse entre corchetes ([ ]).
* Cada nombre debe escribirse entre comillas dobles (" ").
* Los nombres deben estar separados por un espacio.




 a| 
`summary`
 a| 
El ajuste para la devolución de una lista concisa de información acerca de los volúmenes.

|===