---
permalink: commands-a-z/show-storagearray-controllerhealthimage.html 
sidebar: sidebar 
keywords: show, storage, array, controller, health, image 
summary: El comando show storageArray controllerHealthImage muestra detalles de la imagen de estado de la controladora en la caché de la controladora si existe una imagen de estado de la controladora disponible, en las cabinas de almacenamiento compatibles con la imagen de estado de la controladora. 
---
= Mostrar imagen de estado de controladora de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `show storageArray controllerHealthImage` el comando muestra detalles de la imagen de estado de la controladora en la caché de la controladora, si hay una imagen de estado de controladora disponible, en las cabinas de almacenamiento que admiten la imagen de estado de controladora.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con los roles de administrador de almacenamiento o supervisor de almacenamiento.



== Contexto

[NOTE]
====
Con la versión de firmware 8.20 `coreDump` el parámetro se sustituye por el `controllerHealthImage` parámetro.

====
Si la cabina de almacenamiento no admite la función Controller health image, este comando muestra un error.



== Sintaxis

[listing]
----
show storageArray controllerHealthImage
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

7.83

8.20 sustituye la `coreDump` con el `controllerHealthImage` parámetro.
