---
permalink: commands-a-z/show-alldrives-downloadprogress.html 
sidebar: sidebar 
keywords: show, drive, download, progress 
summary: El comando show allDrives downloadProgress muestra el estado de las descargas de firmware de las unidades destinadas al comando download drive firmware o el comando download storageArray driveFirmware. 
---
= Muestra progreso de descarga de la unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `show allDrives downloadProgress` el comando muestra el estado de las descargas de firmware de las unidades objetivo del `download drive firmware` o el `download storageArray driveFirmware` comando.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli]
----
show allDrives downloadProgress
----


== Parámetros

Ninguno.



== Notas

Una vez que finalizan todas las descargas de firmware, este comando muestra el estado "good". Si se produce un error en las descargas de firmware, el comando muestra el estado de la descarga de firmware de cada unidad objetivo. Este comando muestra los Estados que se observan en esta tabla.

[cols="2*"]
|===
| Estado | Definición 


 a| 
`Successful`
 a| 
Las descargas finalizaron sin errores.



 a| 
`Not Attempted`
 a| 
Las descargas no comenzaron.



 a| 
`Partial Download`
 a| 
Se están ejecutando las descargas.



 a| 
`Failed`
 a| 
Las descargas finalizaron con errores.

|===


== Nivel de firmware mínimo

6.10
