---
permalink: commands-a-z/smcli-enable-disable-autosupportondemand.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, ondemand, feature, emw, management, domain, level, smcli 
summary: El comando SMcli enable|disable autoSupportOnDemand activa o desactiva la función AutoSupport OnDemand. Con esta función, el soporte técnico puede coordinar la transmisión de datos de AutoSupport y podrá solicitar la retransmisión de los datos de soporte que faltan. 
---
= Habilitar o deshabilitar la función AutoSupport OnDemand en el nivel de dominio de administración de EMW (solo SMcli) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `SMcli enable|disable autoSupportOnDemand` El comando activa o desactiva la función AutoSupport OnDemand. Con esta función, el soporte técnico puede coordinar la transmisión de datos de AutoSupport y podrá solicitar la retransmisión de los datos de soporte que faltan.



== Cabinas compatibles

Este comando se aplica a todas las cabinas de almacenamiento E2700 y E5600 en el dominio de administración de manera simultánea. No se aplica a las cabinas de almacenamiento E4000, E2800 o E5700.



== Contexto

[NOTE]
====
Este es un comando de SMcli, no de script. Se debe ejecutar desde una línea de comandos. No es posible ejecutar este comando desde el editor de secuencia de comandos del software de administración del almacenamiento.

====
Antes de habilitar esta función, es necesario habilitar la función AutoSupport en el dominio de gestión. Una vez que se habilita esta función, es posible habilitar la función AutoSupport Remote Diagnostics (si se desea). La función AutoSupport Remote Diagnostics se habilita de forma predeterminada cuando se habilita la función AutoSupport OnDemand.



== Sintaxis

[source, cli]
----
SMcli enable|disable autoSupportOnDemand
----


== Parámetros

Ninguno.



== Verificación

Utilice la `SMcli -autoSupportConfig show` comando para ver si ha habilitado la función. Las dos líneas iniciales del resultado muestran el estado de habilitación de la función AutoSupport, seguido por la función AutoSupport OnDemand:

[listing]
----
The AutoSupport feature is activated on this storage management
station.
The AutoSupport OnDemand feature is activated on this storage
management station.
----


== Nivel de firmware mínimo

8.25
