---
permalink: commands-a-z/smcli-enable-autosupportfeature.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, emw, management, domain, level, smcli 
summary: 'El comando SMcli enable autoSupportFeature activa la función AutoSupport (ASUP) para todas las cabinas de almacenamiento gestionadas y permite transmitir mensajes al sitio de soporte técnico. Una vez que se habilita la función ASUP, todas las cabinas de almacenamiento compatibles con ASUP quedan preparadas automáticamente para recoger y enviar datos relacionados con soporte al soporte técnico. Estos datos pueden usarse para tareas remotas de solución y análisis de problemas.' 
---
= Habilitar o deshabilitar AutoSupport en el nivel de dominio de gestión de EMW (solo para SMcli)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `SMcli enable autoSupportFeature` Comando activa la función AutoSupport (ASUP) para todas las cabinas de almacenamiento gestionadas y permite transmitir mensajes al sitio de soporte técnico. Una vez que se habilita la función ASUP, todas las cabinas de almacenamiento compatibles con ASUP quedan preparadas automáticamente para recoger y enviar datos relacionados con soporte al soporte técnico. Estos datos pueden usarse para tareas remotas de solución y análisis de problemas.



== Cabinas compatibles

Este comando se aplica a todas las cabinas de almacenamiento E2700 y E5600 en el dominio de administración de manera simultánea. No se aplica a las cabinas de almacenamiento E2800 o E5700.



== Contexto

[NOTE]
====
Este es un comando de SMcli, no de script. Se debe ejecutar desde una línea de comandos. No es posible ejecutar este comando desde el editor de secuencia de comandos del software de administración del almacenamiento.

====
[NOTE]
====
La supervisión persistente debe estar habilitada para que se pueda usar la función AutoSupport.

====
[NOTE]
====
Nunca se transmiten datos sobre el cliente al sitio de soporte técnico.

====
Este comando afecta todas las cabinas de almacenamiento compatibles con ASUP en el dominio de gestión. Una vez que se habilita esta función para el dominio de gestión, es posible controlar la habilitación de la función para cada cabina de almacenamiento.

Después de habilitar esta función, es posible habilitar la función AutoSupport OnDemand (si se desea) y, luego, la función AutoSupport Remote Diagnostics (si se desea).

Es necesario habilitar estas tres funciones en el siguiente orden:

. *Activar AutoSupport*
. *Activar AutoSupport OnDemand*
. *Activar Diagnóstico remoto de AutoSupport*




== Sintaxis

[listing]
----
SMcli enable|disable autoSupportFeature
----


== Parámetros

Ninguno.



== Verificación

Utilice la `SMcli -autoSupportConfig show` comando para ver si ha habilitado la función. La línea inicial del resultado muestra el estado de habilitación:

[listing]
----
The AutoSupport feature is activated on this storage management station.
----


== Nivel de firmware mínimo

7.86
