---
permalink: commands-a-z/start-volumegroup-defragment.html 
sidebar: sidebar 
keywords: start, volume, group, defragment 
summary: El comando start volumeGroup defragment inicia una operación de desfragmentación en el grupo de volúmenes especificado. 
---
= Iniciar la desfragmentación del grupo de volúmenes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start volumeGroup defragment` el comando inicia una operación de desfragmentación en el grupo de volúmenes especificado.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

[NOTE]
====
La desfragmentación de un grupo de volúmenes inicia una operación prolongada que no se puede detener.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] defragment
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volumeGroup`
 a| 
El nombre del grupo de volúmenes que se desea desfragmentar. El nombre del grupo de volúmenes debe escribirse entre corchetes ([ ]).

|===


[[notes]]
== Notas

Los errores de I/o de host pueden dar como resultado grupos de volúmenes con más de 32 volúmenes. Es posible que esta operación también tenga como resultado reinicios internos de la controladora debido a que el tiempo de espera finaliza antes de que se configure la definición del grupo de volúmenes. Si tiene este problema, desactive las operaciones de I/o del host y vuelva a intentar ejecutar el comando.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
