---
permalink: commands-a-z/start-volumegroup-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, volume, group, resource, provision 
summary: El comando start volumeGroup resourceProvisioning permite el aprovisionamiento de recursos en un grupo de volúmenes determinado e inicia una operación asíncrona de habilitación de aprovisionamiento de recursos en cada volumen del grupo de volúmenes. El aprovisionamiento de recursos requiere que todas las unidades del grupo de volúmenes sean compatibles con la función DULBE de NVMe. 
---
= Iniciar el aprovisionamiento de recursos del grupo de volúmenes - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start volumeGroup resourceProvisioning` el comando habilita el aprovisionamiento de recursos en un grupo de volúmenes determinado e inicia una operación asíncrona de habilitación de aprovisionamiento de recursos en cada volumen del grupo de volúmenes. El aprovisionamiento de recursos requiere que todas las unidades del grupo de volúmenes sean compatibles con la función DULBE de NVMe.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas las matrices EF600, EF300, EF50 y EF80; siempre que estén instalados todos los paquetes SMcli.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento EF600, EF300, EF50 y EF80, debes tener los roles Storage Admin o Support Admin.



[[context]]
== Contexto

Para deshabilitar el aprovisionamiento de recursos en un grupo de volúmenes, se debe usar el comando de aprovisionamiento completo con la opción de deshabilitar el aprovisionamiento de recursos. Un grupo de volúmenes se aprovisionará de recursos cuando se cree si todas las unidades son compatibles con DULBE y las cabinas de almacenamiento `resourceProvisionedVolumes` el ajuste es `true`.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup[_volumeGroupName_]] resourceProvisioning
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volumeGroupName`
 a| 
El grupo de volúmenes que desea habilitar la función de aprovisionamiento de recursos. El nombre del grupo de volúmenes debe escribirse entre corchetes ([ ]).

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

11.73
