---
permalink: commands-a-z/start-storagearray-ocspresponderurl-test.html 
sidebar: sidebar 
keywords: start, ocsp, server, url, test 
summary: 'El comando start storageArray ocspResponderUrl test comprueba la existencia de una conexión abierta a la URL especificada del servidor de protocolo de estado de certificado en línea (OCSP).' 
---
= Iniciar prueba de URL del servidor OCSP - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start storageArray ocspResponderUrl test` El comando comprueba si hay una conexión abierta a la URL especificada del servidor de protocolo de estado de certificado en línea (OCSP).



== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`url`
 a| 
La cadena literal de la URL del servidor de OCSP.

[NOTE]
====
Si no se especifica una URL, el comando utiliza la URL de respuesta de OCSP que se encuentra en la configuración de revocación de certificados.

====
|===


== Sintaxis

[source, cli]
----
start storageArray ocspResponderUrl test (url=stringLiteral)
----


== Nivel de firmware mínimo

8.42
