---
permalink: commands-a-z/start-storagearray-externalkeymanagement-test.html 
sidebar: sidebar 
keywords: test, external key, management, communication 
summary: 'El comando start storageArray externalKeyManagement test utiliza las credenciales configuradas (certificados, dirección del servidor KMIP y número de puerto KMIP) para verificar que la cabina de almacenamiento pueda comunicarse con el servidor KMIP externo.' 
---
= Probar la comunicación de administración de claves externas - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start storageArray externalKeyManagement test` El comando utiliza las credenciales configuradas (certificados, dirección del servidor KMIP y número de puerto KMIP) para verificar que la cabina de almacenamiento pueda comunicarse con el servidor KMIP externo.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a una E4000, E2800, E5700, EF600, EF300, EF50 y EF80 de almacenamiento individual. No funciona en matrices de almacenamiento E2700 o E5600.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol de Security Admin.



[[context]]
== Contexto

[NOTE]
====
Este comando se aplica solo a la gestión de claves externas.

====


[[syntax]]
== Sintaxis

[source, cli]
----
start storageArray externalKeyManagement test
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

El siguiente ejemplo muestra la salida del comando cuando la matriz de almacenamiento puede comunicarse con el servidor externo de gestión de claves. La salida incluye el estado del servidor de gestión de claves, el certificado del cliente y el certificado del servidor.

[listing]
----
Key servers configured:
C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>SMcli.bat 10.115.XX.XXX -u admin -p infiniti -k -c "start storageArray externalKeyManagement test;"
Performing syntax check...

Syntax check complete.

Executing script...

SUMMARY:
   Key management server:
      Server address: ::
      Server port: 9003
      Local controller status: Connection failure
      Alternate controller status: Unknown
      Client certificate status: Ok
      Server certificate status: Ok

DETAILS:
Unable to communicate with the key management server. To correct the problem, perform the
following steps: 1) Check that the key management server address and port is correct. 2) If
the key management server's address is a domain name, check that both controller's DNS
servers are operational and reachable from the controller given your network configuration.
3) Check that the key management server operational and reachable from the controller given
your network configuration. 4) Once the problem has been found and corrected, re-perform the
communication test between the storage array and key management server to clear the needs
attention state on the array.


Script execution complete.

SMcli completed successfully.

C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>


No key servers configured:
C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>SMcli.bat 10.115.XX.XXX -u admin -p infiniti -k -c "start storageArray externalKeyManagement test;"
Performing syntax check...

Syntax check complete.

Executing script...

No key management servers configured.

Script execution complete.

SMcli completed successfully.

C:\Users\Administrator\Downloads\SMcli (1)\SMcli-02.00.00.0011\bin>
----


[[minimum-firmware-level]]
== Nivel de firmware mínimo

8.40
