---
permalink: commands-a-z/start-diskpool-locate.html 
sidebar: sidebar 
keywords: start, disk pool, locate 
summary: El comando start DISKPOOL locate identifica las unidades agrupadas lógicamente para formar el pool de discos especificado mediante el parpadeo de las luces indicadoras en las unidades. 
---
= Inicie la búsqueda de pool de discos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `start diskPool locate` el comando identifica las unidades que se agrupan lógicamente para formar el pool de discos especificado mediante el parpadeo de las luces indicadoras en las unidades.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

(Utilice la `stop diskPool locate` comando para apagar las luces indicadoras de las unidades).



== Sintaxis

[listing, subs="+macros"]
----
start diskPool pass:quotes[[_diskPoolName_]] locate
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`diskPool`
 a| 
El nombre del pool de discos respecto del cual se desea realizar la localización. El nombre del pool de discos debe escribirse entre corchetes ([ ]). Si el nombre del pool de discos tiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de los corchetes.

|===


== Nivel de firmware mínimo

7.83
