---
permalink: commands-a-z/start-increasevolumecapacity-volume.html 
sidebar: sidebar 
keywords: increase, capacity, volume, disk pool, volume, group 
summary: El comando start increaseVolumeCapacity volume aumenta la capacidad de un volumen estándar o un volumen de repositorios en un pool de discos o un grupo de volúmenes. 
---
= Aumentar la capacidad de volumen en un pool de discos o grupo de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `start increaseVolumeCapacity volume` aumenta la capacidad de un volumen estándar o de un volumen de repositorios en un pool de discos o un grupo de volúmenes.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

En este comando, el volumen estándar también se denomina volumen grueso.

[NOTE]
====
No es posible usar este comando para aumentar la capacidad de un volumen fino.

====


== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[start increaseVolumeCapacity volume="_volumeName_"
incrementalCapacity=_volumeCapacity_]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volume`
 a| 
El nombre del volumen de un pool de discos o grupo de volúmenes en el que se desea aumentar la capacidad. El nombre del volumen debe escribirse entre comillas dobles (" ").



 a| 
`incrementalCapacity`
 a| 
El ajuste para aumentar el tamaño de almacenamiento (capacidad) del volumen. El tamaño se define en unidades de `bytes`, `KB`, `MB`, `GB`, o. `TB`. El valor predeterminado es `bytes`.



 a| 
`addDrives`
 a| 
El ajuste para añadir nuevas unidades al volumen. En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).

[NOTE]
====
La `addDrives` el parámetro solo se puede usar para aumentar la capacidad de un grupo de volúmenes. El parámetro no puede usarse para aumentar la capacidad de un pool de discos.

====
|===


== Notas

En algunos casos a `drive` el parámetro puede aparecer como entrada válida para la sintaxis del comando. Sin embargo, no puede utilizar la `drive` parámetro con este comando.

Ajuste de `incrementalCapacity` parámetro, inicia una operación de ejecución prolongada que no se puede detener. Las operaciones de ejecución prolongada se realizan en segundo plano y no impiden la ejecución de otros comandos. Para mostrar el progreso de las operaciones de ejecución prolongada, use la `show volume actionProgress` comando.

La `addDrives` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.



== Nivel de firmware mínimo

7.83
