---
permalink: commands-a-z/start-diskpool-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, resource, provision 
summary: El comando start DISKPOOL resourceProvisioning permite el aprovisionamiento de recursos en un pool de discos determinado e inicia una operación asíncrona de habilitación de aprovisionamiento de recursos en cada volumen del pool de discos. El aprovisionamiento de recursos requiere que todas las unidades del pool de discos admitan la función DULBE de NVMe. 
---
= Iniciar el aprovisionamiento de recursos del grupo de discos - CLI de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start diskPool resourceProvisioning` el comando habilita el aprovisionamiento de recursos en un pool de discos determinado e inicia una operación asíncrona de habilitación de aprovisionamiento de recursos en cada volumen del pool de discos. El aprovisionamiento de recursos requiere que todas las unidades del pool de discos admitan la función DULBE de NVMe.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas las matrices EF600, EF300, EF50 y EF80; siempre que estén instalados todos los paquetes SMcli.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento EF600, EF300, EF50 y EF80, debes tener el rol de Storage Admin.



[[context]]
== Contexto

Para deshabilitar el aprovisionamiento de recursos en un pool de discos, utilice el comando de aprovisionamiento completo con la opción de deshabilitar el aprovisionamiento de recursos. Un pool de discos se aprovisionará cuando se cree si todas las unidades son compatibles con DULBE y las cabinas de almacenamiento `resourceProvisionedVolumes` el ajuste es `true`.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
start diskPoolpass:quotes[[_diskPoolName_]] resourceProvisioning
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`diskPoolName`
 a| 
El pool de discos desea habilitar la función de aprovisionamiento de recursos. El nombre del pool de discos debe escribirse entre corchetes ([ ]).

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

11.73
