---
permalink: commands-a-z/start-diskpool-locate.html 
sidebar: sidebar 
keywords: start, disk pool, locate 
summary: El comando start DISKPOOL locate identifica las unidades agrupadas lógicamente para formar el pool de discos especificado mediante el parpadeo de las luces indicadoras en las unidades. 
---
= Iniciar la localización del grupo de discos - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start diskPool locate` el comando identifica las unidades que se agrupan lógicamente para formar el pool de discos especificado mediante el parpadeo de las luces indicadoras en las unidades.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

(Utilice la `stop diskPool locate` comando para apagar las luces indicadoras de las unidades).



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
start diskPool pass:quotes[[_diskPoolName_]] locate
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`diskPool`
 a| 
El nombre del pool de discos respecto del cual se desea realizar la localización. El nombre del pool de discos debe escribirse entre corchetes ([ ]). Si el nombre del pool de discos tiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de los corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83
