---
permalink: commands-a-z/start-storagearray-locate.html 
sidebar: sidebar 
keywords: start, storage, array, locate 
summary: El comando start storageArray locate localiza una cabina de almacenamiento mediante el encendido de luces indicadoras de la cabina. 
---
= Iniciar la localización de la matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start storageArray locate` el comando localiza una cabina de almacenamiento mediante el encendido de luces indicadoras de la cabina de almacenamiento.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Utilice la `stop storageArray locate` comando para apagar las luces indicadoras de la cabina de almacenamiento.



== Sintaxis

[source, cli]
----
start storageArray locate
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

6.10
