---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: El comando start volume initialize inicia el formateo de un volumen en una cabina de almacenamiento. 
---
= Inicialización del volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start volume initialize` el comando inicia el formateo de un volumen en una cabina de almacenamiento.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

[NOTE]
====
El formateo de un volumen inicia una operación prolongada que no se puede detener.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`volume`
 a| 
El nombre de un volumen que se desea formatear. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

6.10
