---
permalink: commands-a-z/start-check-vol-parity-job.html 
sidebar: sidebar 
keywords: start, check, volume, parity, job 
summary: El comando start check volume parity job inicia una nueva operación check volume parity en un volumen determinado. 
---
= Iniciar la comprobación de paridad del volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start check volume parity job` el comando inicia una nueva operación de comprobación de paridad de volumen en un volumen determinado.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas las matrices EF600, EF300, EF50 y EF80; siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento EF600, EF300, EF50 y EF80, debes tener el rol de Storage Admin.



== Sintaxis

[source, cli, subs="+macros"]
----
start check volume[<volume_label>] parity job
(startingLba=<start_lba> endingLba=<end_lba> scanPriority=<scan_priority> repairParityErrors=<true | false>
repairMediaErrors=<true | false>);
----


== Parámetros

|===
| Parámetro | Descripción 


 a| 
`startingLba`
 a| 
La dirección del bloque lógico del volumen donde se iniciará el escaneo de paridad. El valor predeterminado es `0`.



 a| 
`endingLba`
 a| 
La dirección de bloque lógico de volúmenes donde se detendrá el escaneo de paridad. El valor predeterminado es `maximum volume lba`.



 a| 
`scanPriority`
 a| 
La prioridad de escaneo de paridad. El valor predeterminado es `medium`



 a| 
`repairParityErrors`
 a| 
Determina si se intentan automáticamente reparar los errores de paridad detectados durante el análisis de paridad. El valor predeterminado es `true`.



 a| 
`repairMediaErrors`
 a| 
Determina si se intentan automáticamente reparar los errores de medios detectados durante el análisis de paridad. El valor predeterminado es `true`.

|===


== Nivel de firmware mínimo

11,80
