---
permalink: commands-a-z/start-tray-locate.html 
sidebar: sidebar 
keywords: start, tray, locate 
summary: El comando start tray locate localiza un soporte mediante el encendido de la luz indicadora. 
---
= Localización de la bandeja de inicio - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start tray locate` el comando localiza un soporte mediante el encendido de la luz indicadora.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Utilice la `stop tray locate` comando para apagar la luz indicadora del soporte



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[start tray [_trayID_]] locate
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`tray`
 a| 
El soporte que se desea localizar. Los valores de ID de soporte son `0` para `99`. El valor de ID de soporte debe escribirse entre corchetes ([ ]).

|===


== Nivel de firmware mínimo

6.10
