---
permalink: commands-a-z/start-ssdcache-locate.html 
sidebar: sidebar 
keywords: start, ssd, cache, locate 
summary: 'El comando start ssdCache locate identifica los discos de estado sólido (SSD) agrupados lógicamente para formar la caché SSD mediante el parpadeo de las luces indicadoras en los SSD.' 
---
= Iniciar la localización de caché SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `start ssdCache locate` El comando identifica los discos de estado sólido (SSD) agrupados lógicamente para formar la caché SSD mediante el parpadeo de las luces indicadoras en los SSD.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Support Admin.



[[context]]
== Contexto

Utilice la `stop ssdCache locate` comando para apagar las luces indicadoras de las unidades.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`ssdCache`
 a| 
El nombre de la caché SSD que se desea localizar. El nombre de la caché SSD debe escribirse entre corchetes ([ ]). Si el nombre de la caché SSD incluye caracteres especiales o está compuesto solo de números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
