---
permalink: commands-a-z/stop-consistencygroup-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, images, consistency, group 
summary: El comando stop consistencyGroup pendingSnapImageCreation detiene todas las imágenes Snapshot pendientes que se deben crear en un grupo de coherencia Snapshot. 
---
= Detener las imágenes de instantáneas pendientes en el grupo de consistencia - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop consistencyGroup pendingSnapImageCreation` el comando detiene todas las imágenes snapshot pendientes que se van a crear en un grupo de coherencia snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Si el grupo de coherencia Snapshot no tiene imágenes Snapshot pendientes, el software de administración del almacenamiento muestra un mensaje de error y no ejecuta el comando.



== Sintaxis

[source, cli, subs="+macros"]
----
stop consistencyGroup pass:quotes[[_consistencyGroupName_]]pendingSnapImageCreation
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`consistencyGroupName`
 a| 
El nombre del grupo de coherencia para el que se desea detener cualquier operación Snapshot pendiente. El nombre del grupo de coherencia debe escribirse entre corchetes ([ ]). Si el nombre del grupo de coherencia tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de los corchetes.

|===


== Nivel de firmware mínimo

7.83
