---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: El comando stop storageArray driveFirmwareDownload detiene una descarga de firmware en las unidades de una cabina de almacenamiento que se inició con el comando download storageArray driveFirmware. 
---
= Detenga la descarga de firmware de la unidad de cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop storageArray driveFirmwareDownload` el comando detiene una descarga de firmware en las unidades de una cabina de almacenamiento que se inició con el `download storageArray driveFirmware` comando.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Este comando no detiene una descarga de firmware que ya se encuentra en curso en una unidad. Este comando detiene todas las descargas de firmware en las unidades con la descarga en espera.



== Sintaxis

[source, cli]
----
stop storageArray driveFirmwareDownload
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

6.10
