---
permalink: commands-a-z/stop-asyncmirrorgroup-rolechange.html 
sidebar: sidebar 
keywords: cancel, asynchronous, mirror, group, role, reversal 
summary: El comando stop asyncMirrorGroup rolechange cancela una operación de reversión de roles pendiente entre grupos de reflejos asíncronos. 
---
= Cancelar la inversión de roles del grupo de espejo asincrónico - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop asyncMirrorGroup rolechange` comando cancela una operación de reversión de roles pendiente entre grupos de reflejos asíncronos.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[stop asyncMirrorGroup [_asyncMirrorGroupName_]] rolechange
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`asyncMirrorGroup`
 a| 
Nombre del grupo de reflejos asíncronos para el que se desea cancelar la operación de reversión de roles pendiente. El nombre del grupo de reflejos asíncronos debe escribirse entre corchetes ([ ]). Si el nombre del grupo de reflejos asíncronos contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
