---
permalink: commands-a-z/stop-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, group, snapshot, images 
summary: El comando stop pendingSnapImageCreation cancela todas las imágenes Snapshot pendientes que se deben crear en una Snapshot o un grupo de coherencia Snapshot. 
---
= Detener el grupo de instantáneas con imágenes de instantáneas pendientes - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop pendingSnapImageCreation` el comando cancela todas las imágenes snapshot pendientes que se crean en una snapshot o un grupo de coherencia snapshot.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Si el grupo Snapshot no tiene imágenes Snapshot pendientes, el firmware muestra un mensaje de error y no ejecuta el comando. Este comando se puede ejecutar en un grupo Snapshot o un grupo de coherencia Snapshot.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
stop (snapGroup pass:quotes[[_snapGroupName_]] |
consistencyGroup pass:quotes[[_snapConsistencyGroupName_]])
pendingSnapImageCreation
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`snapGroup`
 a| 
El nombre del grupo Snapshot para el que se desean detener las imágenes Snapshot pendientes. El nombre del grupo Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo Snapshot tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`consistencyGroup`
 a| 
El nombre del grupo de coherencia Snapshot para el que se desea detener las imágenes Snapshot pendientes. El nombre del grupo de coherencia Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo de coherencia Snapshot contiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83
