---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: El comando stop storageArray driveFirmwareDownload detiene una descarga de firmware en las unidades de una cabina de almacenamiento que se inició con el comando download storageArray driveFirmware. 
---
= Detener la descarga del firmware de la unidad de matriz de almacenamiento - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop storageArray driveFirmwareDownload` el comando detiene una descarga de firmware en las unidades de una cabina de almacenamiento que se inició con el `download storageArray driveFirmware` comando.



== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



== Contexto

Este comando no detiene una descarga de firmware que ya se encuentra en curso en una unidad. Este comando detiene todas las descargas de firmware en las unidades con la descarga en espera.



== Sintaxis

[source, cli]
----
stop storageArray driveFirmwareDownload
----


== Parámetros

Ninguno.



== Nivel de firmware mínimo

6.10
