---
permalink: commands-a-z/stop-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: stop, drive, channel, fault, isolation, diagnostics 
summary: El comando stop driveChannel faultDiagnostics interrumpe el diagnóstico de aislamiento de fallos del canal de la unidad, lo cual detiene el comando start drive Channel fault isolation Diagnostics antes de que finalice. 
---
= Diagnóstico de aislamiento de fallas del canal de detención de la unidad - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop driveChannel faultDiagnostics` el comando detiene el diagnóstico de aislamiento de fallos del canal de la unidad, lo cual detiene el `start drive channel fault isolation diagnostics` antes de que finalice.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

[NOTE]
====
Con la versión de firmware 8.10, el `stop driveChannel faultDiagnostics` el comando queda obsoleto.

====


[[syntax]]
== Sintaxis

[source, cli]
----
stop driveChannel faultDiagnostics
----


[[parameters]]
== Parámetros

Ninguno.



[[notes]]
== Notas

Utilice la `start driveChannel faultDiagnostics` y la `save driveChannel faultDiagnostics` con el `stop driveChannel faultDiagnostics` comando. Estos comandos se necesitan para iniciar la prueba de diagnóstico y guardar los resultados de la prueba de diagnóstico en un archivo.

También puede detener la `start driveChannel faultDiagnostics` para ello, pulse `Ctrl+C`.



[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.15
