---
permalink: commands-a-z/stop-cgsnapvolume.html 
sidebar: sidebar 
keywords: stop, consistency, group, snapshot, volume 
summary: El comando stop cgSnapVolume detiene la operación de copia en escritura para crear un volumen Snapshot de grupo de coherencia. 
---
= Detener el volumen de instantáneas del grupo de consistencia - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop cgSnapVolume` el comando detiene la operación de copia en escritura para crear un volumen snapshot de grupo de coherencia.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[context]]
== Contexto

Para reiniciar la operación de copia en escritura, utilice `resume cgSnapVolume` comando.

[NOTE]
====
Este comando no elimina un volumen Snapshot de un grupo de coherencia. Para eliminar un volumen Snapshot de un grupo de coherencia, utilice `delete cgSnapVolume` comando.

====


[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[stop cgSnapVolume [_snapVolumeName_]]
----


[[parameter]]
== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`cgSnapVolume`
 a| 
El nombre del volumen Snapshot del grupo de coherencia del que se desea detener la creación. El nombre del volumen debe escribirse entre corchetes ([ ]). Si el nombre del volumen tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


[[minimum-firmware-level]]
== Nivel de firmware mínimo

7.83
