---
permalink: commands-a-z/stop-asyncmirrorgroup-rolechange.html 
sidebar: sidebar 
keywords: cancel, asynchronous, mirror, group, role, reversal 
summary: El comando stop asyncMirrorGroup rolechange cancela una operación de reversión de roles pendiente entre grupos de reflejos asíncronos. 
---
= Cancelar la reversión de roles en un grupo de reflejos asíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop asyncMirrorGroup rolechange` comando cancela una operación de reversión de roles pendiente entre grupos de reflejos asíncronos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[stop asyncMirrorGroup [_asyncMirrorGroupName_]] rolechange
----


== Parámetro

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`asyncMirrorGroup`
 a| 
Nombre del grupo de reflejos asíncronos para el que se desea cancelar la operación de reversión de roles pendiente. El nombre del grupo de reflejos asíncronos debe escribirse entre corchetes ([ ]). Si el nombre del grupo de reflejos asíncronos contiene caracteres especiales o está compuesto solo por números, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
