---
permalink: commands-a-z/stop-volumecopy-target-source.html 
sidebar: sidebar 
keywords: stop, volume, copy 
summary: El comando stop VolumeCopy target source detiene una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot. 
---
= Detener la copia de volumen - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop volumeCopy target source` el comando detiene una operación de copia de volumen. Este comando es válido para las parejas de copias de volumen Snapshot.



[[supported-arrays]]
== Cabinas compatibles

Este comando se aplica a cualquier matriz de almacenamiento individual, incluidas la E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 y EF80, siempre que todos los paquetes SMcli estén instalados.



[[roles]]
== Funciones

Para ejecutar este comando en una matriz de almacenamiento E4000, E2800, E5700, EF600, EF300, EF50 o EF80, debes tener el rol Storage Admin.



[[syntax]]
== Sintaxis

[source, cli, subs="+macros"]
----
pass:quotes[stop volumeCopy target [_targetName_]] source pass:quotes[[_sourceName_]]
----


[[parameters]]
== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`target`
 a| 
El nombre del volumen objetivo en el cual se desea detener una operación de copia de volumen. El nombre del volumen objetivo se debe escribir entre corchetes ([ ]). Si el nombre del volumen objetivo contiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes.



 a| 
`source`
 a| 
El nombre del volumen de origen en el cual se desea detener una operación de copia de volumen. El nombre del volumen de origen se debe escribir entre corchetes ([ ]). Si el nombre del volumen de origen contiene caracteres especiales o números, se debe escribir entre comillas dobles (" ") dentro de corchetes

|===