---
permalink: commands-a-z/stop-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, group, snapshot, images 
summary: El comando stop pendingSnapImageCreation cancela todas las imágenes Snapshot pendientes que se deben crear en una Snapshot o un grupo de coherencia Snapshot. 
---
= Detenga las imágenes Snapshot pendientes en el grupo Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `stop pendingSnapImageCreation` el comando cancela todas las imágenes snapshot pendientes que se crean en una snapshot o un grupo de coherencia snapshot.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Si el grupo Snapshot no tiene imágenes Snapshot pendientes, el firmware muestra un mensaje de error y no ejecuta el comando. Este comando se puede ejecutar en un grupo Snapshot o un grupo de coherencia Snapshot.



== Sintaxis

[source, cli, subs="+macros"]
----
stop (snapGroup pass:quotes[[_snapGroupName_]] |
consistencyGroup pass:quotes[[_snapConsistencyGroupName_]])
pendingSnapImageCreation
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`snapGroup`
 a| 
El nombre del grupo Snapshot para el que se desean detener las imágenes Snapshot pendientes. El nombre del grupo Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo Snapshot tiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.



 a| 
`consistencyGroup`
 a| 
El nombre del grupo de coherencia Snapshot para el que se desea detener las imágenes Snapshot pendientes. El nombre del grupo de coherencia Snapshot debe escribirse entre corchetes ([ ]). Si el nombre del grupo de coherencia Snapshot contiene caracteres especiales o números, debe escribirse entre comillas dobles (" ") dentro de corchetes.

|===


== Nivel de firmware mínimo

7.83
