---
permalink: commands-a-z/stop-drive-replace.html 
sidebar: sidebar 
keywords: stop, drive, replace 
summary: El comando stop drive replace detiene una operación de copia de datos que se inició con el comando set drive o replace drive más la entrada de usuario copyDrive. 
---
= Detener reemplazo de unidad
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La `stop drive replace` command detiene una operación de copia de datos que se ha iniciado en una `set drive` o un `replace drive` con el `*copyDrive*` entrada del usuario.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E2700, E5600, E2800, E5700, Cabinas EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Sintaxis

[listing]
----
stop drive replace ([trayID,[drawerID,]slotID] | <"wwID">)
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`drive`
 a| 
En el caso de los soportes de unidades de gran capacidad, es necesario indicar los valores de ID de soporte, ID de cajón e ID de ranura correspondientes a la unidad. En el caso de los soportes de unidades de baja capacidad, es necesario indicar los valores de ID de soporte e ID de ranura correspondientes a la unidad. Los valores de ID de soporte son `0` para `99`. Los valores de ID de cajón son `1` para `5`.

El valor máximo de ID de ranura es 24. Los valores de ID de ranura comienzan con 0 o 1, según el modelo de soporte. Los soportes de unidades compatibles con controladoras E2800 y E5700 tienen números de ID de ranura que comienzan con 0. Los soportes de unidades compatibles con controladoras E2700 y E5600 tienen números de ID de ranura que comienzan con 1.

Los valores de ID de soporte, de cajón y de ranura deben escribirse entre corchetes ([ ]).



 a| 
`drive`
 a| 
Identificador a nivel mundial (WWID) de la unidad que se desea reemplazar. El nombre del WWID debe escribirse entre comillas dobles (" ") entre paréntesis angulares (< >).

|===


== Notas

La `drive` el parámetro es compatible con soportes de unidades de alta y baja capacidad. Un soporte de unidades de gran capacidad tiene cajones que contienen las unidades. Los cajones se deslizan hacia afuera para permitir el acceso a las unidades. Un soporte de unidades de baja capacidad no tiene cajones. Para un soporte de unidades de gran capacidad, se deben especificar el identificador (ID) de soporte de unidades, el ID de cajón y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, solo se deben especificar el ID de soporte de unidades y el ID de ranura donde reside la unidad. Para un soporte de unidades de baja capacidad, un método alternativo para identificar la ubicación de una unidad es especificar el ID de soporte de unidades, establecer el ID de cajón en `0`, Y especifique el ID de la ranura en la que reside una unidad.



== Nivel de firmware mínimo

8.20
