---
permalink: commands-a-z/suspend-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: suspend, asynchronous, mirror, group 
summary: El comando suspend asyncMirrorGroup suspende la sincronización de datos en todas las parejas reflejadas en el nivel de grupo de reflejos asíncronos. 
---
= Suspender grupo de reflejos asíncronos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `suspend asyncMirrorGroup` el comando suspende la sincronización de datos en todas las parejas reflejadas en el nivel del grupo de reflejos asíncronos.



== Cabinas compatibles

Este comando se aplica a cualquier cabina de almacenamiento individual, incluidas las cabinas E4000, E2700, E5600, E2800, E5700, EF600 y EF300, siempre que estén instalados todos los paquetes SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de almacenamiento.



== Contexto

Este `suspend` comando ayuda a reducir cualquier impacto sobre el rendimiento de la aplicación host que puede producirse mientras se copian datos modificados de la cabina de almacenamiento local a la cabina de almacenamiento remota.



== Sintaxis

[source, cli, subs="+macros"]
----

pass:quotes[suspend asyncMirrorGroup [_asyncMirrorGroupName_]]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`asyncMirrorGroup`
 a| 
El nombre del grupo de reflejos asíncronos en el cual se desea suspender la sincronización de datos. El nombre del grupo de reflejos asíncronos debe escribirse entre corchetes ([ ]). Si el nombre del grupo de reflejos asíncronos contiene números o caracteres especiales, se debe escribir entre comillas dobles (" ") dentro de corchetes.

|===


== Notas

Cuando un grupo de reflejos asíncronos se encuentra en estado suspendido, no se intenta copiar los datos de los volúmenes primarios a los volúmenes secundarios de las parejas reflejadas. Toda escritura en el lado primario del grupo de reflejos asíncronos se registra de forma persistente en los volúmenes de repositorios de reflejos asociados. Una vez que se reanuda el grupo de reflejos asíncronos, solo las regiones modificadas de los volúmenes primarios se escriben en los volúmenes secundarios.



== Nivel de firmware mínimo

7.84

11,80 añade compatibilidad con cabinas EF600 y EF300
