---
permalink: commands-a-z/validate-storagearray-securitykey.html 
sidebar: sidebar 
keywords: validate, storage array, security key 
summary: El comando validate storageArray securityKey valida la clave de seguridad de una cabina de almacenamiento con unidades compatibles con la función de seguridad para garantizar que el archivo de claves de seguridad de respaldo no esté dañado. 
---
= Validar clave de seguridad de la cabina de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `validate storageArray securityKey` el comando valida la clave de seguridad de una cabina de almacenamiento con unidades compatibles con la función de seguridad para garantizar que el archivo de claves de seguridad de backup no esté dañado.



== Cabinas compatibles

Si la gestión de claves externas está habilitada, este comando solo se aplica a las cabinas E4000, E2800 y E5700. Si la gestión de claves internas está habilitada, este comando se aplica a cualquier cabina de almacenamiento individual, siempre que se hayan instalado todos los paquetes de SMcli.



== Funciones

Para ejecutar este comando en una cabina de almacenamiento E4000, E2800, E5700, EF600 o EF300, debe contar con el rol de administrador de seguridad.



== Contexto

En la validación de claves de seguridad, se emplea la frase de contraseña utilizada para generar el archivo para descifrar la clave y relacionarla con el valor que se mantiene en la memoria de la controladora (claves internas) o en el servidor externo (claves externas).

[NOTE]
====
Este comando se aplica a la gestión de claves interna y externa.

====


== Sintaxis

[source, cli, subs="+macros"]
----

pass:quotes[validate storageArray securityKey file="_fileName_" passPhrase="_passPhraseString_"]
----


== Parámetros

[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
`file`
 a| 
La ruta y el nombre del archivo que contiene la clave de seguridad. Escriba la ruta de acceso y el nombre del archivo entre comillas dobles (" "). Por ejemplo:

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
El nombre de archivo debe tener la extensión de `.slk`.

====


 a| 
`passPhrase`
 a| 
Una cadena de caracteres que cifra la clave de seguridad para poder almacenarla en un archivo externo. La frase de contraseña debe escribirse entre comillas dobles (" ").

|===


== Nivel de firmware mínimo

7.70
